Repository towhee-io/towhee, pull requests merged in 2021-11, with the labels that each got.

#283 Fix workflow error
  towhee/tests/__init__.py
  towhee/tests/engine/test_engine.py
  towhee/tests/engine/test_pipeline.py
Labels: lgtm, approved, size/S

#277 Rename TANSFORME to TRANSFORM
  towhee/tests/mock_operators/__init__.py
  towhee/tests/operators/test_pytorch_transform_operator.py
Labels: lgtm, approved, size/M

#278 Fix path problem in test_download
  towhee/tests/hub/test_download.py
Labels: lgtm, approved, size/XS

#285 CNN + NetVLAD feature extraction.
  towhee/models/layers/netvlad.py
  towhee/tests/models/layers/test_netvlad.py
Labels: lgtm, size/L, approved, component/layers

#271 Install dependency via requirements.txt
  requirements.txt
  setup.py
Labels: lgtm, approved, size/M

#287 add the retinaface model.
  towhee/models/layers/mixed_conv2d.py
  towhee/models/retina_face/__init__.py
  towhee/models/retina_face/configs.py
  towhee/models/retina_face/heads.py
  towhee/models/retina_face/mobilenet_v1.py
  towhee/models/retina_face/prior_box.py
  towhee/models/retina_face/retinaface.py
  towhee/models/retina_face/retinaface_fpn.py
  towhee/models/retina_face/ssh.py
  towhee/models/retina_face/utils.py
  towhee/models/utils/create_conv2d.py
  towhee/models/utils/create_conv2d_pad.py
  towhee/models/utils/pretrained_utils.py
Labels: lgtm, approved, size/XL, component/layers

#286 Singleton Filemanager
  towhee/__init__.py
  towhee/engine/__init__.py
  towhee/engine/operator_loader.py
  towhee/hub/__init__.py
  towhee/hub/file_manager.py
  towhee/hub/hub_tools.py
  towhee/tests/engine/test_engine.py
  towhee/tests/engine/test_operator_pool.py
  towhee/tests/engine/test_pipeline.py
  towhee/tests/engine/test_task_executor.py
  towhee/tests/hub/test_download.py
  towhee/tests/test_util/resnet50_embedding/resnet50_embedding.yaml
  towhee/tests/test_util/simple_pipeline/simple_pipeline.yaml
  towhee/tests/test_util/test_flatmap/flatmap_pipeline.yaml
Labels: lgtm, approved, size/XXL

#295 Slack hyperlink to badge
  README.md
Labels: lgtm, approved, size/XS

#298 Add basic function test cases
  tests/common/common_func.py
  tests/testcases/requirements.text
  tests/testcases/test_image_embedding.py
  tests/testcases/test_main.py
  tests/testcases/test_pipeline.py
Labels: lgtm, size/L, approved
