Repository towhee-io/towhee, pull requests merged in 2021-12, with the labels that each got.

#297 Adjust cache dirs
  towhee/hub/file_manager.py
  towhee/tests/hub/test_download.py
Labels: lgtm, approved, size/M

#300 Add publish dev package workflow
  .github/workflows/pr_test.yml
  .github/workflows/publish_dev_package.yml
  pyproject.toml
  setup.py
Labels: lgtm, approved, size/M

#290 Add embedding extractor
  towhee/models/embedding/embedding_extractor.py
  towhee/tests/models/embedding/cat.jpg
  towhee/tests/models/embedding/test_embedding_extractor.py
Labels: lgtm, size/L, approved

#308 remove redundant requirements
  requirements.txt
  setup.py
  test_requirements.txt
Labels: lgtm, approved, size/S

#311 Fix semi-circular import issue in python3.6
  towhee/engine/operator_io/__init__.py
Labels: lgtm, approved, size/S

#312 Update towhee version
  setup.py
Labels: lgtm, approved, size/XS

#313 Update towhee version for 0.3 branch
  setup.py
Labels: lgtm, approved, size/XS

#315 Adjust system according to the new repo structure
  towhee/__init__.py
  towhee/engine/operator_context.py
  towhee/engine/operator_loader.py
  towhee/hub/file_manager.py
  towhee/hub/hub_tools.py
Labels: lgtm, approved, size/M

#320 Allow passing YAML path to pipeline() to fix ci_test issue
  towhee/__init__.py
  towhee/hub/file_manager.py
  towhee/tests/hub/test_download.py
  towhee/tests/mock_pipelines/ci_test/ci_test.yaml
  towhee/tests/mock_pipelines/ci_test/towhee_logo.png
Labels: lgtm, size/L, approved

#323 Add generate_repo_yaml & init_file_structure to hub_tools
  towhee/hub/__init__.py
  towhee/hub/hub_tools.py
Labels: lgtm, size/L, approved

#318 Improved README
  README.md
Labels: lgtm, approved, size/M

#296 Multi-read + concat
  towhee/dataframe/dataframe.py
  towhee/engine/operator_context.py
  towhee/engine/operator_io/__init__.py
  towhee/engine/operator_io/reader.py
  towhee/tests/engine/operator_io/test_reader.py
  towhee/tests/engine/operator_runner/test_window_runner.py
  towhee/tests/engine/test_operator_context.py
  towhee/tests/engine/test_pipeline.py
  towhee/tests/mock_operators/add_operator_v2/__init__.py
  towhee/tests/mock_operators/add_operator_v2/add_operator_v2.py
  towhee/tests/mock_operators/concat_operator/__init__.py
  towhee/tests/mock_operators/concat_operator/concat_operator.py
  towhee/tests/test_util/test_concat/test_concat.yaml
Labels: lgtm, approved, size/XL

#325 Update hub download test
  towhee/tests/hub/test_download.py
Labels: lgtm, approved, size/XS

#329 add contributor name to readme file
  .github/workflows/all_contributors.yml
Labels: lgtm, approved, size/S

#326 Improve repo documentation
  CONTRIBUTING.md
  README.md
  STYLE_GUIDE.md
  docs/towhee_logo.png
  tests/testcases/test_image_object_embedding.py
  towhee_logo.png
Labels: lgtm, size/L, approved

#328 Compact `tests` in preparation for directory restructure
  tests/testcases/images/towhee_test_image0.jpg
  tests/testcases/images/towhee_test_image1.jpg
  tests/testcases/images/towhee_test_image2.jpg
  tests/testcases/test_image_object_embedding.py
Labels: lgtm, approved, size/XS

#334 change contribute check period to once per day
  .github/workflows/all_contributors.yml
Labels: lgtm, approved, size/XS

#335 Fix repo documentation
  CONTRIBUTING.md
  README.md
Labels: lgtm, approved, size/XS

#338 Improve repo governance
  OWNERS
Labels: lgtm, approved, size/S

#340 Move singleton to utils
  towhee/engine/engine.py
  towhee/hub/file_manager.py
  towhee/tests/engine/test_singleton.py
  towhee/utils/singleton.py
Labels: lgtm, approved, component/util, size/XS

#339 Fix for concat ndarray
  towhee/tests/mock_operators/concat_operator/concat_operator.py
Labels: lgtm, approved, size/XS

#353 Rename issue config
  .github/ISSUE_TEMPLATE/config.yml
Labels: lgtm, approved, size/XS

#348 Add encoder pipelines
  README.md
  towhee/__init__.py
Labels: lgtm, approved, size/S

#358 Update towhee rc1 version
  setup.py
Labels: lgtm, approved, size/XS

#359 Polish concat
  towhee/__init__.py
  towhee/engine/operator_context.py
  towhee/engine/operator_io/__init__.py
  towhee/engine/operator_io/reader.py
  towhee/engine/operator_io/writer.py
  towhee/engine/operator_loader.py
  towhee/engine/operator_runner/__init__.py
  towhee/engine/operator_runner/concat_runner.py
  towhee/engine/operator_runner/runner_base.py
  towhee/errors.py
  towhee/hub/file_manager.py
  towhee/operator/concat_operator.py
  towhee/tests/engine/operator_io/test_reader.py
  towhee/tests/engine/operator_runner/test_concat_runner.py
  towhee/tests/engine/operator_runner/test_filter_runner.py
  towhee/tests/engine/operator_runner/test_flatmap_runner.py
  towhee/tests/engine/operator_runner/test_generator_runner.py
  towhee/tests/engine/operator_runner/test_map_runner.py
  towhee/tests/engine/operator_runner/test_window_runner.py
  towhee/tests/engine/test_pipeline.py
  towhee/tests/engine/test_thread_pool_task_executor.py
  towhee/tests/mock_operators/concat_operator/concat_operator.py
  towhee/tests/test_util/test_concat/test_concat.yaml
Labels: lgtm, approved, component/engine, size/XL

#369 Build type system(Image) and add pil_utils and ndarray_utils
  towhee/tests/types/__init__.py
  towhee/tests/types/test_image.py
  towhee/tests/utils/test_ndarray_utils.py
  towhee/tests/utils/test_pil_utils.py
  towhee/types/__init__.py
  towhee/types/image.py
  towhee/utils/hub_tools.py
  towhee/utils/ndarray_utils.py
  towhee/utils/pil_utils.py
Labels: lgtm, approved, size/XL

#374 Remove test for offline pipeline
  tests/testcases/test_main.py
Labels: lgtm, approved, size/XS

#370 Update hub.hub_tools and delete utils.hub_tools
  towhee/hub/hub_tools.py
  towhee/tests/hub/test_download.py
  towhee/utils/hub_tools.py
Labels: lgtm, approved, size/XL

#373 Add rgb to bgr in ndarray utils and test
  towhee/tests/utils/test_ndarray_utils.py
  towhee/utils/ndarray_utils.py
Labels: lgtm, approved, size/M

#377 Support Windows directory separators
  towhee/engine/operator_loader.py
Labels: lgtm, approved, size/XS

#378 Fix operator pool bug
  towhee/engine/operator_pool.py
  towhee/tests/engine/operator_runner/test_generator_runner.py
  towhee/tests/engine/test_operator_pool.py
  towhee/tests/mock_operators/flat_operator/flat_operator.py
  towhee/tests/mock_operators/generator_operator/generator_operator.py
Labels: lgtm, approved, size/M

#381 Update release version
  setup.py
Labels: lgtm, approved, size/XS
