Repository towhee-io/towhee, pull requests merged in 2021-10, with the labels that each got.

#147 Resnet operator for image classification task.
  towhee/tests/dataset/imagenet_index_path.json
  towhee/tests/mock_operators/__init__.py
  towhee/tests/mock_operators/pytorch_image_classification_operator/__init__.py
  towhee/tests/mock_operators/pytorch_image_classification_operator/pytorch_image_classification_operator.py
  towhee/tests/operators/test_pytorch_image_classification_operator.py
Labels: lgtm, size/L, approved, component/operator

#161 Minor changes to readme and setup
  README.md
  setup.py
Labels: lgtm, approved, size/XS

#162 Use HandlerMixin in OperatorContext
  towhee/engine/graph_context.py
  towhee/engine/operator_context.py
  towhee/utils/handler_mixin.py
Labels: lgtm, approved, component/engine, size/S

#169 Earlier operator cache check and empty input check
  towhee/__init__.py
  towhee/engine/pipeline.py
Labels: lgtm, approved, size/S

#165 Use `HandlerMixin` in `Task`
  towhee/engine/operator_context.py
  towhee/engine/task.py
  towhee/tests/engine/test_task.py
  towhee/tests/engine/test_task_executor.py
Labels: lgtm, approved, component/engine, size/M

#175 adding tools for interacting with hub
  towhee/utils/hub_tools.py
Labels: lgtm, size/L, approved

#179 Implement multi-thread downloads
  towhee/utils/hub_tools.py
Labels: lgtm, size/L, approved

#178 Update the new issue template workflow
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: lgtm, size/L, approved

#212 Removing wonky setup logic
  setup.py
  towhee/__init__.py
Labels: lgtm, approved, size/S

#259 Add New `DataFrame`
  towhee/array/_array_ref.py
  towhee/array/array.py
  towhee/array/utils.py
  towhee/dataframe/dataframe_v2.py
  towhee/tests/array/test_array.py
  towhee/tests/dataframe/test_dataframe_v2.py
Labels: lgtm, approved, size/XL, component/dataframe

#268 add activation layer creators.
  towhee/models/layers/activations/__init__.py
  towhee/models/layers/activations/hardmish.py
  towhee/models/utils/create_act.py
  towhee/tests/models/utils/__init__.py
  towhee/tests/models/utils/create_act.py
Labels: lgtm, size/L, approved
