Repository towhee-io/towhee, pull requests merged in 2022-09, with the labels that each got.

#2012 quick hub docstring fixes
  towhee/hub/file_manager.py
Labels: lgtm, approved, size/M

#2015 Add doc test for tensor array
  towhee/types/__init__.py
  towhee/types/tensor_array.py
Labels: lgtm, approved, size/M

#2016 Add docstring for Entity and EntityView
  towhee/functional/entity.py
Labels: lgtm, approved, size/M

#2011 Add docstring for Conv3DBNActivation
  towhee/models/layers/conv_bn_activation.py
Labels: lgtm, approved, size/S

#2013 Add docstring for ConvMLP
  towhee/models/layers/convmlp.py
Labels: lgtm, approved, size/S

#2014 Add docstring for GatedMLP
  towhee/models/layers/gatedmlp.py
Labels: lgtm, approved, size/S

#2017 max vit init method arg type
  towhee/models/max_vit/max_vit.py
Labels: lgtm, approved, size/XS

#2018 add docstring for mlp of mvit
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/S

#2019 add docstring of Conv2dBN for mpvit
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/S

#2020 Small docstring updates
  towhee/hub/operator_manager.py
Labels: lgtm, approved, size/M

#2022 max vit create model doc str
  towhee/models/max_vit/max_vit.py
Labels: lgtm, approved, size/S

#2024 docstring singleton
  towhee/utils/singleton.py
Labels: lgtm, approved, size/XS

#2026 update docstring of dataframe test
  tests/unittests/dataframe/test_dataframe_v2.py
  tests/unittests/dataframe/test_iterators.py
Labels: lgtm, approved, size/XS

#2030 update docstring of engine test
  tests/unittests/engine/test_operator_pool.py
Labels: lgtm, approved, size/XS

#2025 rm dag/utils test
  tests/unittests/dag/utils/__init__.py
  tests/unittests/dag/utils/test_callstack.py
Labels: lgtm, size/L, approved

#2028 fix the comment of RelativeSelfAttention.
  towhee/models/layers/relative_self_attention.py
Labels: lgtm, approved, size/S

#2029 fix the comment of window_reverse.
  towhee/models/utils/window_reverse.py
Labels: lgtm, approved, size/S

#2033 format in max vit
  towhee/models/max_vit/max_vit.py
Labels: lgtm, approved, size/XS

#2032 rm dag/utils/callstack.py
  towhee/dag/utils/callstack.py
Labels: lgtm, size/L, approved

#2038 add docstring of DWConv2dBN for mpvit
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/S

#2034 Removed unused line
  towhee/functional/mixins/compile.py
Labels: lgtm, approved, size/XS

#2035 Update configmixin docstring
  towhee/functional/mixins/config.py
Labels: lgtm, approved, size/S

#2036 Update data_processing docstring
  towhee/functional/mixins/data_processing.py
Labels: lgtm, approved, size/XS

#2037 rm dag/utils
  towhee/dag/utils/__init__.py
Labels: lgtm, approved, size/S

#2021 Small docstring updates for manager
  towhee/hub/pipeline_manager.py
Labels: lgtm, approved, size/M

#2043 add docsring for DWConv2dBN of mpvit
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/S

#2041 Reformat functional docstring
  towhee/functional/__init__.py
Labels: lgtm, approved, size/S

#2042 Reformat datacollection docstring
  towhee/functional/data_collection.py
Labels: lgtm, approved, size/M

#2044 docstr for mmt
  towhee/models/mdmmt/mmt.py
Labels: lgtm, approved, size/XS

#2039 Few docstring updates
  towhee/__init__.py
Labels: lgtm, approved, size/M

#2040 Quick fix to docstring
  towhee/pipeline_format.py
Labels: lgtm, approved, size/XS

#2046 add docstring for FactorAttConvRelPosEnc of mpvit
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/M

#2047 add docstring of MHCABlock for mpvit
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/S

#2048 docstr for MMTVID in mmt
  towhee/models/mdmmt/mmt.py
Labels: lgtm, approved, size/XS

#2049 fix comment of CLIP4Clip.
  towhee/models/clip4clip/clip4clip.py
Labels: lgtm, approved, size/M

#2050 add mpvit methods return type
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/XS

#2052 fix the comment of RepMLPNetUnit.
  towhee/models/repmlp/repmlp.py
Labels: lgtm, approved, size/S

#2054 fix the comment of FFNBlock.
  towhee/models/layers/ffn.py
Labels: lgtm, approved, size/XS

#2055 fix task scheduler docstring
  towhee/engine/task_scheduler.py
Labels: lgtm, approved, size/XS

#2060 update some engine docstring
  towhee/engine/engine.py
  towhee/engine/factory.py
Labels: lgtm, approved, size/M

#2057 Update datamixin docstring
  towhee/functional/mixins/dataset.py
Labels: lgtm, approved, size/XS

#2056 Update safemixin docstring
  towhee/functional/mixins/safe.py
Labels: lgtm, approved, size/XS

#2058 Update dagmixin docstring
  towhee/functional/mixins/dag.py
Labels: lgtm, approved, size/XS

#2059 fix some engine docstring
  towhee/engine/graph_context.py
  towhee/engine/operator_loader.py
  towhee/engine/operator_registry.py
Labels: lgtm, approved, size/S

#2053 Add copyright
  tests/unittests/engine/operator_runner/__init__.py
Labels: lgtm, approved, size/S

#2061 Add copyright
  tests/unittests/engine/operator_io/__init__.py
Labels: lgtm, approved, size/S

#2062 Format code
  towhee/operator/base.py
Labels: lgtm, approved, size/XS

#2051 Activate doctest
  setup.cfg
  tests/unittests/types/test_tensor_array.py
Labels: lgtm, approved, size/XS

#2063 Add doc tests into unittest
  setup.cfg
  towhee/engine/factory.py
  towhee/functional/data_collection.py
  towhee/hub/builtin/operators/computer_vision.py
  towhee/hub/builtin/operators/faiss_search.py
  towhee/hub/builtin/operators/feature_engineer.py
  towhee/hub/builtin/operators/milvus_search.py
  towhee/hub/builtin/operators/tensor_like.py
Labels: lgtm, approved, size/M

#2065 Reformat data processing docstring
  towhee/functional/mixins/data_processing.py
Labels: lgtm, approved, size/S

#2067 add gpu weekly ci
  .github/workflows/publish_ut_image.yml
  .github/workflows/weekly_gpu_ci.yml
  GPUDockerfile
Labels: lgtm, size/L, approved

#2068 fix cron
  .github/workflows/weekly_gpu_ci.yml
Labels: lgtm, approved, size/XS

#2069 fix cuda version to 11.7.1
  GPUDockerfile
Labels: lgtm, approved, size/XS

#2070 Add ISC to towhee.models
  tests/unittests/models/isc/__init__.py
  tests/unittests/models/isc/test_isc.py
  towhee/models/isc/__init__.py
  towhee/models/isc/isc.py
Labels: lgtm, size/L, approved, component/models

#2045 Support jit in triton
  tests/unittests/triton/expected_files/py_to_triton_test/1/dc_config.json
  tests/unittests/triton/expected_files/py_to_triton_test/1/model.py
  tests/unittests/triton/expected_files/resnet50_model.py
  tests/unittests/triton/test_to_triton.py
  towhee/serve/triton/constant.py
  towhee/serve/triton/dockerfiles/DockerfileCuda113
  towhee/serve/triton/dockerfiles/DockerfileCuda114
  towhee/serve/triton/dockerfiles/DockerfileCuda114dev
  towhee/serve/triton/dockerfiles/DockerfileCuda116
  towhee/serve/triton/python_model_builder.py
  towhee/serve/triton/to_triton_models.py
Labels: lgtm, approved, size/M

#2074 Add contributors from examples repo
  .github/workflows/all_contributors.yml
Labels: lgtm, approved, size/S

#2075 Update contributor repos
  .github/workflows/all_contributors.yml
Labels: lgtm, approved, size/XS

#2079 Codecov add gcc and g++
  .github/workflows/codecov.yml
Labels: lgtm, approved, size/XS

#2072 Allow operators to output nothing
  towhee/engine/execution/base_execution.py
  towhee/functional/mixins/dag.py
Labels: lgtm, approved, size/S

#2078 Add ut and prompt_install for compilemixin
  test_requirements.txt
  tests/unittests/functional/test_mixins.py
  towhee/functional/mixins/compile.py
  towhee/functional/mixins/metric.py
  towhee/utils/jit_utils.py
Labels: lgtm, size/L, approved

#2081 Doc fix and add DataProcessingMixin
  towhee/doc/requirements.txt
  towhee/doc/source/data_collection/mixins.rst
Labels: lgtm, approved, size/XS

#2087 Update ut about compile
  tests/unittests/functional/test_mixins.py
Labels: lgtm, approved, size/M

#2085 Add merge in data_processing
  towhee/functional/mixins/data_processing.py
Labels: lgtm, approved, size/M

#2088 replace merge by group_by
  towhee/functional/mixins/data_processing.py
Labels: lgtm, approved, size/M

#2089 Add leveldb mixin for kvstorage
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/kv_storage.py
  towhee/utils/thirdparty/plyvel_utils.py
Labels: lgtm, size/L, approved

#2092 Modify encoder
  towhee/functional/mixins/kv_storage.py
Labels: lgtm, approved, size/XS

#2083 Fix typeerror with a function
  tests/unittests/functional/test_dispatcher.py
  towhee/functional/data_collection.py
Labels: lgtm, size/L, approved

#2100 update apt-get
  .github/workflows/codecov.yml
Labels: lgtm, approved, size/XS

#2098 Add model for ConvNeXt
  tests/unittests/models/convnext/test_model.py
  towhee/models/convnext/__init__.py
  towhee/models/convnext/convnext.py
Labels: lgtm, size/L, approved, component/models

#2105 bugfix for leveldb mixin
  towhee/functional/mixins/kv_storage.py
  towhee/utils/thirdparty/plyvel_utils.py
Labels: lgtm, approved, size/XS

#2104 Add configs & API to create ConvNeXt by model name
  tests/unittests/models/convnext/test_model.py
  towhee/models/convnext/__init__.py
  towhee/models/convnext/configs.py
  towhee/models/convnext/convnext.py
Labels: lgtm, size/L, approved, component/models

#2109 add text extractor to mcprop
  tests/unittests/models/mcprop/test_textextractor.py
  towhee/models/mcprop/__init__.py
  towhee/models/mcprop/textextractor.py
Labels: lgtm, approved, size/M

#2110 Refactor flatten and group_by
  towhee/functional/mixins/data_processing.py
  towhee/functional/mixins/kv_storage.py
Labels: lgtm, size/L, approved

#2114 add transformerpooling for mcprop
  tests/unittests/models/mcprop/test_transformerpooling.py
  towhee/models/mcprop/transformerpooling.py
Labels: lgtm, approved, size/M

#2117 add image extractor for mcprop
  tests/unittests/models/mcprop/test_imageextractor.py
  towhee/models/mcprop/imageextractor.py
Labels: lgtm, approved, size/M

#2118 fix docstring of ImageExtractor
  towhee/models/mcprop/imageextractor.py
Labels: lgtm, approved, size/XS

#2119 add depth aggregator for mcprop
  tests/unittests/models/mcprop/test_depthaggregator.py
  towhee/models/mcprop/depthaggregator.py
Labels: lgtm, size/L, approved

#2120 add feature fusion for mcprop
  tests/unittests/models/mcprop/test_featurefusion.py
  towhee/models/mcprop/featurefusion.py
Labels: lgtm, approved, size/M

#2122 fix depth aggregator for mcprop
  tests/unittests/models/mcprop/test_depthaggregator.py
  towhee/models/mcprop/depthaggregator.py
Labels: lgtm, approved, size/XS

#2126 Add utils for HorNet
  tests/unittests/models/hornet/__init__.py
  tests/unittests/models/hornet/test_utils.py
  towhee/models/hornet/__init__.py
  towhee/models/hornet/utils.py
Labels: lgtm, size/L, approved

#2129 Add HorNet model
  tests/unittests/models/hornet/test_model.py
  tests/unittests/models/hornet/test_utils.py
  towhee/models/hornet/__init__.py
  towhee/models/hornet/hornet.py
Labels: lgtm, size/L, approved, component/models

#2133 Add download tools to towhee.models.utils
  tests/unittests/models/utils/test_download.py
  towhee/models/utils/download.py
Labels: lgtm, size/L, approved, component/models

#2136 Add pretrained models & configs for HorNet
  tests/unittests/models/hornet/test_model.py
  towhee/models/hornet/__init__.py
  towhee/models/hornet/configs.py
  towhee/models/hornet/hornet.py
  towhee/models/utils/download.py
Labels: lgtm, size/L, approved, model, component/models

#2138 add matching module for mcprop
  tests/unittests/models/mcprop/test_matcher.py
  towhee/models/mcprop/loss.py
  towhee/models/mcprop/matching.py
Labels: lgtm, size/L, approved

#2139 add transforms api for clip
  tests/unittests/models/clip/test_transforms.py
  towhee/models/clip/clip.py
Labels: lgtm, approved, size/M

#2141 Allow flatten multi columns
  towhee/functional/mixins/data_processing.py
Labels: lgtm, approved, size/XS

#2142 add groupnorm for poolformer
  tests/unittests/models/poolformer/test_groupnorm.py
  towhee/models/poolformer/groupnorm.py
Labels: lgtm, approved, size/M

#2144 add pooling for poolformer
  tests/unittests/models/poolformer/test_pooling.py
  towhee/models/poolformer/pooling.py
Labels: lgtm, approved, size/M

#2145 add poolformer block for poolformer
  tests/unittests/models/poolformer/test_poolformerblock.py
  towhee/models/poolformer/poolformerblock.py
Labels: lgtm, size/L, approved

#2147 add basic blocks for poolformer
  tests/unittests/models/poolformer/test_basic_blocks.py
  towhee/models/poolformer/basic_blocks.py
Labels: lgtm, approved, size/M

#2146 Update docs with specified branch
  .github/workflows/check-docs-update.yml
Labels: lgtm, approved, size/XS

#2149 Update command-line-tool docs
  docs/03-User Guides/01-command-line-tool.md
Labels: lgtm, size/L, approved

#2080 Add triton README
  towhee/serve/triton/README.md
  towhee/serve/triton/qps.png
Labels: lgtm, size/L, approved

#2140 Update operator template in cmd
  tests/unittests/command/test_cmdline.py
  tests/unittests/hub/test_operator_manager.py
  towhee/command/README.md
  towhee/command/repo.py
  towhee/hub/operator_manager.py
  towhee/hub/repo_manager.py
Labels: lgtm, approved, size/M

#2151 Add Jinja2<=3.0.3 require
  towhee/doc/requirements.txt
Labels: lgtm, approved, size/XS

#2153 Add api reference in 0.8.0 docs
  docs/01-Overview.md
Labels: lgtm, approved, size/XS

#2154 Add api reference in docs
  docs/01-Overview.md
Labels: lgtm, approved, size/XS

#2148 Fix some docstring issue
  towhee/functional/mixins/data_processing.py
Labels: lgtm, approved, size/S

#2150 Remove ruamel from towhee dependency
  towhee/dag/base_repr.py
Labels: lgtm, approved, size/XS

#2152 Add pyarrow as req
  requirements.txt
Labels: lgtm, approved, size/XS

#2157 add mlp specified by poolformer
  tests/unittests/models/poolformer/test_mlp.py
  towhee/models/poolformer/mlp.py
Labels: lgtm, approved, size/M

#2158 add patchembed specified by poolformer
  tests/unittests/models/poolformer/test_patchembed.py
  towhee/models/poolformer/patchembed.py
Labels: lgtm, approved, size/M

#2160 replace mlp in poolformerblock with specified mlp
  towhee/models/poolformer/poolformerblock.py
Labels: lgtm, approved, size/XS

#2161 add poolformer model api
  tests/unittests/models/poolformer/test_poolformermodel.py
  towhee/models/poolformer/poolformer.py
Labels: lgtm, size/L, approved

#2162 add addpositionembed for metaformer
  tests/unittests/models/metaformer/test_addpositionembed.py
  towhee/models/metaformer/addpositionembed.py
Labels: lgtm, approved, size/M

#2163 add meteformer's specified attention module
  tests/unittests/models/metaformer/test_attention.py
  towhee/models/metaformer/attention.py
Labels: lgtm, approved, size/M

#2164 add spatialfc for metaformer
  tests/unittests/models/metaformer/test_spatialfc.py
  towhee/models/metaformer/spatialfc.py
Labels: lgtm, approved, size/M

#2166 add metaformer block for metaformer
  tests/unittests/models/metaformer/test_metaformerblock.py
  towhee/models/metaformer/metaformerblock.py
Labels: lgtm, size/L, approved

#2167 Update check docs workflow
  .github/workflows/check-docs-update.yml
Labels: lgtm, approved, size/XS

#2170 Update check docs workflow 0.8.1
  .github/workflows/check-docs-update.yml
  docs/01-Overview.md
Labels: lgtm, approved, size/XS

#2168 add basicblocks for metaformer
  tests/unittests/models/metaformer/test_basicblocks.py
  towhee/models/metaformer/basicblocks.py
Labels: lgtm, approved, size/M

#2172 add metaformer api
  tests/unittests/models/metaformer/test_metaformermodel.py
  towhee/models/metaformer/metaformer.py
Labels: lgtm, size/L, approved

#2171 Add ut for kv storage
  tests/unittests/functional/test_mixins.py
Labels: lgtm, approved, size/S

#2175 add activation for vis4mer
  tests/unittests/models/vis4mer/test_activation.py
  towhee/models/vis4mer/activation.py
Labels: lgtm, approved, size/M

#2178 Update towhee version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#2173 Reduce calculation & add device for metaformer ut
  tests/unittests/models/metaformer/test_addpositionembed.py
  tests/unittests/models/metaformer/test_attention.py
  tests/unittests/models/metaformer/test_basicblocks.py
  tests/unittests/models/metaformer/test_metaformerblock.py
  tests/unittests/models/metaformer/test_metaformermodel.py
  tests/unittests/models/metaformer/test_spatialfc.py
Labels: lgtm, approved, size/M, component/models

#2174 Replace download tool in clip with towhee.models.utils.download
  towhee/models/clip/clip.py
  towhee/models/clip/clip_utils.py
Labels: lgtm, approved, size/M, component/models

#2179 add transposelinear for vis4mer
  tests/unittests/models/vis4mer/test_transposelinear.py
  towhee/models/vis4mer/__init__.py
  towhee/models/vis4mer/transposelinear.py
Labels: lgtm, approved, size/M

#2177 Optimize ut for poolformer
  tests/unittests/models/poolformer/test_basic_blocks.py
  tests/unittests/models/poolformer/test_groupnorm.py
  tests/unittests/models/poolformer/test_layernormchannel.py
  tests/unittests/models/poolformer/test_mlp.py
  tests/unittests/models/poolformer/test_patchembed.py
  tests/unittests/models/poolformer/test_poolformerblock.py
  tests/unittests/models/poolformer/test_poolformermodel.py
  tests/unittests/models/poolformer/test_pooling.py
Labels: lgtm, approved, size/M, component/models

#2180 Update towhee version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS
