Repository towhee-io/towhee, pull requests merged in 2022-11, with the labels that each got.

#2243 Add OverlapPatchEmbed for shunted transformer
  tests/unittests/models/shunted_transformer/__init__.py
  tests/unittests/models/shunted_transformer/test_utils.py
  towhee/models/shunted_transformer/__init__.py
  towhee/models/shunted_transformer/utils.py
Labels: lgtm, approved, size/M, component/models

#2246 Add modified Mlp for shunted transformer
  tests/unittests/models/shunted_transformer/test_utils.py
  towhee/models/shunted_transformer/utils.py
Labels: lgtm, approved, size/M, component/models

#2247 Add modified Attention for shunted transformer
  tests/unittests/models/shunted_transformer/test_utils.py
  towhee/models/shunted_transformer/utils.py
Labels: lgtm, size/L, approved, component/models

#2241 Updata pipeline and add examples
  tests/unittests/runtime/test_operator_action.py
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/dag_repr.py
  towhee/runtime/operator_manager/operator_action.py
  towhee/runtime/pipeline.py
Labels: lgtm, approved, size/XL

#2249 Add block for shunted transformer
  tests/unittests/models/shunted_transformer/test_utils.py
  towhee/models/shunted_transformer/utils.py
Labels: lgtm, approved, size/M, component/models

#2253 Install gcc & g++ in weekly ci
  .github/workflows/weekly_ci.yml
Labels: lgtm, approved, size/XS

#2254 Update window check
  tests/unittests/runtime/test_check_util.py
  towhee/runtime/check_utils.py
Labels: lgtm, approved, size/XS

#2255 Add patch embedding head for shunted transformer
  tests/unittests/models/shunted_transformer/test_utils.py
  towhee/models/shunted_transformer/utils.py
Labels: lgtm, approved, size/M, component/models

#2256 Add shunted transformer model
  tests/unittests/models/shunted_transformer/test_model.py
  towhee/models/shunted_transformer/__init__.py
  towhee/models/shunted_transformer/shunted_transformer.py
  towhee/models/shunted_transformer/utils.py
Labels: lgtm, size/L, approved, component/models

#2258 Add configs and model names for pretrained shunted transformer
  tests/unittests/models/shunted_transformer/test_model.py
  towhee/models/shunted_transformer/__init__.py
  towhee/models/shunted_transformer/configs.py
  towhee/models/shunted_transformer/shunted_transformer.py
Labels: lgtm, size/L, approved, component/models

#2257 fix map bug
  tests/unittests/runtime/test_map_node.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/operator_manager/operator_loader.py
Labels: lgtm, approved, size/M

#2264 Update test version
  tests/testcases/requirements.text
Labels: lgtm, approved, size/XS

#2266 Recognize Empty in nodes
  towhee/runtime/nodes/_filter.py
  towhee/runtime/nodes/_flat_map.py
  towhee/runtime/nodes/_map.py
Labels: lgtm, approved, size/XS

#2267 add more clip pretrained models.
  towhee/models/clip/clip_utils.py
Labels: lgtm, approved, size/M

#2263 Install gcc & g++ in weekly gpu ci
  .github/workflows/weekly_gpu_ci.yml
Labels: lgtm, approved, size/XS

#2270 Fix concat bug
  tests/unittests/runtime/test_concat.py
  towhee/runtime/data_queue.py
  towhee/runtime/nodes/_concat.py
Labels: lgtm, approved, size/M

#2268 add publish models package workflow
  .github/workflows/publish_model_package.yml
Labels: lgtm, approved, size/M

#2269 add transform config for each CLIP model.
  towhee/models/clip/clip_utils.py
Labels: lgtm, approved, size/S

#2276 Constrain fastapi version
  test_requirements.txt
Labels: lgtm, approved, size/XS

#2275 Add create_model to towhee.models.utils
  towhee/models/replknet/replknet.py
  towhee/models/utils/__init__.py
  towhee/models/utils/create_model.py
Labels: lgtm, approved, size/M, component/models

#2277 Replace create_model with towhee.models.utils
  tests/unittests/models/cvnet/test_cvnet.py
  towhee/models/convnext/convnext.py
  towhee/models/cvnet/cvnet.py
  towhee/models/hornet/hornet.py
  towhee/models/max_vit/max_vit.py
Labels: lgtm, size/L, approved, component/models

#2278 Replace create_model for repmlp & shunted_transformer
  towhee/models/repmlp/repmlp.py
  towhee/models/shunted_transformer/shunted_transformer.py
Labels: lgtm, approved, size/M, component/models

#2272 Assign name for each node
  tests/unittests/runtime/test_concat.py
  tests/unittests/runtime/test_config.py
  tests/unittests/runtime/test_dag_repr.py
  tests/unittests/runtime/test_filter_node.py
  tests/unittests/runtime/test_flat_map_node.py
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_node_repr.py
  tests/unittests/runtime/test_time_window_node.py
  tests/unittests/runtime/test_window_all.py
  tests/unittests/runtime/test_window_node.py
  towhee/runtime/check_utils.py
  towhee/runtime/constants.py
  towhee/runtime/dag_repr.py
  towhee/runtime/node_config.py
  towhee/runtime/node_repr.py
  towhee/runtime/nodes/node.py
  towhee/runtime/pipeline.py
Labels: lgtm, size/L, approved

#2279 Allow towhee.models.tools to download file by gdrive link
  towhee/models/replknet/configs.py
  towhee/models/utils/__init__.py
  towhee/models/utils/download.py
Labels: lgtm, approved, size/M, component/models

#2280 Add constants OPType
  towhee/runtime/constants.py
  towhee/runtime/dag_repr.py
  towhee/runtime/nodes/node.py
  towhee/runtime/operator_manager/operator_action.py
Labels: lgtm, approved, size/M

#2281 Add runtime config
  tests/unittests/runtime/test_runtim_config.py
  towhee/_types/__init__.py
  towhee/operator/base.py
  towhee/runtime/__init__.py
  towhee/runtime/dag_repr.py
  towhee/runtime/node_config.py
  towhee/runtime/nodes/node.py
  towhee/runtime/runtime_conf.py
  towhee/types/__init__.py
Labels: lgtm, size/L, approved

#2288 Fix filter bug
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/nodes/_filter.py
Labels: lgtm, approved, size/S

#2283 add fuction, s3 don't download if files in local path
  tests/unittests/command/test_s3.py
  towhee/command/s3.py
Labels: lgtm, approved, size/M

#2290 Add check schema in pipeline
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/pipeline.py
Labels: lgtm, approved, size/M

#2291 Fix issue to concat none
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/dag_repr.py
  towhee/runtime/pipeline.py
Labels: lgtm, approved, size/S

#2292 support path add bucket_name
  towhee/command/s3.py
Labels: lgtm, approved, size/S

#2297 support absolute path and solve error friendly
  towhee/command/s3.py
Labels: lgtm, approved, size/S

#2300 Fix CLIP with multilingual model
  towhee/models/clip/clip.py
Labels: lgtm, approved, size/XS, component/models

#2282 Add test cases on new pipeline nodes
  tests/testcases/requirements.text
  tests/testcases/test_data_collection.py
  tests/testcases/test_main.py
Labels: lgtm, size/L, approved

#2302 Fix broken link
  docs/02-Getting Started/01-quick-start.mdx
Labels: lgtm, approved, size/XS, kind/documentation

#2303 Fix broken links
  docs/02-Getting Started/01-quick-start.mdx
Labels: lgtm, approved, size/XS, kind/documentation

#2304 np format
  tests/unittests/utils/test_np_format.py
  towhee/utils/np_format.py
Labels: lgtm, size/L, approved

#2305 Fix callable class
  tests/unittests/runtime/test_config.py
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/dag_repr.py
  towhee/runtime/pipeline.py
Labels: lgtm, approved, size/M

#2306 Callable bugs
  tests/unittests/runtime/test_config.py
  tests/unittests/runtime/test_user_pipeline.py
  tests/unittests/utils/test_np_format.py
  towhee/runtime/dag_repr.py
  towhee/runtime/pipeline.py
  towhee/utils/np_format.py
Labels: lgtm, size/L, approved

#2307 Fix isc: no need to load pretrained backbone
  towhee/models/isc/isc.py
Labels: lgtm, approved, size/XS, component/models

#2308 Add pipe triton model
  test_requirements.txt
  tests/unittests/triton/bls/model_runner/__init__.py
  tests/unittests/triton/bls/model_runner/generator_model_config.json
  tests/unittests/triton/bls/model_runner/map_model_config.json
  tests/unittests/triton/bls/model_runner/test_generator_model.py
  tests/unittests/triton/bls/model_runner/test_map_model.py
  tests/unittests/triton/bls/model_runner/test_transformer.py
  tests/unittests/triton/bls/test_pipeline_model.py
  towhee/runtime/runtime_pipeline.py
  towhee/serve/triton/bls/mock/mock_pb_util.py
  towhee/serve/triton/bls/mock/mock_triton_client.py
  towhee/serve/triton/bls/model_runner/__init__.py
  towhee/serve/triton/bls/model_runner/generator_model.py
  towhee/serve/triton/bls/model_runner/map_model.py
  towhee/serve/triton/bls/model_runner/transformer.py
  towhee/serve/triton/bls/pipeline_model.py
Labels: lgtm, approved, size/XL

#2298 Add test cases on new command
  tests/testcases/test_command.py
  tests/testcases/test_main.py
Labels: lgtm, size/L, approved

#2311 Add test picture path of op expansionnet-v2
  tests/testcases/hub/execute_hub_operators.py
Labels: lgtm, approved, size/XS
