Repository towhee-io/towhee, pull requests merged in 2022-06, with the labels that each got.

#1311 fix for 1305
  towhee/dataframe/iterators.py
Labels: lgtm, approved, size/S

#1315 Replace torchvideo transforms with submodules
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/M

#1318 Add save_model to NNOperator
  tests/unittests/models/clip/test_pretrained.py
  tests/unittests/models/violet/test_violet.py
  tests/unittests/operators/test_operator_base.py
  towhee/operator/base.py
Labels: lgtm, approved, size/M

#1312 Support col-based computing with ndarray
  towhee/engine/factory.py
  towhee/functional/data_collection.py
  towhee/functional/entity_view.py
  towhee/functional/mixins/column.py
  towhee/hub/builtin/operators/tensor_like.py
  towhee/types/tensor_array.py
Labels: lgtm, size/L, approved

#1317 Add new model: frozen_in_time
  test_requirements.txt
  tests/unittests/models/frozen_in_time/__init__.py
  tests/unittests/models/frozen_in_time/test_frozen_in_time.py
  tests/unittests/models/frozen_in_time/test_frozen_utils.py
  towhee/models/frozen_in_time/__init__.py
  towhee/models/frozen_in_time/frozen_in_time.py
  towhee/models/frozen_in_time/frozen_utils.py
  towhee/models/frozen_in_time/frozen_video_transformer.py
Labels: lgtm, approved, size/XL

#1320 Update test version
  tests/testcases/requirements.text
  tests/testcases/test_data_collection.py
  tests/testcases/test_main.py
Labels: lgtm, approved, size/M

#1314 AudioFrame add layout info
  tests/unittests/types/test_audio_frame.py
  towhee/types/audio_frame.py
Labels: lgtm, approved, size/S

#1326 modify unittest of tsm
  tests/unittests/models/tsm/test_tsm.py
Labels: lgtm, approved, size/M, model

#1335 Dependency
  requirements.txt
  towhee/utils/thirdparty/__init__.py
Labels: lgtm, approved, size/S

#1331 fix #1275
  towhee/doc/source/data_collection/get_started.rst
  towhee/doc/source/towhee/towhee.rst
  towhee/functional/__init__.py
Labels: lgtm, approved, size/M

#1339 add dummy input
  towhee/__init__.py
  towhee/functional/__init__.py
Labels: lgtm, approved, size/M

#1336 Support show video
  towhee/functional/mixins/display.py
Labels: lgtm, approved, size/M

#1338 Replace download method for timesformer
  towhee/models/timesformer/timesformer_utils.py
Labels: lgtm, approved, size/S

#1337 Bugfix/0 6 2
  test_requirements.txt
  towhee/dataframe/iterators.py
  towhee/doc/source/data_collection/get_started.rst
  towhee/doc/source/towhee/towhee.rst
  towhee/functional/__init__.py
  towhee/models/utils/video_transforms.py
Labels: lgtm, size/L, approved

#1344 replace _OperatorLazyWrapper with mixins
  towhee/engine/execution/base_execution.py
  towhee/engine/execution/pandas_execution.py
  towhee/engine/execution/stateful_execution.py
  towhee/engine/execution/vectorized_execution.py
  towhee/engine/factory.py
Labels: lgtm, size/L, approved

#1349 Change CI test machine
  .github/workflows/pr_test.yml
Labels: lgtm, approved, size/XS

#1319 clip visualization
  docs/02-Getting Started/02-install.md
Labels: lgtm, approved, size/XS

#1352 Add benchmark notebook and update benchmark report in doc
  towhee/benchmark/benchmark_report.ipynb
  towhee/doc/source/benchmark/column-based-benchmark-report.md
Labels: lgtm, size/L, approved

#1353 Add __init__.py for execution engines
  towhee/engine/execution/__init__.py
Labels: lgtm, approved, size/XS

#1346 add forward_features
  towhee/models/tsm/tsm.py
Labels: lgtm, approved, size/S, model

#1354 Add towhee.models in installation doc
  docs/02-Getting Started/02-install.md
Labels: lgtm, approved, size/XS

#1355 clip visualization
  tests/unittests/trainer/test_visualization_util.py
  towhee/models/clip/auxilary.py
  towhee/models/clip/clip.py
  towhee/trainer/utils/visualization.py
Labels: lgtm, approved, size/XL

#1356 refactor visualization directory
  docs/05-Tutorials/01-Fine Tune/Train operators/train-a-bird-classification-model.md
  docs/05-Tutorials/01-Fine Tune/Train operators/train-cub-200-2011.md
  tests/unittests/models/visualization/__init__.py
  tests/unittests/models/visualization/test_clip_vis.py
  tests/unittests/models/visualization/test_transformer_vis.py
  tests/unittests/trainer/test_plot_util.py
  towhee/models/visualization/__init__.py
  towhee/models/visualization/clip_visualization.py
  towhee/models/visualization/transformer_visualization.py
  towhee/trainer/utils/plot_utils.py
Labels: lgtm, approved, size/XL

#1362 MViT model visualization
  tests/unittests/models/visualization/test_transformer_vis.py
  towhee/models/layers/layers_with_relprop.py
  towhee/models/multiscale_vision_transformers/__init__.py
  towhee/models/multiscale_vision_transformers/create_multiscale_vision_transformers.py
  towhee/models/multiscale_vision_transformers/create_mvit.py
  towhee/models/multiscale_vision_transformers/multiscale_vision_transformers.py
  towhee/models/multiscale_vision_transformers/mvit.py
  towhee/models/visualization/clip_visualization.py
  towhee/models/visualization/transformer_visualization.py
  towhee/models/vit/vit.py
  towhee/utils/log.py
Labels: lgtm, approved, size/XXL

#1363 tsm modify
  towhee/models/tsm/tsm.py
Labels: lgtm, approved, size/M, component/models

#1364 Update to_milvus to steam
  towhee/functional/mixins/milvus_mixin.py
Labels: lgtm, approved, size/XS

#1359 add load pretrained function to video_swin_transformer
  tests/unittests/models/video_swin_transformer/test_video_swin_transformer.py
  towhee/models/video_swin_transformer/video_swin_transformer.py
Labels: lgtm, size/L, approved

#1357 refactoring execution for arrow-based data frame
  towhee/engine/execution/vectorized_execution.py
  towhee/engine/factory.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/column.py
  towhee/hub/builtin/operators/tensor_like.py
  towhee/types/tensor_array.py
Labels: lgtm, size/L, approved

#1369 Add utility gen_from_type_annotations
  serve/tests/__init__.py
  serve/tests/unittests/__init__.py
  serve/tests/unittests/triton/__init__.py
  serve/tests/unittests/triton/test_type_gen.py
  serve/triton/type_gen.py
Labels: lgtm, size/L, approved

#1371 support chunked execution in data frame
  towhee/engine/execution/vectorized_execution.py
  towhee/functional/data_collection.py
  towhee/functional/entity_view.py
  towhee/functional/mixins/column.py
  towhee/functional/mixins/display.py
  towhee/functional/storages.py
Labels: lgtm, size/L, approved

#1372 add tsm_rgb_s16
  towhee/models/tsm/config.py
  towhee/models/tsm/tsm.py
Labels: lgtm, approved, size/S, component/models

#1297 Add video encoder in computer vision mixin
  towhee/__init__.py
  towhee/functional/__init__.py
  towhee/functional/mixins/computer_vision.py
  towhee/utils/av_utils.py
Labels: lgtm, size/L, approved

#1374 add create_model of omnivore
  towhee/models/omnivore/omnivore.py
Labels: lgtm, approved, size/M, component/models

#1379 Add type handling functions
  serve/tests/unittests/triton/test_type_gen.py
  serve/triton/type_gen.py
Labels: lgtm, size/L, approved

#1377 support chunked execution in data frame
  towhee/functional/mixins/column.py
  towhee/functional/storages.py
Labels: lgtm, size/L, approved

#1383 modify weights name in video swin transformer
  towhee/models/video_swin_transformer/get_configs.py
Labels: lgtm, approved, size/S

#1384 Add type init functions in type_gen
  serve/tests/unittests/triton/test_type_gen.py
  serve/triton/type_gen.py
Labels: lgtm, size/L, approved

#1370 Add supported_model_names to NNOperator
  tests/unittests/operators/test_operator_base.py
  towhee/operator/base.py
Labels: lgtm, approved, size/S

#1394 add __init__.py
  towhee/models/allinone/__init__.py
  towhee/models/allinone/allinone.py
  towhee/models/violet/__init__.py
  towhee/models/violet/violet.py
Labels: lgtm, approved, size/M

#1396 include bpe_simple_vocab_16e6 file to package
  MANIFEST.in
  setup.py
Labels: lgtm, approved, size/XS

#1398 fix package problem
  MANIFEST.in
  setup.py
  towhee/models/allinone/__init__.py
  towhee/models/allinone/allinone.py
  towhee/models/violet/__init__.py
  towhee/models/violet/violet.py
Labels: lgtm, approved, size/M

#1397 Allow mimo with chunked execution
  towhee/engine/execution/base_execution.py
  towhee/engine/execution/pandas_execution.py
  towhee/engine/execution/vectorized_execution.py
  towhee/functional/mixins/column.py
Labels: lgtm, approved, size/M

#1399 Add codegen for Tensor-object inter convert
  serve/tests/unittests/triton/test_format_utils.py
  serve/tests/unittests/triton/test_python_model_builder.py
  serve/triton/format_utils.py
  serve/triton/python_model_builder.py
  serve/triton/type_gen.py
Labels: lgtm, approved, size/XL

#1400 chunked execution cleanup
  towhee/functional/mixins/column.py
  towhee/functional/storages.py
Labels: lgtm, approved, size/M

#1401 Add UT for mimo
  tests/unittests/functional/test_mixins.py
  towhee/engine/execution/vectorized_execution.py
  towhee/functional/mixins/column.py
Labels: lgtm, size/L, approved

#1404 Add gen_model_from_pickled_callable
  serve/tests/unittests/triton/expected_files/clip_preprocess_model_expect.py
  serve/tests/unittests/triton/test_python_model_builder.py
  serve/triton/format_utils.py
  serve/triton/python_model_builder.py
  serve/triton/type_gen.py
Labels: lgtm, size/L, approved

#1409 Upgrade codevoc-action
  .github/workflows/codecov.yml
  codecov.yml
Labels: lgtm, approved, size/XS

#1411 optimize DRL model to adapt op and clip module.
  towhee/models/drl/__init__.py
  towhee/models/drl/drl.py
Labels: lgtm, size/L, approved

#1412 Update benchmark
  towhee/benchmark/benchmark_report.ipynb
Labels: lgtm, approved, size/XS

#1414 Log error when download failed
  towhee/hub/repo_manager.py
Labels: lgtm, approved, size/XS

#1408 modify clip to adapt bridgeformer
  tests/unittests/models/bridgeformer/test_bridge_former.py
  towhee/models/bridgeformer/__init__.py
  towhee/models/bridgeformer/bridge_former.py
  towhee/models/bridgeformer/bridge_former_utils.py
  towhee/models/clip/clip.py
Labels: lgtm, size/L, approved

#1416 Clear cache when clone failed
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/XS

#1417 Fix issue when download/clone repo
  towhee/hub/repo_manager.py
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/S

#1423 Add OpPyModelBuilder
  serve/tests/unittests/triton/expected_files/clip_preprocess_model.py
  serve/tests/unittests/triton/expected_files/resnet50_model.py
  serve/tests/unittests/triton/test_python_model_builder.py
  serve/tests/unittests/triton/test_triton_config_builder.py
  serve/triton/python_model_builder.py
  serve/triton/triton_config_builder.py
Labels: lgtm, size/L, approved

#1424 Fix scalar shape
  serve/tests/unittests/triton/test_triton_config_builder.py
  serve/triton/python_model_builder.py
  serve/triton/type_gen.py
Labels: lgtm, approved, size/M

#1422 add bridgeformer training module to bridge former
  tests/unittests/models/bridgeformer/test_bridge_former.py
  towhee/models/bridgeformer/bridge_former.py
  towhee/models/bridgeformer/bridge_former_training.py
  towhee/models/bridgeformer/bridge_former_training_block.py
Labels: lgtm, approved, size/XL

#1426 embedding visualization
  tests/unittests/models/visualization/test_embedding_vis.py
  towhee/models/multiscale_vision_transformers/create_mvit.py
  towhee/models/visualization/embedding_visualization.py
Labels: lgtm, size/L, approved

#1373 Remove cv2_to_rgb in Image
  towhee/_types/image.py
  towhee/utils/plot_utils.py
Labels: lgtm, approved, size/S

#1421 Add dependency version check before executing operators
  towhee/engine/operator_loader.py
Labels: lgtm, approved, size/S

#1434 Fix dependency conflict issue
  towhee/engine/operator_loader.py
Labels: lgtm, approved, size/S

#1435 Fix dependency conflict issue
  towhee/engine/operator_loader.py
Labels: lgtm, approved, size/S

#1402 add create_model of movinet
  tests/unittests/models/movinet/test_movinet.py
  towhee/models/movinet/movinet.py
Labels: lgtm, size/L, approved, component/models

#1436 modify timesformer to adapt svt
  tests/unittests/models/timesformer/test_timesformer.py
  towhee/models/timesformer/timesformer.py
  towhee/models/timesformer/timesformer_utils.py
Labels: lgtm, approved, size/M

#1439 code cleanup for data collection
  tests/unittests/functional/test_entity_view.py
  towhee/functional/__init__.py
  towhee/functional/data_collection.py
  towhee/functional/entity.py
  towhee/functional/entity_view.py
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/column.py
  towhee/functional/mixins/computer_vision.py
  towhee/functional/mixins/dataset.py
  towhee/functional/mixins/dispatcher.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/milvus.py
  towhee/functional/mixins/save.py
  towhee/functional/storages.py
Labels: lgtm, size/L, approved

#1440 Add version check before install packages
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/S

#1441 Add version check before install packages (#1440)
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/S

#1443 add support for init args
  .gitignore
  tests/unittests/engine/test_op.py
  tests/unittests/functional/test_data_collection.py
  towhee/engine/factory.py
  towhee/engine/operator_loader.py
  towhee/engine/operator_pool.py
  towhee/functional/data_collection.py
Labels: lgtm, size/L, approved

#1444 collaborative experts
  tests/unittests/models/collaborative_experts/__init__.py
  tests/unittests/models/collaborative_experts/test_collaborative_experts.py
  towhee/models/collaborative_experts/__init__.py
  towhee/models/collaborative_experts/collaborative_experts.py
  towhee/models/collaborative_experts/net_vlad.py
  towhee/models/collaborative_experts/util.py
Labels: lgtm, approved, size/XXL

#1446 code cleanup
  tests/unittests/functional/test_data_collection.py
  towhee/__init__.py
  towhee/doc/source/towhee/towhee.rst
  towhee/functional/__init__.py
  towhee/functional/entity.py
  towhee/functional/mixins/computer_vision.py
  towhee/functional/mixins/dataset.py
  towhee/hub/builtin/operators/computer_vision.py
  towhee/hub/builtin/operators/feature_engineer.py
  towhee/hub/builtin/operators/milvus_search.py
  towhee/hub/builtin/operators/runas_op.py
  towhee/hub/builtin/operators/tensor_like.py
Labels: lgtm, size/L, approved

#1447 Add faiss mixin and faiss search
  test_requirements.txt
  tests/unittests/functional/test_mixins.py
  towhee/doc/source/data_collection/mixins.rst
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/faiss_mixin.py
  towhee/hub/builtin/operators/faiss_search.py
  towhee/hub/preclude/__init__.py
  towhee/utils/faiss_utils.py
Labels: lgtm, size/L, approved

#1405 Dag info
  tests/testcases/test_dag_info.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/dag.py
  towhee/functional/mixins/ray.py
  towhee/functional/mixins/serve.py
Labels: lgtm, size/L, approved

#1451 Prepare for triton
  towhee/engine/factory.py
  towhee/engine/operator_registry.py
Labels: lgtm, approved, size/S

#1455 Insatll required packages when downloading op
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/XS

#1459 Triton config
  .github/workflows/pylint.yml
  serve/__init__.py
  serve/tests/unittests/__init__.py
  serve/tests/unittests/triton/__init__.py
  serve/tests/unittests/triton/expected_files/clip_preprocess_model.py
  serve/tests/unittests/triton/expected_files/resnet50_model.py
  serve/tests/unittests/triton/test_python_model_builder.py
  serve/tests/unittests/triton/test_triton_config_builder.py
  serve/tests/unittests/triton/test_type_gen.py
  serve/triton/python_model_builder.py
  serve/triton/type_gen.py
  setup.cfg
Labels: lgtm, size/L, approved

#1457 Branch0.7
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/XS

#1460 add to config.pbtxt
  serve/tests/unittests/triton/expected_files/nnop/config.pbtxt
  serve/tests/unittests/triton/expected_files/postprocess/1/model.py
  serve/tests/unittests/triton/expected_files/postprocess/1/postprocess.pickle
  serve/tests/unittests/triton/expected_files/postprocess/config.pbtxt
  serve/tests/unittests/triton/expected_files/preprocess/1/model.py
  serve/tests/unittests/triton/expected_files/preprocess/config.pbtxt
  serve/tests/unittests/triton/expected_files/py_to_triton_test/1/model.py
  serve/tests/unittests/triton/expected_files/py_to_triton_test/config.pbtxt
  serve/tests/unittests/triton/expected_files/test_model.pbtxt
  serve/tests/unittests/triton/test_to_triton.py
  serve/tests/unittests/triton/test_triton_config_builder.py
  serve/triton/constant.py
  serve/triton/to_triton_models.py
  serve/triton/triton_config_builder.py
  tests/unittests/mock_operators/triton_nnop/__init__.py
  tests/unittests/mock_operators/triton_nnop/model.py
  tests/unittests/mock_operators/triton_nnop/postprocess.py
  tests/unittests/mock_operators/triton_nnop/preprocess.py
  tests/unittests/mock_operators/triton_nnop/triton_nnop.py
  tests/unittests/mock_operators/triton_py/__init__.py
  tests/unittests/mock_operators/triton_py/triton_py.py
Labels: lgtm, approved, size/XL

#1464 Rm 05-Tutorials
  docs/05-Tutorials/01-Fine Tune/Train operators/2_Fine_Tune_with_MNIST_files/2_Fine_Tune_with_MNIST_12_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_11_1.png
  docs/05-Tutorials/01-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_1.png
  docs/05-Tutorials/01-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_2.png
  docs/05-Tutorials/01-Fine Tune/Train operators/fine-tune-with-MNIST.md
  docs/05-Tutorials/01-Fine Tune/Train operators/quick-start.md
  docs/05-Tutorials/01-Fine Tune/Train operators/train-a-bird-classification-model.md
  docs/05-Tutorials/01-Fine Tune/Train operators/train-cub-200-2011.md
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_10_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_12_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_13_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_19_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_21_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_23_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_25_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_27_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_29_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_40_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/training-configs.md
  docs/05-Tutorials/02-Computer Vision/01-reverse-image-search.md
  docs/05-Tutorials/02-Computer Vision/02-image-deduplication.md
  docs/05-Tutorials/02-Computer Vision/image_dedup.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_metric1.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_metric2.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_metric3.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_results.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_showcase.gif
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_showcsv.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_workflow.png
  docs/05-Tutorials/03-Audio/01-music-recognition-system.md
  docs/05-Tutorials/03-Audio/music_embedding.png
  docs/05-Tutorials/03-Audio/music_recog_system.png
  tutorials/anime_style_transformer.ipynb
  tutorials/music_recognition_tutorial.ipynb
Labels: lgtm, approved, size/XXL

#1465 add create_ensemble
  serve/tests/unittests/triton/expected_files/test_create_ensemble.pbtxt
  serve/tests/unittests/triton/test_triton_config_builder.py
  serve/triton/triton_config_builder.py
Labels: lgtm, size/L, approved

#1466 lightning dot bi_encoder
  tests/unittests/models/lightning_dot/__init__.py
  tests/unittests/models/lightning_dot/test_lightning_dot.py
  towhee/models/lightning_dot/__init__.py
  towhee/models/lightning_dot/bi_encoder.py
Labels: lgtm, size/L, approved

#1468 Update version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#1469 Update towhee version for 0.7.0
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#1470 Unlink the tutorial
  docs/01-Overview.md
  docs/03-User Guides/03-Built-in Pipelines/audio-embedding.md
  docs/03-User Guides/03-Built-in Pipelines/image-embedding.md
  docs/05-Release Notes/release-notes-040.md
Labels: lgtm, approved, size/S

#1463 Add configmixin and compilemixin
  test_requirements.txt
  tests/unittests/functional/test_mixins.py
  towhee/doc/source/data_collection/mixins.rst
  towhee/engine/operator_registry.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/compile.py
  towhee/functional/mixins/config.py
  towhee/functional/mixins/faiss.py
  towhee/utils/numba.py
Labels: lgtm, size/L, approved

#1477 Fix error report with glob
  towhee/functional/mixins/dataset.py
Labels: lgtm, approved, size/XS

#1478 Add numba package in doc
  towhee/doc/requirements.txt
  towhee/functional/mixins/compile.py
  towhee/utils/numba_utils.py
Labels: lgtm, approved, size/S

#1480 fix doc build for readthedocs
  towhee/doc/requirements.txt
Labels: lgtm, approved, size/XS

#1482 mpvit
  tests/unittests/models/mpvit/__init__.py
  tests/unittests/models/mpvit/test_mpvit.py
  towhee/models/mpvit/__init__.py
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/XL

#1481 Bugfix/fix doc build
  towhee/doc/requirements.txt
Labels: lgtm, approved, size/XS

#1483 Add model changelog
  MODEL_CHANGELOG.md
Labels: lgtm, approved, size/M

#1484 clean up for parallel execution
  towhee/functional/mixins/parallel.py
Labels: lgtm, approved, size/M

#1487 repair _pad for newest pytorch version
  tests/unittests/models/layers/test_sam.py
  towhee/models/clip/auxilary.py
Labels: lgtm, approved, size/XS

#1479 fix triton ensemble
  serve/tests/unittests/triton/expected_files/ensemble/config.pbtxt
  serve/tests/unittests/triton/expected_files/nnop/config.pbtxt
  serve/tests/unittests/triton/expected_files/postprocess/config.pbtxt
  serve/tests/unittests/triton/expected_files/preprocess/config.pbtxt
  serve/tests/unittests/triton/expected_files/py_to_triton_test/config.pbtxt
  serve/tests/unittests/triton/expected_files/test_create_ensemble.pbtxt
  serve/tests/unittests/triton/test_builder.py
  serve/tests/unittests/triton/test_to_triton.py
  serve/tests/unittests/triton/test_triton_config_builder.py
  serve/triton/builder.py
  serve/triton/to_triton_models.py
  serve/triton/triton_config_builder.py
  tests/unittests/mock_operators/triton_nnop/model.py
Labels: lgtm, approved, size/XL

#1491 add as_function.__name__
  towhee/functional/mixins/serve.py
Labels: lgtm, approved, size/XS

#1493 Replace towhee.Image
  tests/unittests/functional/test_mixins.py
  tests/unittests/types/test_image.py
  tests/unittests/utils/test_ndarray_utils.py
  tests/unittests/utils/test_pil_utils.py
  towhee/types/__init__.py
  towhee/utils/ndarray_utils.py
  towhee/utils/pil_utils.py
  towhee/utils/plot_utils.py
Labels: lgtm, approved, size/S

#1490 Add stream chunk execution
  towhee/functional/data_collection.py
  towhee/functional/mixins/column.py
  towhee/functional/storages.py
Labels: lgtm, size/L, approved
