Repository towhee-io/towhee, pull requests merged in 2022-10, with the labels that each got.

#2115 Add runtime data_queue
  tests/unittests/runtime/__init__.py
  tests/unittests/runtime/test_data_queue.py
  towhee/runtime/data_queue.py
Labels: lgtm, size/L, approved

#2181 Update towhee version
  tests/testcases/requirements.text
Labels: lgtm, approved, size/XS

#2189 add linear activation and initializer for vis4mer
  tests/unittests/models/vis4mer/test_linearactivation.py
  towhee/models/vis4mer/get_initializer.py
  towhee/models/vis4mer/linearactivation.py
Labels: lgtm, size/L, approved

#2185 Runtime map node
  tests/unittests/mock_operators/multi_gen/__init__.py
  tests/unittests/mock_operators/multi_gen/gen.py
  tests/unittests/mock_operators/multi_output/__init__.py
  tests/unittests/mock_operators/multi_output/op.py
  tests/unittests/runtime/test_data_queue.py
  tests/unittests/runtime/test_map_node.py
  towhee/runtime/__init__.py
  towhee/runtime/data_queue.py
  towhee/runtime/nodes/__init__.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/nodes/node.py
  towhee/runtime/nodes/node_info.py
Labels: lgtm, approved, size/XL

#2192 Add fuse_bn for RepLKNet
  tests/unittests/models/replknet/__init__.py
  tests/unittests/models/replknet/test_utils.py
  towhee/models/layers/conv_bn_activation.py
  towhee/models/replknet/__init__.py
  towhee/models/replknet/utils.py
Labels: lgtm, size/L, approved, component/models

#2193 Add ConvFFN for RepLKNet
  tests/unittests/models/replknet/test_utils.py
  towhee/models/replknet/utils.py
Labels: lgtm, approved, size/M, component/models

#2191 Add NodeRepr
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_node_repr.py
  towhee/runtime/node_repr.py
  towhee/runtime/nodes/__init__.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/nodes/node.py
  towhee/runtime/nodes/node_info.py
Labels: lgtm, approved, size/XL

#2190 add package && upload command
  requirements.txt
  test_requirements.txt
  towhee/command/cmdline.py
  towhee/command/execute.py
Labels: lgtm, approved, size/M

#2194 Add ReparamLargeKernelConv for RepLKNet
  tests/unittests/models/replknet/test_utils.py
  towhee/models/replknet/utils.py
Labels: lgtm, size/L, approved, component/models

#2196 Add RepLKBlock
  tests/unittests/models/replknet/test_utils.py
  towhee/models/replknet/utils.py
Labels: lgtm, approved, size/M, component/models

#2198 Add RepLKNetStage
  tests/unittests/models/replknet/test_utils.py
  towhee/models/replknet/utils.py
Labels: lgtm, approved, size/M, component/models

#2200 Add RepLKNet model
  tests/unittests/models/replknet/test_model.py
  towhee/models/replknet/__init__.py
  towhee/models/replknet/configs.py
  towhee/models/replknet/replknet.py
Labels: lgtm, size/L, approved, component/models

#2201 Add model configs for towhee.models.replknet
  tests/unittests/models/replknet/test_model.py
  towhee/models/replknet/configs.py
  towhee/models/replknet/replknet.py
  towhee/models/replknet/utils.py
Labels: lgtm, size/L, approved, component/models

#2199 Support Window Node
  tests/unittests/mock_operators/add/__init__.py
  tests/unittests/mock_operators/add/add_operator.py
  tests/unittests/mock_operators/sum2/__init__.py
  tests/unittests/mock_operators/sum2/sum_operator.py
  tests/unittests/runtime/test_data_queue.py
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_window_node.py
  towhee/runtime/data_queue.py
  towhee/runtime/nodes/__init__.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/nodes/_window.py
Labels: lgtm, approved, size/XL

#2197 Create filter node
  tests/unittests/mock_operators/filter_operator/__init__.py
  tests/unittests/mock_operators/filter_operator/filter_operator.py
  tests/unittests/runtime/test_filter_node.py
  tests/unittests/runtime/test_map_node.py
  towhee/runtime/data_queue.py
  towhee/runtime/nodes/__init__.py
  towhee/runtime/nodes/_filter.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/nodes/node.py
Labels: lgtm, size/L, approved

#2195 Add runtime DagRepr and SchemaRepr
  tests/unittests/runtime/test_dag_repr.py
  tests/unittests/runtime/test_filter_node.py
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_node_repr.py
  tests/unittests/runtime/test_schema_repr.py
  tests/unittests/runtime/test_window_node.py
  tests/unittests/utils/test_check_util.py
  towhee/runtime/dag_repr.py
  towhee/runtime/node_repr.py
  towhee/runtime/schema_repr.py
  towhee/utils/check_utils.py
Labels: lgtm, approved, size/XL

#2205 add kernel functions for vis4mer, add ut for krylov
  tests/unittests/models/vis4mer/test_krylov.py
  towhee/models/vis4mer/__init__.py
  towhee/models/vis4mer/utils.py
Labels: lgtm, size/L, approved

#2207 add ut for transifion for vis4mer
  tests/unittests/models/vis4mer/test_transition.py
Labels: lgtm, approved, size/S

#2208 add ut for rank correction
  tests/unittests/models/vis4mer/test_rank_correction.py
Labels: lgtm, approved, size/S

#2210 add ut for nplr for vis4mer
  tests/unittests/models/vis4mer/test_nplr.py
Labels: lgtm, approved, size/S

#2203 Time window
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_time_window_node.py
  towhee/runtime/nodes/__init__.py
  towhee/runtime/nodes/_time_window.py
  towhee/runtime/nodes/_window.py
Labels: lgtm, size/L, approved

#2213 Fix broken quick start URL
  docs/02-Getting Started/01-quick-start.mdx
Labels: lgtm, approved, size/XS

#2212 Add window_all and concat
  tests/unittests/runtime/test_concat.py
  tests/unittests/runtime/test_window_all.py
  towhee/runtime/nodes/__init__.py
  towhee/runtime/nodes/_concat.py
  towhee/runtime/nodes/_window_all.py
  towhee/runtime/nodes/node.py
Labels: lgtm, approved, size/XL

#2218 Support lambda
  tests/unittests/runtime/test_filter_node.py
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_time_window_node.py
  tests/unittests/runtime/test_window_all.py
  tests/unittests/runtime/test_window_node.py
  towhee/runtime/nodes/node.py
Labels: lgtm, approved, size/M

#2209 Support flat_map node
  tests/unittests/mock_operators/add2/__init__.py
  tests/unittests/mock_operators/add2/add_operator.py
  tests/unittests/mock_operators/flat_gen/__init__.py
  tests/unittests/mock_operators/flat_gen/flat_gen.py
  tests/unittests/mock_operators/multi_flat_map/__init__.py
  tests/unittests/mock_operators/multi_flat_map/multi_flat_map.py
  tests/unittests/mock_operators/sum3/__init__.py
  tests/unittests/mock_operators/sum3/sum_operator.py
  tests/unittests/runtime/test_flat_map_node.py
  towhee/runtime/nodes/__init__.py
  towhee/runtime/nodes/_flat_map.py
Labels: lgtm, approved, size/XL

#2219 Add docstring for nodes
  towhee/runtime/nodes/_filter.py
  towhee/runtime/nodes/_flat_map.py
Labels: lgtm, approved, size/S

#2206 Add RuntimePipeline
  tests/unittests/runtime/test_dag_repr.py
  tests/unittests/runtime/test_filter_node.py
  tests/unittests/runtime/test_flat_map_node.py
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_operator_pool.py
  tests/unittests/runtime/test_runtime_pipeline.py
  tests/unittests/runtime/test_time_window_node.py
  tests/unittests/runtime/test_window_all.py
  tests/unittests/runtime/test_window_node.py
  towhee/operator/nop.py
  towhee/runtime/dag_repr.py
  towhee/runtime/node_repr.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/nodes/node.py
  towhee/runtime/operator_manager/__init__.py
  towhee/runtime/operator_manager/operator_loader.py
  towhee/runtime/operator_manager/operator_pool.py
  towhee/runtime/operator_manager/operator_registry.py
  towhee/runtime/operator_manager/uri.py
  towhee/runtime/runtime_pipeline.py
Labels: lgtm, approved, size/XL

#2221 Allow get item in Entity
  towhee/datacollection/entity.py
Labels: lgtm, approved, size/S

#2224 make ut image when push to main
  .github/workflows/publish_ut_image.yml
Labels: lgtm, approved, size/XS

#2223 Runtime test
  tests/unittests/runtime/test_check_util.py
  tests/unittests/runtime/test_dag_repr.py
  tests/unittests/runtime/test_data_queue.py
  tests/unittests/runtime/test_filter_node.py
  tests/unittests/runtime/test_nodes.py
  tests/unittests/runtime/test_runtime_pipeline.py
  towhee/operator/nop.py
  towhee/runtime/check_utils.py
  towhee/runtime/constants.py
  towhee/runtime/dag_repr.py
  towhee/runtime/data_queue.py
  towhee/runtime/node_repr.py
  towhee/runtime/nodes/__init__.py
  towhee/runtime/nodes/_filter.py
  towhee/runtime/nodes/_time_window.py
  towhee/runtime/nodes/_window.py
Labels: lgtm, size/L, approved

#2229 clean weekly ci cache
  .github/workflows/publish_ut_image.yml
  .github/workflows/weekly_ci.yml
  .github/workflows/weekly_gpu_ci.yml
Labels: lgtm, approved, size/S

#2222 Modify tests after code change
  tests/testcases/hub/execute_hub_operators.py
  tests/testcases/requirements.text
Labels: lgtm, approved, size/S

#2225 Add ops
  tests/unittests/runtime/test_factory.py
  towhee/runtime/factory.py
Labels: lgtm, size/L, approved

#2228 Support concat in runtimepipeline
  tests/unittests/runtime/test_dag_repr.py
  tests/unittests/runtime/test_runtime_pipeline.py
  towhee/runtime/dag_repr.py
  towhee/runtime/node_repr.py
  towhee/runtime/schema_repr.py
Labels: lgtm, approved, size/M

#2227 DataQueue return Empty
  tests/unittests/runtime/test_data_queue.py
  tests/unittests/runtime/test_filter_node.py
  tests/unittests/runtime/test_flat_map_node.py
  tests/unittests/runtime/test_time_window_node.py
  tests/unittests/runtime/test_window_all.py
  tests/unittests/runtime/test_window_node.py
  towhee/runtime/data_queue.py
  towhee/runtime/nodes/_window.py
  towhee/runtime/nodes/_window_all.py
Labels: lgtm, size/L, approved

#2230 add git-lfs to weekly_ci
  .github/workflows/weekly_ci.yml
  .github/workflows/weekly_gpu_ci.yml
  tests/testcases/hub/execute_hub_operators.py
Labels: lgtm, approved, size/XS

#2226 Test pipeline with window nodes
  tests/unittests/runtime/test_pipeline.py
  towhee/runtime/check_utils.py
  towhee/runtime/nodes/_window_all.py
Labels: lgtm, size/L, approved

#2233 Replace engine op pool with runtime op pool
  tests/unittests/runtime/test_concat.py
Labels: lgtm, approved, size/XS

#2237 fix pytorch and numpy import error
  .github/workflows/weekly_ci.yml
  .github/workflows/weekly_gpu_ci.yml
Labels: lgtm, approved, size/XS

#2232 Add pipeline test
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_nodes.py
  tests/unittests/runtime/test_operator_pool.py
  tests/unittests/runtime/test_runtime_pipeline.py
  towhee/runtime/data_queue.py
  towhee/runtime/nodes/_concat.py
  towhee/runtime/operator_manager/operator_loader.py
  towhee/runtime/operator_manager/operator_pool.py
  towhee/runtime/operator_manager/operator_registry.py
Labels: lgtm, size/L, approved

#2239 Polish operator pool
  tests/unittests/runtime/test_concat.py
  tests/unittests/runtime/test_filter_node.py
  tests/unittests/runtime/test_flat_map_node.py
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_operator_pool.py
  tests/unittests/runtime/test_window_all.py
  tests/unittests/runtime/test_window_node.py
  towhee/runtime/nodes/node.py
  towhee/runtime/operator_manager/operator_pool.py
  towhee/runtime/runtime_pipeline.py
Labels: lgtm, size/L, approved

#2240 Update iter info to constant
  towhee/runtime/pipeline.py
Labels: lgtm, approved, size/M

#2242 fix git checkout lfs error
  .github/workflows/codecov.yml
  .github/workflows/weekly_ci.yml
  .github/workflows/weekly_gpu_ci.yml
Labels: lgtm, approved, size/S

#2245 remove codecov gitlfs
  .github/workflows/codecov.yml
  towhee/hub/builtin/operators/computer_vision.py
Labels: lgtm, approved, size/S
