Repository towhee-io/towhee, pull requests merged in 2022-07, with the labels that each got.

#1497 Fix search parameter issue
  towhee/functional/mixins/faiss.py
  towhee/hub/builtin/operators/faiss_search.py
Labels: lgtm, approved, size/XS

#1495 add some docstring
  towhee/models/clip/clip.py
  towhee/models/clip4clip/clip4clip.py
  towhee/models/collaborative_experts/collaborative_experts.py
  towhee/models/drl/drl.py
  towhee/models/mpvit/mpvit.py
Labels: lgtm, size/L, approved

#1498 Fix search parameter issue
  towhee/functional/mixins/faiss.py
  towhee/hub/builtin/operators/faiss_search.py
Labels: lgtm, approved, size/XS

#1496 Replace towhee.types.image with towhee._types.image
  tests/unittests/types/test_image.py
  tests/unittests/types/test_mage_utils.py
  tests/unittests/utils/test_ndarray_utils.py
  tests/unittests/utils/test_pil_utils.py
  towhee/_types/image.py
  towhee/hub/builtin/operators/computer_vision.py
  towhee/types/arg.py
  towhee/types/image.py
  towhee/utils/image_utils.py
  towhee/utils/ndarray_utils.py
  towhee/utils/pil_utils.py
  towhee/utils/plot_utils.py
Labels: lgtm, size/L, approved

#1502 Refactor repr and str for Entity
  towhee/functional/entity.py
  towhee/functional/mixins/dataframe.py
Labels: lgtm, approved, size/S

#1503 update version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#1504 Update towhee version for 0.7.1
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#1501 Add examples to README
  README.md
Labels: lgtm, approved, size/XS

#1509 add coformer
  tests/unittests/models/coformer/__init__.py
  tests/unittests/models/coformer/test_coformer.py
  towhee/models/coformer/__init__.py
  towhee/models/coformer/backbone.py
  towhee/models/coformer/coformer.py
  towhee/models/coformer/config.py
  towhee/models/coformer/transformer.py
  towhee/models/coformer/utils.py
  towhee/models/layers/position_encoding.py
Labels: lgtm, approved, size/XXL

#1507 add svt finetune model
  tests/unittests/models/svt/__init__.py
  tests/unittests/models/svt/test_svt.py
  tests/unittests/models/timesformer/test_timesformer.py
  towhee/models/svt/__init__.py
  towhee/models/svt/svt.py
  towhee/models/timesformer/timesformer.py
  towhee/models/timesformer/timesformer_utils.py
Labels: lgtm, size/L, approved

#1485 add benchmark script for ray backend
  towhee/benchmark/benchmark_ray_backend.py
  towhee/functional/mixins/ray.py
Labels: lgtm, size/L, approved

#1513 add cvnet model
  tests/unittests/models/cvnet/__init__.py
  tests/unittests/models/cvnet/test_cvnet.py
  towhee/models/cvnet/__init__.py
  towhee/models/cvnet/cvnet.py
  towhee/models/cvnet/cvnet_block.py
  towhee/models/cvnet/cvnet_utils.py
  towhee/models/cvnet/resnet.py
  towhee/models/layers/conv4d.py
Labels: lgtm, approved, size/XL

#1512 fix dag_info
  tests/testcases/test_dag_info.py
  towhee/functional/mixins/dag.py
Labels: lgtm, approved, size/S

#1525 Move image_utils to types
  tests/unittests/types/test_mage_utils.py
  towhee/hub/builtin/operators/computer_vision.py
  towhee/types/arg.py
  towhee/types/image_utils.py
  towhee/utils/plot_utils.py
Labels: lgtm, approved, size/XS

#1527 Update towhee version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#1526 Builder
  .github/workflows/pylint.yml
  serve/tests/__init__.py
  serve/tests/unittests/__init__.py
  setup.cfg
  setup.py
  tests/unittests/triton/__init__.py
  tests/unittests/triton/expected_files/clip_preprocess_model.py
  tests/unittests/triton/expected_files/ensemble/config.pbtxt
  tests/unittests/triton/expected_files/nnop/config.pbtxt
  tests/unittests/triton/expected_files/postprocess/1/model.py
  tests/unittests/triton/expected_files/postprocess/1/postprocess.pickle
  tests/unittests/triton/expected_files/postprocess/config.pbtxt
  tests/unittests/triton/expected_files/preprocess/1/model.py
  tests/unittests/triton/expected_files/preprocess/config.pbtxt
  tests/unittests/triton/expected_files/py_to_triton_test/1/model.py
  tests/unittests/triton/expected_files/py_to_triton_test/config.pbtxt
  tests/unittests/triton/expected_files/resnet50_model.py
  tests/unittests/triton/expected_files/test_create_ensemble.pbtxt
  tests/unittests/triton/expected_files/test_model.pbtxt
  tests/unittests/triton/test_builder.py
  tests/unittests/triton/test_format_utils.py
  tests/unittests/triton/test_python_model_builder.py
  tests/unittests/triton/test_to_triton.py
  tests/unittests/triton/test_triton_config_builder.py
  tests/unittests/triton/test_type_gen.py
  towhee/__init__.py
  towhee/serve/__init__.py
  towhee/serve/triton/__init__.py
  towhee/serve/triton/builder.py
  towhee/serve/triton/constant.py
  towhee/serve/triton/docker_image_builder.py
  towhee/serve/triton/dockerfiles/DockerfileCuda113
  towhee/serve/triton/dockerfiles/DockerfileCuda114
  towhee/serve/triton/dockerfiles/DockerfileCuda116
  towhee/serve/triton/dockerfiles/__init__.py
  towhee/serve/triton/format_utils.py
  towhee/serve/triton/python_model_builder.py
  towhee/serve/triton/to_triton_models.py
  towhee/serve/triton/triton_config_builder.py
  towhee/serve/triton/type_gen.py
Labels: lgtm, size/L, approved

#1530 Add model transrac: prepare utils
  tests/unittests/models/transrac/__init__.py
  tests/unittests/models/transrac/test_utils.py
  towhee/models/transrac/__init__.py
  towhee/models/transrac/utils.py
Labels: lgtm, size/L, approved, component/models

#1519 add swiglu
  tests/unittests/models/layers/test_swiglu.py
  towhee/models/layers/activations/swiglu.py
  towhee/models/omnivore/omnivore.py
Labels: lgtm, approved, size/M

#1534 add 0.7.1 change log
  MODEL_CHANGELOG.md
Labels: lgtm, approved, size/S

#1532 add coca model
  tests/unittests/models/coca/__init__.py
  tests/unittests/models/coca/test_coca.py
  towhee/models/coca/__init__.py
  towhee/models/coca/coca.py
Labels: lgtm, approved, size/XL, component/models

#1537 Add transrac model
  tests/unittests/models/transrac/test_transrac.py
  towhee/models/transrac/__init__.py
  towhee/models/transrac/transrac.py
Labels: lgtm, size/L, approved, component/models

#1529 Ajust text show format
  towhee/functional/mixins/display.py
Labels: lgtm, approved, size/S

#1533 modify swin transformer to adapt swin transformer v2
  tests/unittests/models/swin_transformer/test_swin_transformer.py
  tests/unittests/models/swin_transformer/test_utils.py
  towhee/models/layers/patch_merging.py
  towhee/models/layers/swin_transformer_block3d.py
  towhee/models/layers/window_attention.py
  towhee/models/swin_transformer/basic_layer.py
  towhee/models/swin_transformer/configs.py
  towhee/models/swin_transformer/model.py
  towhee/models/swin_transformer/swin_transformer_block.py
  towhee/models/swin_transformer/utils.py
  towhee/models/swin_transformer/window_attention.py
  towhee/models/utils/window_partition.py
  towhee/models/utils/window_partition3d.py
  towhee/models/utils/window_reverse.py
  towhee/models/utils/window_reverse3d.py
  towhee/models/video_swin_transformer/compute_mask.py
Labels: lgtm, approved, size/XL

#1535 add cross_attention
  tests/unittests/models/layers/test_cross_attention.py
  towhee/models/coca/coca.py
  towhee/models/layers/cross_attention.py
Labels: lgtm, size/L, approved, component/layers

#1539 Update towhee version
  .github/workflows/pr_test.yml
  tests/testcases/requirements.text
  tests/testcases/test_main.py
Labels: lgtm, approved, size/XS

#1542 add triton_client
  test_requirements.txt
  tests/unittests/triton/test_client.py
  towhee/serve/triton/client.py
Labels: lgtm, size/L, approved

#1540 add maxvit model utils
  tests/unittests/models/layers/test_mbconv.py
  tests/unittests/models/layers/test_relative_self_attention.py
  tests/unittests/models/max_vit/__init__.py
  tests/unittests/models/max_vit/test_max_vit_utils.py
  towhee/models/layers/mbconv.py
  towhee/models/layers/relative_self_attention.py
  towhee/models/max_vit/max_vit_utils.py
Labels: lgtm, size/L, approved, component/models

#1548 Update new pipeline
  .github/workflows/nightly_ci.yml
  .github/workflows/weekly_ci.yml
Labels: lgtm, approved, size/M

#1551 Clean up cache structure
  towhee/__init__.py
  towhee/engine/factory.py
  towhee/hub/file_manager.py
Labels: lgtm, approved, size/M

#1553 New readme
  README.md
  towhee_example.png
Labels: lgtm, size/L, approved

#1563 Skip module request info
  .github/workflows/nightly_ci.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/weekly_ci.yml
Labels: lgtm, approved, size/XS

#1565 modify max_vit model to be trainable
  towhee/models/max_vit/max_vit.py
Labels: lgtm, approved, component/models

#1566 Clean up DC class
  tests/unittests/functional/test_mixins.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/data_processing.py
  towhee/functional/mixins/list.py
  towhee/functional/mixins/safe.py
  towhee/functional/mixins/stream.py
Labels: lgtm, approved, size/XXL

#1571 modify max_vit create_model function to customize the training parameters
  towhee/models/max_vit/max_vit.py
Labels: lgtm, approved, size/XS, component/models

#1578 Add op_config
  towhee/engine/factory.py
Labels: lgtm, approved, size/XS

#1577 Support multilingual for clip-vit-b32
  tests/unittests/models/clip/test_clip.py
  towhee/models/clip/clip.py
  towhee/models/clip/clip_utils.py
  towhee/models/clip4clip/clip4clip.py
Labels: lgtm, size/L, approved, component/models

#1576 Fix issue 1572
  towhee/functional/mixins/remote.py
Labels: lgtm, approved, size/XS

#1580 add namespace package
  setup.py
  towhee/__init__.py
Labels: lgtm, approved, size/XS

#1582 Add README for towhee.models.clip
  towhee/models/clip/README.md
Labels: lgtm, approved, size/M, component/models

#1594 add op_config to dag
  tests/testcases/test_dag_info.py
  towhee/engine/factory.py
  towhee/functional/mixins/dag.py
Labels: lgtm, approved, size/M

#1603 Add cache related manipulation to towhee
  tests/unittests/hub/test_file_manager.py
  towhee/__init__.py
  towhee/hub/file_manager.py
Labels: lgtm, approved, size/M

#1586 Update ut machine
  .github/workflows/codecov.yml
Labels: lgtm, approved, size/XS

#1612 Add pipeline config and format_priority
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/config.py
  towhee/functional/mixins/format_priority.py
Labels: lgtm, size/L, approved

#1613 fix dependency problem of pyarrow
  towhee/functional/mixins/column.py
  towhee/functional/storages.py
Labels: lgtm, approved, size/S

#1614 fix dependency problem of pyarrow
  towhee/functional/mixins/column.py
  towhee/functional/storages.py
Labels: lgtm, approved, size/S

#1616 Update test machine
  .github/workflows/nightly_ci.yml
  .github/workflows/weekly_ci.yml
Labels: lgtm, approved, size/XS

#1617 repair CE module ckpt loading problem
  towhee/models/collaborative_experts/collaborative_experts.py
Labels: lgtm, approved, size/XS

#1618 repair CE module ckpt loading problem
  towhee/models/collaborative_experts/collaborative_experts.py
Labels: lgtm, approved, size/XS

#1621 fix no protobuf
  .github/workflows/codecov.yml
  test_requirements.txt
Labels: lgtm, approved, size/S

#1624 Update towhee CI
  tests/testcases/requirements.text
Labels: lgtm, approved, size/XS

#1611 Documentation Updates for DataCollection
  towhee/functional/data_collection.py
  towhee/functional/mixins/parallel.py
Labels: lgtm, approved, size/XL

#1627 Add melspec
  .github/workflows/codecov.yml
  tests/unittests/functional/test_data_collection.py
  tests/unittests/models/utils/test_melspec.py
  towhee/models/utils/melspec.py
Labels: lgtm, size/L, approved, component/models

#1628 add input and output to dag info
  tests/testcases/test_dag_info.py
  towhee/functional/mixins/dag.py
Labels: lgtm, size/L, approved

#1629 Update README towhee install
  README.md
Labels: lgtm, approved, size/XS

#1631 Add audio preprocess
  tests/unittests/models/utils/test_audio_preprocess.py
  tests/unittests/models/utils/test_melspec.py
  towhee/models/utils/audio_preprocess.py
Labels: lgtm, size/L, approved, component/models

#1632 Add separable conv2d
  tests/unittests/models/layers/test_conv2d_separable.py
  towhee/models/layers/conv2d_separable.py
Labels: lgtm, size/L, approved, component/models

#1635 add pygit2 and pgzip
  requirements.txt
Labels: lgtm, approved, size/XS

#1634 Add neural network fingerprint
  tests/unittests/models/nnfp/__init__.py
  tests/unittests/models/nnfp/test_nnfp.py
  towhee/models/nnfp/__init__.py
  towhee/models/nnfp/nnfp.py
Labels: lgtm, size/L, approved, component/models

#1636 add pgzip and pygit2
  requirements.txt
Labels: lgtm, approved, size/XS

#1633 Support op_config
  tests/unittests/triton/expected_files/nnop/config.pbtxt
  tests/unittests/triton/expected_files/postprocess/config.pbtxt
  tests/unittests/triton/expected_files/preprocess/config.pbtxt
  tests/unittests/triton/expected_files/py_to_triton_test/config.pbtxt
  tests/unittests/triton/expected_files/test_model.pbtxt
  tests/unittests/triton/test_builder.py
  tests/unittests/triton/test_to_triton.py
  towhee/serve/triton/builder.py
  towhee/serve/triton/constant.py
  towhee/serve/triton/to_triton_models.py
  towhee/serve/triton/triton_config_builder.py
Labels: lgtm, size/L, approved

#1637 Update towhee version for 0.7.3
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#1638 Update towhee version for 0.7.3
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#1640 Update codecov.yml
  .github/workflows/codecov.yml
Labels: lgtm, approved, size/XS

#1643 Add pipeline config to op config
  tests/testcases/test_dag_info.py
  towhee/functional/mixins/config.py
  towhee/functional/mixins/dag.py
Labels: lgtm, approved, size/M

#1642 chore: optimized installation description
  README.md
Labels: lgtm, approved, size/XS

#1647 add towhee compiler support
  towhee/functional/mixins/compile.py
Labels: lgtm, approved, size/M
