Repository towhee-io/towhee, pull requests merged in 2022-05, with the labels that each got.

#1173 Remove headers from tutorials
  docs/02-Getting Started/01-quick-start.mdx
  docs/02-Getting Started/02-install.md
  docs/02-Getting Started/03-data-collection.md
  docs/02-Getting Started/04-troubleshooting.md
  docs/02-Getting Started/05-gsoc-2022.md
  docs/02-Getting Started/data-collection.md
  docs/02-Getting Started/gsoc-2022.md
  docs/02-Getting Started/install.md
  docs/02-Getting Started/pipeline-config.md
  docs/02-Getting Started/quick-start.mdx
  docs/02-Getting Started/towhee.jpeg
  docs/02-Getting Started/troubleshooting.md
  docs/03-Tutorials/01-reverse-image-search.md
  docs/03-Tutorials/02-music-recognition-system.md
  docs/03-Tutorials/03-image-deduplication.md
  docs/04-Supported Pipelines/audio-embedding.md
  docs/04-Supported Pipelines/image-embedding.md
  docs/05-User Guides/Data collection/data-collection-with-ray.md
  docs/06-Developer Guides/cmdline.md
  docs/06-Developer Guides/contributing/adding-new-doc.md
  docs/06-Developer Guides/contributing/contributing-guide.md
  docs/06-Developer Guides/framework/DAG-details.md
  docs/06-Developer Guides/framework/architecture-overview.md
  docs/06-Developer Guides/framework/dag.png
  docs/06-Developer Guides/framework/dataframe-details.md
  docs/06-Developer Guides/framework/engine-details.md
  docs/06-Developer Guides/framework/framework.png
  docs/06-Developer Guides/framework/hub-integration-and-caching.md
  docs/06-Developer Guides/framework/image-ensemble-training.md
  docs/06-Developer Guides/framework/pipeline-overview.md
  docs/06-Developer Guides/framework/roadmap.md
  docs/06-Developer Guides/models/layers-overview.md
  docs/06-Developer Guides/models/swin_arch.png
  docs/07-Fine Tune/Train operators/2_Fine_Tune_with_MNIST_files/2_Fine_Tune_with_MNIST_12_0.png
  docs/07-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_11_1.png
  docs/07-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_0.png
  docs/07-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_1.png
  docs/07-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_2.png
  docs/07-Fine Tune/Train operators/fine-tune-with-MNIST.md
  docs/07-Fine Tune/Train operators/quick-start.md
  docs/07-Fine Tune/Train operators/train-a-bird-classification-model.md
  docs/07-Fine Tune/Train operators/train-cub-200-2011.md
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_10_0.png
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_12_0.png
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_13_0.png
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_19_0.png
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_21_0.png
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_23_0.png
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_25_0.png
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_27_0.png
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_29_0.png
  docs/07-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_40_0.png
  docs/07-Fine Tune/Train operators/training-configs.md
Labels: lgtm, approved, size/XXL

#1171 Removing conditional returns and non factory calls
  towhee/functional/data_collection.py
  towhee/functional/mixins/dataset.py
  towhee/functional/mixins/serve.py
Labels: lgtm, size/L, approved

#1176 Fix more broken links
  docs/01-Overview.md
  docs/04-Supported Pipelines/audio-embedding.md
  docs/04-Supported Pipelines/image-embedding.md
  docs/06-Developer Guides/framework/architecture-overview.md
  docs/06-Developer Guides/framework/pipeline-overview.md
Labels: lgtm, approved, size/S

#1164 ten minutes to data collection
  towhee/doc/source/user_guide/10-minutes-to-data-collection.md
Labels: lgtm, size/L, approved

#1179 tsm_test
  tests/unittests/models/layers/test_non_local.py
  tests/unittests/models/tsm/test_tsm.py
  towhee/models/tsm/bn_inception.py
  towhee/models/tsm/temporal_shift.py
  towhee/models/tsm/tsm.py
Labels: lgtm, approved, size/XL, component/layers, component/models

#1180 Support search list in milvus
  towhee/connectors/ann_index/milvus.py
Labels: lgtm, approved, size/XS

#1181 Add text tokenizer in clip and text_prompt in clip_action
  tests/unittests/models/action_clip/test_action_clip.py
  tests/unittests/models/clip/test_clip.py
  towhee/models/action_clip/__init__.py
  towhee/models/action_clip/text_prompt.py
  towhee/models/clip/__init__.py
  towhee/models/clip/bpe_simple_vocab_16e6.txt.gz
  towhee/models/clip/clip_utils.py
  towhee/models/clip/model.py
  towhee/models/clip/simple_tokenizer.py
Labels: lgtm, size/L, approved, component/models

#1187 add lrp for basic layers and mlp
  tests/unittests/models/layers/test_mlp.py
  towhee/models/layers/layers_with_relprop.py
  towhee/models/layers/mlp.py
Labels: lgtm, size/L, approved

#1191 add lrp for patch embed 2d layer
  tests/unittests/models/layers/test_patch_embed2d.py
  towhee/models/layers/patch_embed2d.py
Labels: lgtm, approved, size/S

#1192 Add API to load pretrained clip models (no jit)
  tests/unittests/models/clip/test_clip.py
  towhee/models/clip/__init__.py
  towhee/models/clip/clip.py
  towhee/models/clip/clip_utils.py
Labels: lgtm, size/L, approved, component/models

#1198 Allow clip to load with jit
  tests/unittests/models/clip/test_pretrained.py
  towhee/models/clip/clip.py
  towhee/models/clip/clip_utils.py
Labels: lgtm, size/L, approved, component/models

#1203 Optimize ut of towhee.models to reduce memory usage
  tests/unittests/models/action_clip/test_action_clip.py
  tests/unittests/models/clip/test_clip.py
  tests/unittests/models/layers/test_droppath.py
  tests/unittests/models/layers/test_mlp.py
  tests/unittests/models/layers/test_non_local.py
  tests/unittests/models/layers/test_padding_functions.py
  tests/unittests/models/layers/test_patch_embed2d.py
  tests/unittests/models/layers/test_patch_embed3d.py
  tests/unittests/models/layers/test_time2vec.py
  tests/unittests/models/timesformer/test_timesformer.py
  tests/unittests/models/vggish/test_vggish.py
  tests/unittests/models/vit/test_vit.py
  towhee/models/timesformer/timesformer.py
Labels: lgtm, size/L, approved

#1205 Add 10 min to towhee cmd docs
  docs/05-User Guides/10 minutes to Towhee CMD.md
Labels: lgtm, size/L, approved

#1207 clip4clip model
  tests/unittests/models/clip4clip/__init__.py
  tests/unittests/models/clip4clip/test_clip4clip.py
  towhee/models/clip4clip/__init__.py
  towhee/models/clip4clip/clip4clip.py
  towhee/models/clip4clip/until_module.py
Labels: lgtm, size/L, approved

#1206 Change CI test machine
  .github/workflows/pr_test.yml
  tests/testcases/test_main.py
Labels: lgtm, approved, size/XS

#1208 remove useless functions
  towhee/models/clip4clip/until_module.py
Labels: lgtm, approved, size/S

#1209 Specify long_description_content_type to solve wheel error
  setup.py
Labels: lgtm, approved, size/XS

#1204 Large-scale docs refactor
  docs/01-Overview.md
  docs/02-Getting Started/03-troubleshooting.md
  docs/03-User Guides/01-DataCollection/01-data-collection.md
  docs/03-User Guides/01-DataCollection/02-data-collection-with-ray.md
  docs/03-User Guides/02-command-line-tool.md
  docs/03-User Guides/03-Built-in Pipelines/audio-embedding.md
  docs/03-User Guides/03-Built-in Pipelines/image-embedding.md
  docs/04-Developer Guides/01-contributing-guide.md
  docs/04-Developer Guides/02-adding-new-doc.md
  docs/04-Developer Guides/Google Summer of Code/gsoc-2022.md
  docs/04-Developer Guides/Model Building Blocks/layers-overview.md
  docs/04-Developer Guides/Model Building Blocks/swin_arch.png
  docs/05-Tutorials/01-Fine Tune/Train operators/2_Fine_Tune_with_MNIST_files/2_Fine_Tune_with_MNIST_12_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_11_1.png
  docs/05-Tutorials/01-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_1.png
  docs/05-Tutorials/01-Fine Tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_2.png
  docs/05-Tutorials/01-Fine Tune/Train operators/fine-tune-with-MNIST.md
  docs/05-Tutorials/01-Fine Tune/Train operators/quick-start.md
  docs/05-Tutorials/01-Fine Tune/Train operators/train-a-bird-classification-model.md
  docs/05-Tutorials/01-Fine Tune/Train operators/train-cub-200-2011.md
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_10_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_12_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_13_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_19_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_21_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_23_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_25_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_27_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_29_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_40_0.png
  docs/05-Tutorials/01-Fine Tune/Train operators/training-configs.md
  docs/05-Tutorials/02-Computer Vision/01-reverse-image-search.md
  docs/05-Tutorials/02-Computer Vision/02-image-deduplication.md
  docs/05-Tutorials/02-Computer Vision/image_dedup.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_results1.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_results2.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_step1.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_step2.png
  docs/05-Tutorials/03-Audio/02-music-recognition-system.md
  docs/05-Tutorials/03-Audio/music_embedding.png
  docs/05-Tutorials/03-Audio/music_recog_system.png
  docs/06-Developer Guides/framework/architecture-overview.md
  docs/06-Developer Guides/framework/architecture-part-i.md
  docs/06-Developer Guides/framework/architecture-part-ii.md
  docs/06-Developer Guides/framework/architecture-part-iii.md
  docs/06-Developer Guides/framework/dag.png
  docs/06-Developer Guides/framework/ensemble-image-embedding.md
  docs/06-Developer Guides/framework/framework.png
  docs/06-Developer Guides/framework/hub-integration-and-caching.md
  docs/06-Developer Guides/framework/pipeline-overview.md
  docs/06-Release Notes/040-release-notes.md
  docs/06-Release Notes/050-release-notes.md
  docs/06-Release Notes/060-release-notes.md
  tests/unittests/documents/test_dc_get_started.py
Labels: lgtm, approved, size/XL

#1212 Add badges for pylint and codecov
  README.md
Labels: lgtm, approved, size/XS

#1213 add embedding_extractor
  tests/unittests/models/embedding/test_embedding_extractor.py
  towhee/models/embedding/embedding_extractor.py
Labels: lgtm, size/L, approved

#1174 fix queue hang in split
  towhee/functional/mixins/parallel.py
  towhee/functional/mixins/ray.py
Labels: lgtm, approved, size/M

#1215 Update links for new docs structure
  docs/01-Overview.md
  docs/03-User Guides/03-Built-in Pipelines/audio-embedding.md
  docs/03-User Guides/03-Built-in Pipelines/image-embedding.md
  docs/05-Tutorials/03-Audio/01-music-recognition-system.md
  docs/06-Release Notes/release-notes-040.md
  docs/06-Release Notes/release-notes-050.md
  docs/06-Release Notes/release-notes-060.md
Labels: lgtm, approved, size/S

#1220 Use download instead clone in cmd
  towhee/command/repo.py
Labels: lgtm, approved, size/XS

#1218 add uniformer model and ut
  tests/unittests/models/uniformer/__init__.py
  tests/unittests/models/uniformer/test_uniformer.py
  towhee/models/uniformer/__init__.py
  towhee/models/uniformer/uniformer.py
Labels: lgtm, approved, size/XL, component/models

#1223 make clip4clip code compatible with clip
  tests/unittests/models/clip4clip/test_clip4clip.py
  towhee/models/clip/clip.py
  towhee/models/clip4clip/__init__.py
  towhee/models/clip4clip/clip4clip.py
  towhee/models/clip4clip/until_module.py
  towhee/models/clip4clip/utils.py
Labels: lgtm, size/L, approved

#1219 Add encode_image & encode_text to action_clip
  tests/unittests/models/action_clip/test_action_clip.py
  tests/unittests/models/action_clip/test_utils.py
  towhee/models/action_clip/__init__.py
  towhee/models/action_clip/action_clip.py
  towhee/models/action_clip/action_clip_utils.py
Labels: lgtm, approved, size/M, component/models

#1229 Quick ray bug fix for actors
  towhee/functional/mixins/parallel.py
  towhee/functional/mixins/ray.py
Labels: lgtm, approved, size/S

#1235 add violet for video retrieval
  tests/unittests/models/violet/test_violet.py
  towhee/models/violet/violet.py
Labels: lgtm, size/L, approved

#1236 Move scipy dependency into scipy_utils to raise error properly
  towhee/hub/builtin/operators/sklearn.py
  towhee/utils/scipy_utils.py
Labels: lgtm, approved, size/M

#1225 Spilt DataFrame from DataCollection to deal with Entity-based DC separately
  tests/unittests/functional/test_data_collection.py
  tests/unittests/functional/test_mixins.py
  towhee/__init__.py
  towhee/functional/__init__.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/dataframe.py
  towhee/functional/mixins/serve.py
Labels: lgtm, size/L, approved

#1239 Update towhee version for main branch
  setup.py
Labels: lgtm, approved, size/XS

#1237 Sync with main and modify branch in workflow
  .github/workflows/pr_test.yml
  .github/workflows/publish_dev_package.yml
  tests/unittests/models/violet/test_violet.py
  towhee/hub/builtin/operators/sklearn.py
  towhee/models/violet/violet.py
  towhee/utils/scipy_utils.py
Labels: lgtm, size/L, approved

#1243 Update get file method
  towhee/utils/hub_utils.py
Labels: lgtm, approved, size/XS

#1244 Update get file method to 0.6.1
  towhee/utils/hub_utils.py
Labels: lgtm, approved, size/XS

#1250 Update towhee version for 0.6.1 branch
  setup.py
Labels: lgtm, approved, size/XS

#1253 Add ACAR-NET Neck modules
  tests/unittests/models/acar_net/__init__.py
  tests/unittests/models/acar_net/test_acar_neck.py
  towhee/models/acar_net/__init__.py
  towhee/models/acar_net/neck.py
  towhee/models/acar_net/utils.py
Labels: lgtm, size/L, approved, component/models

#1254 add vcopheader for allinone
  tests/unittests/models/allinone/test_allinone.py
  towhee/models/allinone/allinone.py
Labels: lgtm, approved, size/M

#1255 Add heads for ACAR-Net
  tests/unittests/models/acar_net/test_acar_head.py
  towhee/models/acar_net/__init__.py
  towhee/models/acar_net/head.py
  towhee/models/acar_net/utils.py
Labels: lgtm, size/L, approved, component/models

#1256 Add backbone for ACAR-Net
  tests/unittests/models/acar_net/test_acar_backbone.py
  towhee/models/acar_net/__init__.py
  towhee/models/acar_net/backbone.py
  towhee/models/acar_net/head.py
  towhee/models/acar_net/utils.py
  towhee/models/clip/clip.py
Labels: lgtm, size/L, approved, component/models

#1257 bert_mmt module in mdmmt
  tests/unittests/models/mdmmt/__init__.py
  tests/unittests/models/mdmmt/test_bert_mmt.py
  towhee/models/mdmmt/__init__.py
  towhee/models/mdmmt/bert_mmt.py
Labels: lgtm, size/L, approved

#1252 Add to_df and to_dc function for dc and df
  towhee/functional/data_collection.py
Labels: lgtm, approved, size/M

#1258 Build up ACAR-Net with submodules
  tests/unittests/models/acar_net/test_backbone.py
  tests/unittests/models/acar_net/test_head.py
  tests/unittests/models/acar_net/test_model.py
  tests/unittests/models/acar_net/test_neck.py
  towhee/models/acar_net/__init__.py
  towhee/models/acar_net/backbone.py
  towhee/models/acar_net/head.py
  towhee/models/acar_net/model.py
  towhee/models/acar_net/neck.py
Labels: lgtm, size/L, approved, component/models

#1264 Update the reverse image search tutorial
  docs/05-Tutorials/02-Computer Vision/01-reverse-image-search.md
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_metric1.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_metric2.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_metric3.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_results.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_showcase.gif
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_showcsv.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_workflow.png
  tutorials/reverse_image_search.ipynb
Labels: lgtm, approved, size/XL

#1266 Update image format
  docs/05-Tutorials/02-Computer Vision/01-reverse-image-search.md
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_results1.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_results2.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_step1.png
  docs/05-Tutorials/02-Computer Vision/reverse_image_search_step2.png
Labels: lgtm, approved, size/S

#1271 Update and debug video_transforms
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/M, component/models

#1273 Remove dtype scale from video_transforms
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/XS, component/models

#1274 Merge towhee.df into towhee.dc
  towhee/__init__.py
  towhee/functional/__init__.py
Labels: lgtm, approved, size/S

#1276 Remove any(map(...)) in case of unexpected return value
  towhee/functional/mixins/column.py
  towhee/functional/mixins/save.py
Labels: lgtm, approved, size/S

#1277 Fix bug for video_transforms
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/XS, component/models

#1269 auto_download packages
  towhee/utils/cv2_utils.py
  towhee/utils/dependency_control.py
Labels: lgtm, approved, size/M

#1272 Add VideoFrame
  tests/unittests/types/test_video_frame.py
  towhee/types/__init__.py
  towhee/types/video_frame.py
Labels: lgtm, size/L, approved

#1280 Fix bug for action_clip using cuda
  towhee/models/action_clip/action_clip.py
Labels: lgtm, approved, size/XS, component/models

#1281 Add quick-start notebook for colab link & debug quick-start steps
  README.md
  docs/02-Getting Started/01-quick-start.mdx
  docs/02-Getting Started/quick-start.ipynb
Labels: lgtm, size/L, approved

#1282 Fix issue when save image list
  towhee/hub/builtin/operators/computer_vision.py
Labels: lgtm, approved, size/S

#1283 add read_video and to_video
  towhee/__init__.py
  towhee/functional/__init__.py
  towhee/functional/mixins/computer_vision.py
  towhee/types/image_utils.py
Labels: lgtm, approved, size/M

#1284 Feature/add read to video
  towhee/functional/mixins/computer_vision.py
Labels: lgtm, approved, size/XS

#1285 Remove duplicate directory
  docs/03-User Guides/01-command-line-tool.md
  docs/03-User Guides/02-DataCollection/01-data-collection.md
  docs/03-User Guides/02-DataCollection/02-data-collection-with-ray.md
  docs/03-User Guides/02-command-line-tool.md
  docs/05-Release Notes/release-notes-040.md
  docs/05-Release Notes/release-notes-050.md
  docs/05-Release Notes/release-notes-060.md
Labels: lgtm, approved, size/M

#1286 Fix broken links
  docs/01-Overview.md
  tests/unittests/documents/test_dc_get_started.py
Labels: lgtm, approved, size/XS

#1288 Generate DataFrame instead of DataCollection when read json and csv
  towhee/functional/__init__.py
Labels: lgtm, approved, size/XS

#1291 feat autoinstall pandas
  towhee/utils/pandas_utils.py
Labels: lgtm, approved, size/S

#1293 feat: enhance save-images api
  towhee/hub/builtin/operators/computer_vision.py
Labels: lgtm, approved, size/S

#1287 Modify the testcase
  tests/testcases/requirements.text
  tests/testcases/test_data_collection.py
Labels: lgtm, approved, size/M

#1294 chore: deps prompt install for all utils
  towhee/utils/cv2_utils.py
  towhee/utils/ipython_utils.py
  towhee/utils/matplotlib_utils.py
  towhee/utils/milvus_utils.py
  towhee/utils/ndarray_utils.py
  towhee/utils/pandas_utils.py
  towhee/utils/pil_utils.py
  towhee/utils/plot_utils.py
  towhee/utils/scipy_utils.py
  towhee/utils/sklearn_utils.py
Labels: lgtm, size/L, approved

#1295 add tensor array
  towhee/types/tensor_array.py
  towhee/utils/thirdparty/pyarrow.py
Labels: lgtm, size/L, approved

#1296 Add configs for large pretrained timesformer model
  tests/unittests/models/timesformer/test_timesformer.py
  towhee/models/timesformer/timesformer_utils.py
Labels: lgtm, approved, size/M, component/models

#1290 repair when video_mask is None
  towhee/models/clip4clip/clip4clip.py
Labels: lgtm, approved, size/XS

#1298 chunk support for tensor array
  towhee/types/tensor_array.py
Labels: lgtm, approved, size/S

#1304 modify timesformer
  tests/unittests/models/timesformer/test_timesformer.py
  towhee/models/timesformer/timesformer.py
  towhee/models/timesformer/timesformer_block.py
Labels: lgtm, approved, size/M

#1302 add movinet
  tests/unittests/models/layers/test_conv_bn_activation.py
  tests/unittests/models/layers/test_padding_functions.py
  tests/unittests/models/layers/test_temporal_cg_avgpool3d.py
  tests/unittests/models/layers/test_tf_avgpool3d.py
  tests/unittests/models/movinet/__init__.py
  tests/unittests/models/movinet/test_movinet.py
  towhee/models/layers/conv_bn_activation.py
  towhee/models/layers/padding_functions.py
  towhee/models/layers/temporal_cg_avgpool3d.py
  towhee/models/layers/tf_avgpool3d.py
  towhee/models/movinet/__init__.py
  towhee/models/movinet/config.py
  towhee/models/movinet/movinet.py
  towhee/models/movinet/movinet_block.py
  towhee/models/utils/causal_module.py
Labels: lgtm, approved, size/XXL, component/models

#1308 add ut for crossmodel
  tests/unittests/models/drl/test_drl.py
Labels: lgtm, approved, size/S

#1310 optimize code in create clip model
  towhee/models/clip/clip.py
Labels: lgtm, approved, size/XS
