Repository towhee-io/towhee, pull requests merged in 2022-01, with the labels that each got.

#382 Refactor dir
  towhee/data_source/__init__.py
  towhee/dataframe/array/__init__.py
  towhee/dataframe/array/_array_ref.py
  towhee/dataframe/array/array.py
  towhee/dataframe/array/utils.py
  towhee/dataframe/dataframe_v2.py
  towhee/tests/array/test_array.py
  towhee/tests/dataframe/test_dataframe_v2.py
Labels: lgtm, approved, component/engine, size/M

#386 Add music_recognition_tutorial notebook
  tutorials/music_recognition_tutorial.ipynb
Labels: lgtm, size/L, approved

#387 Add tutorial for reverse_image_search in notebook
  tutorials/reverse_image_search.ipynb
Labels: lgtm, size/L, approved

#380 Replace download with git system
  requirements.txt
  towhee/hub/file_manager.py
  towhee/hub/hub_tools.py
Labels: lgtm, size/L, approved

#414 Add Milvus link
  README.md
Labels: lgtm, approved, size/XS

#411 Replace branch with tag
  towhee/__init__.py
  towhee/hub/file_manager.py
  towhee/hub/hub_tools.py
Labels: lgtm, approved, size/M

#418 Use pathlib instead of os.path
  towhee/hub/hub_tools.py
Labels: lgtm, approved, size/S

#421 Update Towhee website link in README
  README.md
Labels: lgtm, approved, size/XS

#432 Add docs
  docs/developer-guides/contributing/contributing-guide.md
  docs/developer-guides/framework/DAG-details.md
  docs/developer-guides/framework/architectural-overview.md
  docs/developer-guides/framework/dag.png
  docs/developer-guides/framework/engine-details.md
  docs/developer-guides/framework/framework.png
  docs/developer-guides/framework/hub-integration-and-caching.md
  docs/developer-guides/framework/image-ensemble-training.md
  docs/developer-guides/framework/layer-details.md
  docs/developer-guides/framework/roadmap.md
  docs/developer-guides/framework/swin_arch.png
  docs/get-started/back.mdx
  docs/get-started/install.md
  docs/get-started/pipeline-config.md
  docs/get-started/quick-start.mdx
  docs/get-started/towhee.jpeg
  docs/operators/image-loading-and-transforms.md
  docs/operators/model-based-operators.md
  docs/overview.md
  docs/pipelines/audio-embedding.md
  docs/pipelines/image-embedding.md
  docs/sidebars.js
  docs/tutorials/image-deduplication.md
  docs/tutorials/image_dedup.png
  docs/tutorials/music-recognition-system.md
  docs/tutorials/music_embedding.png
  docs/tutorials/music_recog_system.png
  docs/tutorials/reverse-image-search.md
  docs/tutorials/reverse_image_search_results1.png
  docs/tutorials/reverse_image_search_results2.png
  docs/tutorials/reverse_image_search_step1.png
  docs/tutorials/reverse_image_search_step2.png
Labels: lgtm, approved, size/XXL

#434 Delete useless doc
  docs/get-started/back.mdx
Labels: lgtm, approved, size/M

#435 Add check docs update action
  .github/workflows/check-docs-update.yml
Labels: lgtm, approved, size/S

#441 Update README.md image in dark mode
  README.md
  towhee_logo_dark.png
Labels: lgtm, approved, size/XS

#437 Reconstruct hub_tools and create repo managers
  towhee/hub/download_tools.py
  towhee/hub/hub_tools.py
  towhee/hub/operator_manager.py
  towhee/hub/pipeline_manager.py
  towhee/hub/repo_manager.py
Labels: lgtm, approved, size/XL

#444 Add music recognition tutorial author
  docs/get-started/quick-start.mdx
  docs/tutorials/music-recognition-system.md
Labels: lgtm, approved, size/XS

#442 Add test for repo_manager
  tests/unittests/hub/test_repo_manager.py
  towhee/hub/repo_manager.py
Labels: lgtm, approved, size/M

#450 Update image links in music-recog notebook
  tutorials/music_recognition_tutorial.ipynb
Labels: lgtm, approved, size/XS

#452 Update image links in reverse_image_search notebook
  tutorials/reverse_image_search.ipynb
Labels: lgtm, approved, size/XS

#461 Add pylint check for unittests
  .github/workflows/pylint.yml
  tests/unittests/data/dataset/test_dataset.py
  tests/unittests/data/test_random_erase.py
  tests/unittests/engine/test_engine.py
  tests/unittests/engine/test_operator_pool.py
  tests/unittests/engine/test_pipeline.py
  tests/unittests/models/embedding/test_embedding_extractor.py
Labels: lgtm, approved, size/S

#465 refactor the trainer framework
  tests/unittests/cnn_trainer/__init__.py
  tests/unittests/trainer/test_args.py
  tests/unittests/trainer/test_callback.py
  tests/unittests/trainer/test_trainer.py
  towhee/cnn_trainer/trainer_callback.py
  towhee/cnn_trainer/utils/__init__.py
  towhee/trainer/callback.py
  towhee/trainer/loss.py
  towhee/trainer/metrics.py
  towhee/trainer/modelcard.py
  towhee/trainer/towheemodel.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
  towhee/trainer/training_summary.py
  towhee/trainer/utils/__init__.py
  towhee/trainer/utils/logging.py
  towhee/trainer/utils/trainer_utils.py
Labels: lgtm, approved, size/XL

#449 Update func about init and generate-yaml
  towhee/hub/operator_manager.py
  towhee/hub/pipeline_manager.py
  towhee/hub/repo_manager.py
Labels: lgtm, size/L, approved

#466 Update main for hub tool
  setup.py
  towhee/hub/README.md
  towhee/hub/bin/__init__.py
  towhee/hub/bin/hub_tools.py
Labels: lgtm, size/L, approved

#426 Allow specifying tag of repos
  tests/unittests/engine/operator_runner/test_concat_runner.py
  tests/unittests/engine/operator_runner/test_filter_runner.py
  tests/unittests/engine/operator_runner/test_flatmap_runner.py
  tests/unittests/engine/operator_runner/test_generator_runner.py
  tests/unittests/engine/operator_runner/test_map_runner.py
  tests/unittests/engine/operator_runner/test_runner_base.py
  tests/unittests/engine/operator_runner/test_window_runner.py
  tests/unittests/engine/test_operator_pool.py
  tests/unittests/engine/test_thread_pool_task_executor.py
  tests/unittests/hub/test_download.py
  towhee/dag/operator_repr.py
  towhee/engine/operator_context.py
  towhee/engine/operator_loader.py
  towhee/engine/operator_pool.py
  towhee/engine/operator_runner/__init__.py
  towhee/engine/operator_runner/concat_runner.py
  towhee/engine/operator_runner/runner_base.py
  towhee/engine/thread_pool_task_executor.py
  towhee/hub/file_manager.py
Labels: lgtm, size/L, approved

#454 Use threadpool to download
  tests/unittests/hub/test_download.py
  tests/unittests/hub/test_operator_manager.py
  tests/unittests/hub/test_pipeline_manager.py
  tests/unittests/hub/test_repo_manager.py
  towhee/hub/bin/hub_tools.py
  towhee/hub/operator_manager.py
  towhee/hub/pipeline_manager.py
  towhee/hub/repo_manager.py
Labels: lgtm, size/L, approved

#470 Update loader with importmodule
  towhee/engine/operator_loader.py
Labels: size/S

#469 add towhee command line tool
  docs/developer-guides/cmdline.md
  setup.py
  towhee/hub/cmdline.py
  towhee/hub/subcmds/develop.py
  towhee/hub/subcmds/template.py
Labels: lgtm, size/L

#472 [Documentation]: Update broken links
  docs/pipelines/image-embedding.md
Labels: lgtm, approved, size/XS

#468 Fix doc broken links
  docs/get-started/quick-start.mdx
  docs/pipelines/image-embedding.md
Labels: lgtm, approved, size/XS

#474 Update reverse image search tutorial
  docs/tutorials/reverse-image-search.md
Labels: lgtm, approved, size/XS

#473 Refactor RepoManager and add hub utils
  tests/unittests/hub/test_operator_manager.py
  tests/unittests/hub/test_pipeline_manager.py
  tests/unittests/hub/test_repo_manager.py
  tests/unittests/utils/test_hub_utils.py
  towhee/hub/download_tools.py
  towhee/hub/operator_manager.py
  towhee/hub/pipeline_manager.py
  towhee/hub/repo_manager.py
  towhee/utils/hub_utils.py
Labels: lgtm, approved, size/XL

#456 Add markdown links check
  .github/workflows/markdown-check.yml
Labels: lgtm, approved, size/S

#481 Update towhee test version
  tests/testcases/requirements.text
Labels: lgtm, approved, size/XS

#483 fix the EmbeddingExtractor bug
  tests/unittests/models/embedding/test_embedding_extractor.py
  towhee/models/embedding/__init__.py
  towhee/models/embedding/embedding_extractor.py
Labels: lgtm, approved, size/S, model

#478 Update pipeline links in Audio-embedding Pipeline
  docs/pipelines/audio-embedding.md
Labels: lgtm, approved, size/XS

#491 Refactor models
  tests/unittests/models/layers/test_patch_embed2d.py
  towhee/models/layers/__init__.py
  towhee/models/layers/patch_embed2d.py
  towhee/models/layers/patch_merging.py
  towhee/models/multiscale_vision_transformers/create_multiscale_vision_transformers.py
  towhee/models/swin_transformer/model.py
  towhee/models/swin_transformer/swin_transformer_block.py
  towhee/models/swin_transformer/utils.py
  towhee/models/swin_transformer/window_attention.py
  towhee/models/utils/init_vit_weights.py
  towhee/models/utils/weight_init.py
  towhee/trainer/models/layers/__init__.py
  towhee/trainer/models/layers/drop.py
  towhee/trainer/models/layers/mlp.py
  towhee/trainer/models/layers/weight_init.py
  towhee/trainer/models/swin_transformer/__init__.py
  towhee/trainer/models/swin_transformer/configs.py
  towhee/trainer/models/swin_transformer/model.py
  towhee/trainer/models/swin_transformer/utils.py
  towhee/trainer/models/utils/__init__.py
  towhee/trainer/models/utils/pretrained_utils.py
Labels: lgtm, approved, size/XXL

#487 Create git utils and test
  tests/unittests/hub/test_repo_manager.py
  tests/unittests/utils/test_git_utils.py
  tests/unittests/utils/test_hub_utils.py
  towhee/hub/repo_manager.py
  towhee/utils/git_utils.py
Labels: lgtm, size/L, approved

#486 Add execute subcmd for towhee
  requirements.txt
  towhee/engine/operator_loader.py
  towhee/hub/cmdline.py
  towhee/hub/subcmds/__init__.py
  towhee/hub/subcmds/develop.py
  towhee/hub/subcmds/execute.py
  towhee/hub/subcmds/template.py
Labels: lgtm, size/L

#493 Add the callback for trainer.
  tests/unittests/trainer/test_callback.py
  towhee/trainer/callback.py
  towhee/trainer/trainer.py
Labels: lgtm, size/L, approved, component/trainer

#495 Fix repo init bug with nnoperator
  towhee/hub/hub_tools.py
Labels: lgtm, approved, size/M

#496 Training
  tests/unittests/trainer/test_trainer.py
  towhee/operator/base.py
  towhee/trainer/dataset.py
  towhee/trainer/modelcard.py
  towhee/trainer/optimization/optimization.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
  towhee/trainer/training_summary.py
  towhee/trainer/utils/trainer_utils.py
Labels: lgtm, approved, size/XL, component/trainer

#494 Refeactor the repo manager
  setup.py
  tests/unittests/hub/test_operator_manager.py
  tests/unittests/hub/test_pipeline_manager.py
  tests/unittests/hub/test_repo_manager.py
  tests/unittests/utils/test_hub_utils.py
  towhee/hub/bin/README.md
  towhee/hub/bin/hub_tools.py
  towhee/hub/bin/towheehub.png
  towhee/hub/operator_manager.py
  towhee/hub/pipeline_manager.py
  towhee/hub/repo_manager.py
  towhee/utils/hub_utils.py
Labels: lgtm, approved, size/XXL

#500 Add test cases
  tests/testcases/requirements.text
  tests/testcases/test_audio_embedding.py
  tests/testcases/test_image_embedding.py
  tests/testcases/test_main.py
Labels: lgtm, size/L, approved

#509 Add the metrics for trainer.
  test_requirements.txt
  tests/unittests/trainer/test_metrics.py
  towhee/trainer/metrics.py
Labels: enhancement, lgtm, size/L, approved, component/trainer

#497 Support Pytorch model when packaging
  towhee/hub/subcmds/develop.py
Labels: lgtm, size/XS

#459 Add frame and schema
  tests/unittests/dataframe/test_dataframe.py
  tests/unittests/engine/operator_io/test_reader.py
  tests/unittests/engine/operator_runner/test_filter_runner.py
  tests/unittests/engine/operator_runner/test_flatmap_runner.py
  tests/unittests/engine/operator_runner/test_generator_runner.py
  tests/unittests/engine/operator_runner/test_map_runner.py
  tests/unittests/engine/operator_runner/test_window_runner.py
  tests/unittests/engine/test_engine.py
  tests/unittests/engine/test_operator_context.py
  tests/unittests/engine/test_pipeline.py
  tests/unittests/engine/test_thread_pool_task_executor.py
  tests/unittests/mock_operators/repeat_operator/repeat_operator.py
  tests/unittests/mock_operators/zero_drop/zero_drop.py
  tests/unittests/test_util/test_generator/test_generator.yaml
  tests/unittests/test_util/test_window/test_window.yaml
  towhee/dataframe/_schema.py
  towhee/dataframe/dataframe.py
  towhee/engine/graph_context.py
  towhee/engine/operator_context.py
  towhee/engine/operator_io/__init__.py
  towhee/engine/operator_io/reader.py
  towhee/engine/operator_io/writer.py
  towhee/engine/operator_runner/__init__.py
  towhee/engine/operator_runner/filter_runner.py
  towhee/engine/operator_runner/flatmap_runner.py
  towhee/engine/operator_runner/generator_runner.py
  towhee/engine/operator_runner/runner_base.py
  towhee/engine/operator_runner/window_runner.py
  towhee/hub/file_manager.py
  towhee/operator/concat_operator.py
  towhee/operator/nop.py
  towhee/pipeline_format.py
  towhee/types/_frame.py
  towhee/types/image.py
Labels: lgtm, approved, component/engine, component/dataframe, size/XXL

#514 Add a new issue template: DesignProposal
  .github/ISSUE_TEMPLATE/design proposal.yaml
Labels: approved, size/M

#502 Add ut for Reprs and callstack
  tests/unittests/dag/test_repr.py
  tests/unittests/dag/utils/test_callstack.py
  towhee/dag/base_repr.py
  towhee/dag/graph_repr.py
Labels: lgtm, approved, size/M

#501 Modify file manager get function
  requirements.txt
  tests/unittests/hub/bin/test_hub_tools.py
  tests/unittests/hub/test_pipeline_manager.py
  tests/unittests/hub/test_repo_manager.py
  tests/unittests/mock_pipelines/ci_test/README.md
  tests/unittests/utils/test_git_utils.py
  towhee/hub/file_manager.py
  towhee/hub/hub_tools.py
  towhee/hub/repo_manager.py
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/XL

#519 Add Operator APIs to save & load weights
  tests/unittests/trainer/test_weights.py
  towhee/operator/base.py
  towhee/trainer/dataset.py
  towhee/trainer/load_weights.py
  towhee/trainer/save_weights.py
Labels: lgtm, size/L, approved

#522 Feature/support hyperparameter v2
  requirements.txt
  towhee/__init__.py
  towhee/engine/__init__.py
  towhee/engine/operator_registry.py
  towhee/hub/subcmds/execute.py
Labels: size/M

#521 Add test for hub tools and file manager
  tests/unittests/hub/test_file_manager.py
  tests/unittests/hub/test_hub_tools.py
  towhee/hub/bin/hub_tools.py
Labels: lgtm, approved, size/M

#524 Move load_weights and save_weights to trainer/utils
  towhee/operator/base.py
  towhee/trainer/utils/load_weights.py
  towhee/trainer/utils/save_weights.py
Labels: lgtm, approved, size/XS

#529 Add layer freezer
  tests/unittests/trainer/test_freezer.py
  towhee/trainer/utils/layer_freezer.py
Labels: lgtm, size/L, approved
