Repository towhee-io/towhee, pull requests merged in 2022-08, with the labels that each got.

#1648 [Serve] Move format_priority to pipeline config
  tests/unittests/triton/test_builder.py
  tests/unittests/triton/test_to_triton.py
  towhee/__init__.py
  towhee/serve/triton/builder.py
  towhee/serve/triton/constant.py
  towhee/serve/triton/docker_image_builder.py
  towhee/serve/triton/dockerfiles/DockerfileCuda113
  towhee/serve/triton/dockerfiles/DockerfileCuda114
  towhee/serve/triton/dockerfiles/DockerfileCuda116
  towhee/serve/triton/to_triton_models.py
Labels: lgtm, approved, size/M

#1657 add 0.7.3 to model change log
  MODEL_CHANGELOG.md
Labels: lgtm, approved, size/S

#1660 [Serve] pymodel support GPU
  tests/unittests/triton/expected_files/clip_preprocess_model.py
  tests/unittests/triton/expected_files/postprocess/1/model.py
  tests/unittests/triton/expected_files/preprocess/1/model.py
  tests/unittests/triton/expected_files/py_to_triton_test/1/model.py
  tests/unittests/triton/expected_files/resnet50_model.py
  tests/unittests/triton/test_python_model_builder.py
  tests/unittests/triton/test_to_triton.py
  towhee/serve/triton/builder.py
  towhee/serve/triton/python_model_builder.py
Labels: lgtm, approved, size/M

#1661 fix issue 1659
  tests/testcases/test_dag_info.py
  towhee/functional/mixins/dag.py
Labels: lgtm, approved, size/S

#1662 Modify conv_bn_activation & add fuse_bn
  tests/unittests/models/layers/test_conv_bn_activation.py
  tests/unittests/models/utils/test_fuse_bn.py
  towhee/models/layers/conv_bn_activation.py
  towhee/models/utils/fuse_bn.py
Labels: lgtm, size/L, approved, component/models

#1658 Support set jit with towhee-compoiler
  towhee/functional/mixins/compile.py
Labels: lgtm, approved, size/S

#1665 add wave_vit utils
  test_requirements.txt
  tests/unittests/models/wave_vit/__init__.py
  tests/unittests/models/wave_vit/test_wave_vit_utils.py
  towhee/models/wave_vit/wave_vit_utils.py
Labels: lgtm, size/L, approved, component/models

#1666 add wave_vit block
  tests/unittests/models/wave_vit/test_wave_vit_block.py
  tests/unittests/models/wave_vit/test_wave_vit_utils.py
  towhee/models/wave_vit/wave_vit_block.py
Labels: lgtm, size/L, approved, component/models

#1667 Add blocks for RepMLP
  tests/unittests/models/layers/test_ffn.py
  tests/unittests/models/repmlp/__init__.py
  tests/unittests/models/repmlp/test_blocks.py
  towhee/models/layers/ffn.py
  towhee/models/repmlp/__init__.py
  towhee/models/repmlp/blocks.py
Labels: lgtm, size/L, approved, component/models

#1668 Update towhee version and weekly tests
  .github/workflows/weekly_ci.yml
  tests/common/common_func.py
  tests/testcases/hub/execute_hub_operators.py
  tests/testcases/requirements.text
Labels: lgtm, size/L, approved

#1669 add wave_vit main module
  tests/unittests/models/wave_vit/test_wave_vit.py
  towhee/models/wave_vit/__init__.py
  towhee/models/wave_vit/wave_vit.py
  towhee/models/wave_vit/wave_vit_block.py
  towhee/models/wave_vit/wave_vit_utils.py
Labels: lgtm, size/L, approved, component/models

#1670 [Serve] Add test dockerfile
  setup.py
  tests/unittests/triton/expected_files/postprocess/config.pbtxt
  tests/unittests/triton/expected_files/preprocess/config.pbtxt
  tests/unittests/triton/expected_files/py_to_triton_test/1/model.py
  tests/unittests/triton/expected_files/resnet50_model.py
  towhee/serve/triton/dockerfiles/DockerfileCuda114dev
  towhee/serve/triton/dockerfiles/__init__.py
  towhee/serve/triton/python_model_builder.py
  towhee/serve/triton/triton_config_builder.py
Labels: lgtm, approved, size/M

#1679 repair problem that model's device and data's device are not the same.
  .github/workflows/codecov.yml
  test_requirements.txt
  tests/testcases/requirements.text
  tests/unittests/mock_operators/triton_nnop/model.py
  tests/unittests/models/action_clip/test_action_clip.py
  tests/unittests/models/action_clip/test_pretrained.py
  tests/unittests/models/bridgeformer/test_bridge_former.py
  tests/unittests/models/clip/test_clip.py
  tests/unittests/models/clip4clip/test_clip4clip.py
  tests/unittests/models/coformer/test_coformer.py
  tests/unittests/models/collaborative_experts/test_collaborative_experts.py
  tests/unittests/models/cvnet/test_cvnet.py
  tests/unittests/models/max_vit/test_max_vit.py
  tests/unittests/models/movinet/test_movinet.py
  tests/unittests/models/mpvit/test_mpvit.py
  tests/unittests/models/svt/test_svt.py
  tests/unittests/models/visualization/test_clip_vis.py
  tests/unittests/models/wave_vit/test_wave_vit.py
  towhee/models/clip/clip.py
  towhee/models/visualization/clip_visualization.py
Labels: lgtm, size/L, approved

#1675 Add RepMLP block
  tests/unittests/models/repmlp/test_blocks.py
  towhee/models/repmlp/blocks.py
Labels: lgtm, size/L, approved, component/models

#1672 Add stream parallel when CUDA available
  towhee/functional/mixins/parallel.py
Labels: lgtm, approved, size/M

#1680 Add repmlp model
  tests/unittests/models/repmlp/test_repmlp.py
  towhee/models/repmlp/__init__.py
  towhee/models/repmlp/repmlp.py
Labels: lgtm, size/L, approved, component/models

#1684 Update README for 0.7.3 release
  README.md
Labels: type/doc, lgtm, approved, size/S, kind/documentation

#1687 RepMLP: add configs for different model names
  tests/unittests/models/repmlp/test_configs.py
  tests/unittests/models/repmlp/test_repmlp.py
  towhee/models/repmlp/configs.py
  towhee/models/repmlp/repmlp.py
Labels: lgtm, size/L, approved, component/models

#1686 Update trigger pr test rules
  .github/workflows/codecov.yml
  .github/workflows/pr_test.yml
  .github/workflows/pylint.yml
Labels: size/M

#1685 add dockerfile
  Dockerfile
Labels: lgtm, approved, size/M

#1690 Add publish docker image
  .github/workflows/publish_ut_image.yml
Labels: lgtm, approved, size/M

#1691 fix install triton requirement
  towhee/utils/tritonclient_utils.py
Labels: lgtm, approved, size/XS

#1695 add latest docker image version
  .github/workflows/publish_ut_image.yml
Labels: lgtm, approved, size/XS

#1696 fix docker tag
  .github/workflows/publish_ut_image.yml
Labels: lgtm, approved, size/XS

#1698 Add nnfp to towhee.models README
  towhee/models/README.md
Labels: type/doc, lgtm, approved, size/XS, component/models, kind/documentation

#1699 Add nnfp to models table (CN)
  towhee/models/README_CN.md
Labels: type/doc, lgtm, approved, size/XS, component/models, kind/documentation

#1702 Add torchaudio in dockerfile
  Dockerfile
Labels: lgtm, approved, size/XS

#1689 Bugfix jit the operator
  towhee/functional/mixins/compile.py
Labels: lgtm, approved, size/XS

#1692 Support time window in DC
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/audio.py
  towhee/functional/mixins/computer_vision.py
  towhee/functional/mixins/data_processing.py
Labels: lgtm, size/L, approved

#1704 Update towhee version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#1707 fix import torch
  towhee/functional/mixins/parallel.py
Labels: lgtm, approved, size/S

#1706 fix import torch
  towhee/functional/mixins/parallel.py
Labels: lgtm, approved, size/S

#1708 Update command README
  towhee/command/README.md
Labels: lgtm, approved, size/S

#1712 Update towhee version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#1716 Adjust the file name to be consistent with the project code style
  README.md
  README_CN.md
Labels: lgtm, approved, size/XS

#1697 add ut in docker
  .github/workflows/codecov.yml
Labels: lgtm, approved, size/M

#1718 fix docstring of CoCa.
  towhee/models/coca/coca.py
Labels: lgtm, approved, size/M

#1719 docs: update document content
  README_CN.md
Labels: lgtm, approved, size/S

#1709 Add Wave-ViT to towhee models table (EN)
  towhee/models/README.md
Labels: lgtm, approved, size/XS

#1710 Add Wave-ViT to towhee models table (CN)
  towhee/models/README_CN.md
Labels: lgtm, approved, size/XS

#1711 Remove useless README
  towhee/models/vggish/README.md
Labels: lgtm, approved, size/XS

#1722 fix pylint for CoCa.
  towhee/models/coca/coca.py
Labels: lgtm, approved, size/S

#1564 Update README.md
  README.md
Labels: lgtm, approved, size/M

#1700 Add docstring for AcarNet
  towhee/models/acar_net/model.py
Labels: lgtm, approved, size/XS, component/models

#1725 add unit test for `exception_safe`
  tests/unittests/functional/test_exception_safe.py
Labels: lgtm, approved, size/M

#1723 Assert log instead of compare time with failed compile
  tests/unittests/functional/test_mixins.py
Labels: lgtm, approved, size/M

#1724 [Serve] Add Data Transformer in Py Models
  tests/unittests/triton/bls/__init__.py
  tests/unittests/triton/bls/model_runner/__init__.py
  tests/unittests/triton/bls/model_runner/test_transformer.py
  towhee/serve/triton/bls/__init__.py
  towhee/serve/triton/bls/mock/__init__.py
  towhee/serve/triton/bls/mock/mock_pb_util.py
  towhee/serve/triton/bls/model_runner/__init__.py
  towhee/serve/triton/bls/model_runner/transformer.py
  towhee/serve/triton/bls/python_backend_wrapper.py
  towhee/serve/triton/bls/utils/__init__.py
  towhee/serve/triton/bls/utils/type_util.py
Labels: lgtm, approved, size/XL

#1727 drop pipeline inject
  tests/unittests/pipelines/test_pipeline_template.py
  towhee/__init__.py
Labels: lgtm, size/L, approved

#1728 Refactor towhee command
  tests/unittests/command/test_cmdline.py
  towhee/command/README.md
  towhee/command/cmdline.py
  towhee/command/repo.py
Labels: lgtm, size/L, approved

#1731 Add docstring to Mlp layer
  towhee/models/layers/mlp.py
Labels: lgtm, approved, size/M

#1732 Add TransRAC to model table (CN)
  towhee/models/README_CN.md
Labels: lgtm, approved, size/XS

#1733 Add TransRAC to models table (EN)
  towhee/models/README.md
Labels: lgtm, approved, size/XS

#1734 Add ut for select
  towhee/functional/mixins/dataframe.py
Labels: lgtm, approved, size/S

#1715 Additional comments
  towhee/engine/factory.py
  towhee/functional/mixins/compile.py
  towhee/functional/mixins/dag.py
  towhee/functional/mixins/serve.py
  towhee/functional/mixins/state.py
  towhee/hparam/hyperparameter.py
Labels: lgtm, approved, size/S, type/api-doc

#1729 Refactor read_video
  towhee/functional/mixins/computer_vision.py
Labels: lgtm, approved, size/XS

#1735 Update command README and add ut
  tests/unittests/command/test_cmdline.py
  towhee/command/README.md
Labels: lgtm, approved, size/S

#1739 Cleanup towhe hub
  tests/unittests/hub/bin/test_hub_tools.py
  tests/unittests/hub/test_hub_tools.py
  towhee/hub/bin/__init__.py
  towhee/hub/bin/hub_tools.py
  towhee/hub/bin/towheehub.png
  towhee/hub/cmdline.py
  towhee/hub/operator_manager.py
  towhee/hub/subcmds/__init__.py
  towhee/hub/subcmds/develop.py
  towhee/hub/subcmds/execute.py
Labels: lgtm, approved, size/XL

#1737 Allow users to selectively use MIRROR when building docker images
  Dockerfile
Labels: lgtm, approved, size/S

#1747 Improve the MIRROR function in the Towhee Docker Image
  Dockerfile
Labels: lgtm, approved, size/S

#1751 readme grammar mistake
  README.md
Labels: lgtm, approved, size/XS

#1742 delete unused requirement
  test_requirements.txt
Labels: lgtm, approved, size/XS

#1743 Add RepMLP to model table (EN)
  towhee/models/README.md
Labels: lgtm, approved, size/XS

#1744 Add RepMLP to model table (CN)
  towhee/models/README_CN.md
Labels: lgtm, approved, size/XS

#1750 updating range
  towhee/__init__.py
  towhee/functional/__init__.py
Labels: lgtm, approved, size/M

#1748 Refactor batch to deal with Entity normally
  towhee/functional/mixins/data_processing.py
Labels: lgtm, approved, size/S

#1746 add clip4clip constructor type
  towhee/models/clip4clip/clip4clip.py
Labels: lgtm, approved, size/S

#1753 add docstring in AttentionPool2d in clip
  towhee/models/clip/clip.py
Labels: lgtm, approved, size/XS

#1755 add docstring for modified ResNet
  towhee/models/clip/clip.py
Labels: lgtm, approved, size/XS

#1754 add transformer visual function type
  towhee/models/visualization/transformer_visualization.py
Labels: lgtm, approved, size/XS

#1760 add docstring for ResidualAttentionBlock
  towhee/models/clip/clip.py
Labels: lgtm, approved, size/M

#1759 docs: update whats-new in readme with towhee v0.8.0
  README.md
Labels: lgtm, approved, size/XS

#1763 docs: update whats-new in readme_cn with towhee v0.8.0
  README_CN.md
Labels: lgtm, approved, size/XS

#1764 fix comment of drop_nans.
  towhee/models/collaborative_experts/collaborative_experts.py
Labels: lgtm, approved, size/S

#1766 Update readme link
  README.md
  README_CN.md
Labels: lgtm, approved, size/XS

#1767 chore: adjust the static resource location used by the project document
  README.md
  README_CN.md
  assets/towhee_example.png
  assets/towhee_logo_dark.png
  assets/towhee_logo_square.png
Labels: lgtm, approved, size/XS

#1773 docs: update content in model docs with towhee v0.8.0
  MODEL_CHANGELOG.md
Labels: lgtm, approved, size/S

#1772 Fixed static resources referenced by Towhee Model documentation page in GitHub dark mode
  towhee/models/README.md
  towhee/models/README_CN.md
Labels: lgtm, approved, size/XS

#1765 Update towhee.dc in statemixin
  towhee/functional/mixins/state.py
Labels: lgtm, approved, size/XS

#1769 Add docstring for ACAR-Net backbone bottleneck
  towhee/models/acar_net/backbone.py
Labels: lgtm, approved, size/S

#1770 Add docstring for ACAR-Net head
  towhee/models/acar_net/head.py
Labels: lgtm, approved, size/S

#1771 Add docstring for ACAR-Net neck
  towhee/models/acar_net/neck.py
Labels: lgtm, approved, size/XS

#1741 Remove useless overlaod func in Entity
  towhee/functional/entity.py
Labels: lgtm, approved, size/S

#1775 mv av util to thirdparty
  towhee/__init__.py
  towhee/functional/mixins/audio.py
  towhee/functional/mixins/computer_vision.py
  towhee/utils/thirdparty/av_utils.py
Labels: lgtm, approved, size/S

#1776 fix comment of sharded_single_view_inner_product.
  towhee/models/collaborative_experts/collaborative_experts.py
Labels: lgtm, approved, size/S

#1774 Replace init_weights with towhee.models.utils in actionclip
  tests/unittests/models/action_clip/test_prompt.py
  towhee/models/action_clip/visual_prompt.py
Labels: lgtm, approved, size/M, component/models

#1777 fix comment of sharded_cross_view_inner_product.
  towhee/models/collaborative_experts/collaborative_experts.py
Labels: lgtm, approved, size/S

#1778 add mpvit function args info.
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/S

#1756 Update the docstring in repo command
  towhee/command/repo.py
Labels: lgtm, approved, size/XS

#1740 Support flatten with schema
  towhee/functional/entity.py
  towhee/functional/mixins/data_processing.py
Labels: lgtm, approved, size/M

#1782 Sort imports
  towhee/__init__.py
  towhee/functional/__init__.py
Labels: lgtm, approved, size/S

#1781 Fix ci
  .github/workflows/nightly_ci.yml
  .github/workflows/weekly_ci.yml
Labels: lgtm, approved, size/M

#1783 Sort glob and range
  towhee/functional/__init__.py
Labels: lgtm, approved, size/M

#1780 move faiss util
  towhee/functional/mixins/faiss.py
  towhee/hub/builtin/operators/faiss_search.py
  towhee/utils/thirdparty/faiss_utils.py
Labels: lgtm, approved, size/XS

#1784 move milvus util
  towhee/connectors/ann_index/milvus.py
  towhee/functional/mixins/milvus.py
  towhee/hub/builtin/operators/milvus_search.py
  towhee/utils/thirdparty/milvus_utils.py
Labels: lgtm, approved, size/S

#1789 add drl construction args type.
  towhee/models/drl/drl.py
Labels: lgtm, approved, size/S

#1790 drop connectors
  towhee/__init__.py
  towhee/command/develop.py
  towhee/command/execute.py
  towhee/connectors/__init__.py
  towhee/connectors/ann_index/__init__.py
  towhee/connectors/ann_index/base.py
  towhee/connectors/ann_index/milvus.py
  towhee/utils/thirdparty/av_utils.py
  towhee/utils/thirdparty/pyarrow.py
Labels: lgtm, size/L, approved

#1793 fix comment of SpaceTimeTransformer.
  towhee/models/frozen_in_time/frozen_video_transformer.py
Labels: lgtm, approved, size/M

#1797 fix docstring for vit of clip
  towhee/models/clip/clip.py
Labels: lgtm, approved, size/S

#1798 optimize frozen in time construction input info.
  towhee/models/frozen_in_time/frozen_in_time.py
Labels: lgtm, approved, size/M

#1799 fix comment of VitModel.
  towhee/models/vit/vit.py
Labels: lgtm, approved, size/M

#1794 improve codecov
  towhee/functional/mixins/audio.py
  towhee/functional/mixins/compile.py
  towhee/functional/mixins/computer_vision.py
  towhee/utils/thirdparty/faiss_utils.py
  towhee/utils/thirdparty/milvus_utils.py
Labels: lgtm, approved, size/S

#1800 add docstring for clip extended input
  towhee/models/clip/clip.py
Labels: lgtm, approved, size/S

#1796 Move benchmark to root dir
  benchmark/DataCollection-Arrow.ipynb
  benchmark/benchmark_ray_backend.py
  benchmark/benchmark_report.ipynb
Labels: lgtm, approved, size/XS

#1795 Add docstring for TAggregate in ActionClip
  towhee/models/action_clip/visual_prompt.py
Labels: lgtm, approved, size/S

#1804 Add ut for ActionClip visual prompt (different heads)
  tests/unittests/models/action_clip/test_prompt.py
Labels: lgtm, approved, size/M, component/models

#1805 Add docstring for ActionCLIP model
  towhee/models/action_clip/action_clip.py
Labels: lgtm, approved, size/S

#1803 add no cover to display mixin
  towhee/functional/mixins/display.py
Labels: lgtm, approved, size/S

#1801 Add test run in DC
  tests/unittests/functional/test_data_collection.py
Labels: lgtm, approved, size/XS

#1752 doc updates for entity.
  towhee/functional/entity.py
Labels: lgtm, size/L, approved

#1785 init comments
  towhee/__init__.py
Labels: lgtm, approved, size/XS

#1787 AtomicCount comments
  towhee/utils/atomic_count.py
Labels: lgtm, approved, size/S

#1788 Singleton comments.
  towhee/utils/singleton.py
Labels: lgtm, approved, size/XS

#1806 Update docstring
  towhee/functional/data_collection.py
Labels: lgtm, approved, size/XS

#1792 fix hub_operators path
  .github/workflows/weekly_ci.yml
  tests/testcases/hub/execute_hub_operators.py
Labels: lgtm, approved, size/XS

#1808 Remove mock concat_operator
  tests/unittests/mock_operators/concat_operator/__init__.py
Labels: lgtm, approved, size/S

#1813 fix comment of MaxViTTransformerBlock.
  towhee/models/max_vit/max_vit_block.py
Labels: lgtm, approved, size/M

#1807 Add cm test in metricmixin
  towhee/functional/mixins/metric.py
Labels: lgtm, approved, size/XS

#1810 mock_generator_op support serve
  tests/unittests/mock_operators/generator_operator/__init__.py
  tests/unittests/mock_operators/generator_operator/generator_operator.py
Labels: lgtm, approved, size/XS

#1757 Move from_df to dataset mixin
  tests/unittests/functional/test_pandas.py
  towhee/functional/__init__.py
  towhee/functional/mixins/dataset.py
Labels: lgtm, approved, size/S

#1809 Mock op zero_drop support serve
  tests/unittests/mock_operators/zero_drop/__init__.py
  tests/unittests/mock_operators/zero_drop/zero_drop.py
Labels: lgtm, approved, size/S

#1812 add mpvit MHCAEncoder init args infos.
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/S

#1817 add docstring for clip4clip
  towhee/models/clip4clip/clip4clip.py
Labels: lgtm, approved, size/S

#1802 Merge plot and matplotlib utils
  towhee/utils/matplotlib_utils.py
  towhee/utils/plot_utils.py
Labels: lgtm, size/L, approved

#1814 Add ut for cache path
  tests/unittests/hub/test_file_manager.py
Labels: lgtm, approved, size/XS

#1779 [Serve] Triton support Generator model
  tests/unittests/mock_operators/generator_with_timestamp/__init__.py
  tests/unittests/mock_operators/generator_with_timestamp/generator_with_timestamp.py
  tests/unittests/triton/bls/model_runner/generator_model_config.json
  tests/unittests/triton/bls/model_runner/test_generator_model.py
  towhee/serve/triton/bls/caller/local_caller.py
  towhee/serve/triton/bls/mock/mock_pb_util.py
  towhee/serve/triton/bls/mock/mock_triton_client.py
  towhee/serve/triton/bls/model_runner/generator_model.py
Labels: lgtm, size/L, approved

#1820 range bugfix
  towhee/functional/__init__.py
Labels: lgtm, approved, size/XS

#1821 add mpvit class docstr.
  towhee/models/mpvit/mpvit.py
Labels: lgtm, approved, size/S

#1823 fix comment of vit block.
  towhee/models/vit/vit_block.py
Labels: lgtm, approved, size/M

#1828 fix comment for Coformer.
  towhee/models/coformer/coformer.py
Labels: lgtm, approved, size/S

#1829 Update style guide
  STYLE_GUIDE.md
Labels: lgtm, approved, size/XS

#1824 Add ut for ActionClip map_state_dict (cover more cases)
  tests/unittests/models/action_clip/test_utils.py
Labels: lgtm, approved, size/S, component/models

#1825 Add docstring for ResidualAttentionBlock in ActionClip
  towhee/models/action_clip/visual_prompt.py
Labels: lgtm, approved, size/S

#1826 Add docstring for modified SlowFast in AcarNet
  towhee/models/acar_net/backbone.py
Labels: lgtm, approved, size/S

#1832 support load global/local function as operator
  towhee/engine/factory.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/dispatcher.py
Labels: lgtm, approved, size/M

#1827 Remove ruamel.yaml from requirements
  requirements.txt
  tests/unittests/utils/test_yaml_utils.py
  towhee/utils/yaml_utils.py
Labels: lgtm, approved, size/S

#1833 Mock flat op support serve
  tests/unittests/mock_operators/flat_operator/flat_operator.py
Labels: lgtm, approved, size/XS

#1834 add unit test for new towhee dispatcher
  tests/unittests/functional/test_dispatcher.py
Labels: lgtm, approved, size/M

#1836 Add no cover in cmd
  towhee/command/repo.py
  towhee/command/user.py
Labels: lgtm, approved, size/XS

#1838 Add license
  tests/__init__.py
Labels: lgtm, approved, size/S

#1835 mock repeat op support serve
  tests/unittests/mock_operators/repeat_operator/repeat_operator.py
Labels: lgtm, approved, size/XS

#1831 Remove mock cv2_decoder
  tests/unittests/mock_operators/cv2_decoder/__init__.py
  tests/unittests/mock_operators/cv2_decoder/cv2_decoder.py
  tests/unittests/mock_operators/cv2_decoder/test_cv2_decoder.py
  tests/unittests/mock_operators/cv2_decoder/test_video.avi
Labels: lgtm, approved, size/M

#1839 Update test mixins
  tests/unittests/functional/test_mixins.py
Labels: lgtm, approved, size/S

#1840 drop unused code
  tests/unittests/utils/test_handler_mixin.py
  towhee/utils/__init__.py
  towhee/utils/atomic_count.py
  towhee/utils/handler_mixin.py
Labels: lgtm, size/L, approved

#1837 add mvit relprop function arg infos.
  towhee/models/multiscale_vision_transformers/mvit.py
Labels: lgtm, approved, size/XS

#1815 add dag control plane doc
  towhee/functional/mixins/dag.py
Labels: lgtm, approved, size/XS

#1816 add some test
  tests/testcases/test_dag_info.py
Labels: lgtm, approved, size/S

#1830 Remove sklearn from test_req to test import
  .github/workflows/codecov.yml
  test_requirements.txt
  towhee/utils/sklearn_utils.py
Labels: lgtm, approved, size/XS

#1842 fix comment of Coformer forward.
  towhee/models/coformer/coformer.py
Labels: lgtm, approved, size/S

#1844 add net_vlad docstring
  towhee/models/collaborative_experts/net_vlad.py
Labels: lgtm, approved, size/XS

#1843 add vit relprop method infos.
  towhee/models/vit/vit.py
Labels: lgtm, approved, size/XS
