Repository towhee-io/towhee, pull requests merged in 2022-02, with the labels that each got.

#534 Add pipeline overview
  docs/developer-guides/framework/pipeline-overview.md
  docs/sidebars.js
Labels: lgtm, size/L, approved

#535 Fix image util annotations
  towhee/utils/ndarray_utils.py
  towhee/utils/pil_utils.py
Labels: lgtm, approved, size/S

#545 Add interface of image embedding pipeline
  towhee/pipeline/base.py
  towhee/pipeline/image_embedding_pipeline.py
Labels: lgtm, approved, size/M

#544 v1.2 dev towhee docs update
  docs/get-started/quick-start.mdx
  docs/get-started/troubleshooting.md
  docs/sidebars.js
Labels: lgtm, approved, size/S

#546 support old towhee repo
  towhee/__init__.py
  towhee/dag/base_repr.py
  towhee/engine/__init__.py
  towhee/engine/operator_loader.py
  towhee/engine/operator_registry.py
  towhee/hub/subcmds/develop.py
  towhee/hub/subcmds/execute.py
Labels: size/L

#549 Support towhee.op()
  towhee/__init__.py
  towhee/engine/operator_loader.py
Labels: lgtm, size/M

#548 New hub merge main
  docs/developer-guides/framework/pipeline-overview.md
  docs/get-started/quick-start.mdx
  docs/get-started/troubleshooting.md
  docs/sidebars.js
  tests/unittests/hub/test_file_manager.py
  tests/unittests/hub/test_hub_tools.py
  towhee/engine/operator_loader.py
  towhee/hub/bin/hub_tools.py
  towhee/pipeline/base.py
  towhee/pipeline/image_embedding_pipeline.py
  towhee/utils/ndarray_utils.py
  towhee/utils/pil_utils.py
Labels: size/L

#539 Update architecture overview
  docs/developer-guides/framework/architectural-overview.md
  docs/developer-guides/framework/architecture-overview.md
  docs/developer-guides/framework/engine-details.md
  docs/developer-guides/framework/hub-integration-and-caching.md
  docs/developer-guides/framework/pipeline-overview.md
  docs/developer-guides/models/layers-overview.md
  docs/developer-guides/models/swin_arch.png
  docs/sidebars.js
Labels: lgtm, size/L, approved

#537 Improve pipeline docs
  docs/operators/image-loading-and-transforms.md
  docs/operators/model-based-operators.md
  docs/pipelines/audio-embedding.md
  docs/sidebars.js
Labels: lgtm, approved, size/M

#551 refactor saver and loader
  tests/unittests/trainer/test_weights.py
  towhee/operator/base.py
  towhee/trainer/modelcard.py
  towhee/trainer/trainer.py
  towhee/trainer/utils/load_weights.py
  towhee/trainer/utils/save_weights.py
  towhee/trainer/utils/trainer_utils.py
Labels: lgtm, size/L, approved

#559 Fix unittest
  requirements.txt
  towhee/dag/base_repr.py
Labels: lgtm, approved, size/XS

#560 Update towhee version and delete tests for offline pipeline
  tests/testcases/requirements.text
  tests/testcases/test_image_object_embedding.py
  tests/testcases/test_main.py
Labels: lgtm, size/L, approved

#553 merge `new_hub` to `main`
  docs/developer-guides/cmdline.md
  requirements.txt
  setup.py
  tests/unittests/hub/bin/test_hub_tools.py
  towhee/__init__.py
  towhee/dag/base_repr.py
  towhee/engine/__init__.py
  towhee/engine/operator_loader.py
  towhee/engine/operator_registry.py
  towhee/hub/cmdline.py
  towhee/hub/subcmds/__init__.py
  towhee/hub/subcmds/develop.py
  towhee/hub/subcmds/execute.py
Labels: lgtm, approved, size/XL

#567 Update hub URLs
  tests/unittests/hub/test_repo_manager.py
  towhee/hub/file_manager.py
  towhee/hub/pipeline_manager.py
  towhee/hub/repo_manager.py
  towhee/utils/git_utils.py
  towhee/utils/hub_utils.py
Labels: lgtm, approved, size/S

#569 add hyperparameter
  requirements.txt
  towhee/__init__.py
  towhee/dag/base_repr.py
  towhee/engine/operator_loader.py
  towhee/hparam/__init__.py
  towhee/hparam/hyperparameter.py
  towhee/hub/subcmds/execute.py
Labels: lgtm, approved, size/XL

#570 Refactor ViT model
  tests/unittests/mock_operators/pytorch_transformer_operator/__init__.py
  tests/unittests/mock_operators/pytorch_transformer_operator/pytorch_transformer_operator.py
  tests/unittests/mock_operators/pytorch_transformer_vec_operator/__init__.py
  tests/unittests/mock_operators/pytorch_transformer_vec_operator/pytorch_transformer_vec_operator.py
  tests/unittests/models/vit/test_vision_transformer.py
  tests/unittests/operators/test_pytorch_transformer_operator.py
  tests/unittests/operators/test_pytorch_transformer_vec_operator.py
  tests/unittests/trainer/test_transformer.py
  tests/unittests/trainer/test_vit_configs.py
  tests/unittests/trainer/test_vit_pretrained.py
  towhee/models/layers/multi_head_attention.py
  towhee/models/layers/vit_block.py
  towhee/models/vit/__init__.py
  towhee/models/vit/vit.py
  towhee/models/vit/vit_utils.py
  towhee/trainer/models/vit/transformer.py
  towhee/trainer/models/vit/vit.py
  towhee/trainer/models/vit/vit_configs.py
  towhee/trainer/models/vit/vit_pretrained.py
  towhee/trainer/models/vit/vit_training_utils.py
Labels: lgtm, approved, size/XXL

#562 Modify filemanger test
  tests/unittests/hub/test_file_manager.py
Labels: lgtm, size/XS

#555 Update download in ut
  tests/unittests/hub/test_repo_manager.py
Labels: lgtm, size/XS

#573 Add ut to test op func
  tests/unittests/engine/test_op.py
Labels: lgtm, size/M

#577 add load from yaml interface for training_config
  tests/unittests/trainer/config.yaml
  tests/unittests/trainer/test_trainingargs.py
  towhee/trainer/training_config.py
Labels: lgtm, size/L, approved

#572 Add utils to normalize repo
  tests/unittests/utils/test_repo_normalize.py
  towhee/utils/repo_normalize.py
Labels: lgtm, size/L

#579 Update towhee version
  tests/testcases/requirements.text
Labels: lgtm, approved, size/XS

#582 add save to yaml interface for training_config
  tests/unittests/trainer/save_test.yaml
  tests/unittests/trainer/test_trainingargs_saving.py
  towhee/trainer/training_config.py
Labels: lgtm, size/L, approved

#583 Allow operator to resume training
  tests/unittests/trainer/test_trainer.py
  towhee/operator/base.py
  towhee/trainer/trainer.py
  towhee/trainer/utils/trainer_utils.py
Labels: lgtm, size/L, approved

#586 move builtin templates to `towhee.hub`
  towhee/hub/builtin/__init__.py
  towhee/hub/builtin/pipelines/__init__.py
  towhee/hub/builtin/pipelines/image_embedding_template.yaml
  towhee/hub/builtin/pipelines/template_test.yaml
  towhee/hub/file_manager.py
Labels: lgtm, approved, size/XS

#589 cpu, gpu, multi gpu training framework
  tests/unittests/trainer/test_trainer.py
  towhee/operator/base.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, size/L, approved

#592 add callback in trainer.
  towhee/data/__init__.py
  towhee/data/dataset/__init__.py
  towhee/data/dataset/image_datasets.py
  towhee/data/random_erase.py
  towhee/trainer/callback.py
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/M, component/trainer

#596 optimize code and user experience
  tests/unittests/trainer/config.yaml
  tests/unittests/trainer/save_test.yaml
  tests/unittests/trainer/test_args.py
  tests/unittests/trainer/test_trainer.py
  tests/unittests/trainer/test_weights.py
  towhee/trainer/callback.py
  towhee/trainer/modelcard.py
  towhee/trainer/optimization/optimization.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
  towhee/trainer/utils/logging.py
  towhee/utils/log.py
Labels: lgtm, approved, size/XXL

#594 Refactor towhee cmdline tool
  setup.py
  tests/unittests/command/__init__.py
  tests/unittests/command/test_cmdline.py
  towhee/command/README.md
  towhee/command/__init__.py
  towhee/command/cmdline.py
  towhee/command/develop.py
  towhee/command/execute.py
  towhee/engine/operator_loader.py
Labels: lgtm, size/L, approved

#599 Develop content of ModelCard
  tests/unittests/trainer/test_trainer.py
  towhee/trainer/modelcard.py
  towhee/trainer/trainer.py
  towhee/trainer/training_summary.py
Labels: lgtm, approved, size/M

#595 Improve README clarity
  README.md
Labels: lgtm, approved, size/S

#593 Add TimeWindow reader
  tests/unittests/engine/operator_io/test_reader.py
  tests/unittests/engine/test_pipeline.py
  tests/unittests/mock_operators/generator_with_timestamp/__init__.py
  tests/unittests/mock_operators/generator_with_timestamp/generator_with_timestamp.py
  tests/unittests/test_util/test_time_window/test_time_window.yaml
  tests/unittests/test_util/test_timestamp/test_timestamp.yaml
  towhee/engine/operator_io/__init__.py
  towhee/engine/operator_io/reader.py
  towhee/engine/operator_runner/__init__.py
  towhee/engine/operator_runner/generator_runner.py
  towhee/types/_frame.py
Labels: lgtm, approved, component/engine, size/XL

#600 add operator ir and operator lazy loading
  tests/unittests/pipelines/test_pipeline_ops.py
  towhee/__init__.py
  towhee/dag/operator_repr.py
  towhee/hparam/hyperparameter.py
Labels: lgtm, size/L, approved

#591 add image embedding pipeline
  tests/unittests/pipelines/test_image_embedding_pipeline.py
  towhee/__init__.py
  towhee/dag/graph_repr.py
  towhee/engine/pipeline.py
  towhee/hub/builtin/pipelines/image_embedding_template_1.yaml
  towhee/hub/builtin/pipelines/image_embedding_template_2.yaml
  towhee/hub/builtin/pipelines/image_embedding_template_3.yaml
  towhee/pipeline/image_embedding_pipeline.py
  towhee/pipelines/__init__.py
  towhee/pipelines/base.py
  towhee/pipelines/image_embedding_pipeline.py
Labels: lgtm, size/L, approved

#607 add `towhee.pipes` for pipeline templates
  tests/unittests/pipelines/test_pipeline_pipes.py
  towhee/__init__.py
Labels: lgtm, approved, size/M

#601 optimize the loss and optimizer setup and support construct parameters ability.
  tests/unittests/trainer/save_test.yaml
  tests/unittests/trainer/test_trainingargs.py
  tests/unittests/trainer/test_trainingargs_saving.py
  towhee/trainer/metrics.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, size/L, approved

#610 Generate mean loss value for trainer
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/M

#611 custom loss and optimizer ability, optimize the trainer instantiating in op.
  tests/unittests/trainer/test_scheduler.py
  tests/unittests/trainer/test_trainer.py
  towhee/operator/base.py
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/M

#615 Add set_all to layer_freezer
  tests/unittests/trainer/test_freezer.py
  towhee/trainer/utils/layer_freezer.py
Labels: lgtm, approved, size/S

#617 Support towhee user config
  tests/unittests/utils/test_hub_file_utils.py
  towhee/command/cmdline.py
  towhee/command/develop.py
  towhee/command/user.py
  towhee/utils/hub_file_utils.py
  towhee/utils/hub_utils.py
Labels: lgtm, size/L, approved

#622 refactor model card
  tests/unittests/trainer/test_trainer.py
  tests/unittests/trainer/test_weights.py
  towhee/trainer/modelcard.py
  towhee/trainer/trainer.py
Labels: lgtm, size/L, approved

#623 add earlystopping and modelcheckpoint callback.
  towhee/trainer/callback.py
Labels: lgtm, size/L, approved

#616 add model alias support in image embedding pipeline
  tests/unittests/pipelines/test_image_embedding_pipeline.py
  towhee/__init__.py
  towhee/hub/builtin/pipelines/image_embedding_template_2.yaml
  towhee/hub/builtin/pipelines/image_embedding_template_3.yaml
  towhee/pipelines/alias_resolvers.py
  towhee/pipelines/image_embedding_pipeline.py
Labels: lgtm, size/L

#625 progressbar, print callback and optimize the train loop structure.
  tests/unittests/trainer/save_test.yaml
  tests/unittests/trainer/test_args.py
  tests/unittests/trainer/test_trainer.py
  tests/unittests/trainer/test_trainingargs_saving.py
  tests/unittests/trainer/test_weights.py
  towhee/operator/base.py
  towhee/trainer/loss.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
  towhee/trainer/utils/trainer_utils.py
Labels: lgtm, size/L, approved

#620 Add df gc
  tests/unittests/__init__.py
  tests/unittests/dataframe/test_dataframe.py
  tests/unittests/engine/operator_io/test_reader.py
  tests/unittests/engine/test_graph_context.py
  towhee/dataframe/dataframe.py
  towhee/engine/engine.py
  towhee/engine/graph_context.py
  towhee/engine/operator_io/reader.py
  towhee/engine/task_scheduler.py
  towhee/utils/atomic_count.py
Labels: lgtm, size/L, approved, component/engine, component/dataframe

#627 fix tensorboard import
  tests/unittests/trainer/save_test.yaml
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/S

#629 Modify image embedding pipeline test cache dir
  tests/unittests/command/test_cmdline.py
  tests/unittests/engine/test_pipeline.py
  tests/unittests/pipelines/test_image_embedding_pipeline.py
  towhee/pipelines/image_embedding_pipeline.py
Labels: lgtm, size/L, approved

#630 fix progress bar problem.
  tests/unittests/trainer/save_test.yaml
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/M

#631 Add repo command line
  tests/unittests/command/test_cmdline.py
  towhee/command/README.md
  towhee/command/cmdline.py
  towhee/command/develop.py
  towhee/command/execute.py
  towhee/command/repo.py
  towhee/command/user.py
  towhee/hub/operator_manager.py
  towhee/hub/pipeline_manager.py
Labels: lgtm, size/XL

#633 bugfix for metrics construction.
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/XS

#634 Enable updated ModelCard in trainer
  towhee/trainer/modelcard.py
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/M, component/trainer

#636 add tag to repo
  towhee/utils/hub_utils.py
Labels: lgtm, approved, size/M

#628 update doc for image embedding piepline
  towhee/__init__.py
  towhee/pipelines/image_embedding_pipeline.py
Labels: lgtm, size/L, approved

#638 Update README for cmdline
  towhee/command/README.md
Labels: lgtm, size/XS

#626 Add yaml utils
  requirements.txt
  test_requirements.txt
  tests/unittests/utils/test_yaml_utils.py
  towhee/utils/yaml_utils.py
Labels: lgtm, size/L, approved

#639 Optimize calculation of loss & metric in trainer
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/M, component/trainer

#644 bugfix for mean metric update.
  towhee/trainer/metrics.py
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/S

#647 integrate and optimize callbacks
  tests/unittests/trainer/save_test.yaml
  towhee/operator/base.py
  towhee/trainer/callback.py
  towhee/trainer/scheduler.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
  towhee/trainer/utils/trainer_utils.py
Labels: lgtm, approved, size/XL

#648 multi gpu ability and some code structure adjustment.
  tests/unittests/data/test_random_erase.py
  tests/unittests/data/test_video_info.py
  tests/unittests/trainer/save_test.yaml
  tests/unittests/trainer/test_trainer.py
  towhee/data/dataset/dataset.py
  towhee/data/random_erase.py
  towhee/data/video_info.py
  towhee/trainer/callback.py
  towhee/trainer/dataset.py
  towhee/trainer/modelcard.py
  towhee/trainer/towheemodel.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, size/L, approved

#654 Add key_frame attr to image
  tests/unittests/types/test_image.py
  towhee/types/image.py
Labels: lgtm, approved, component/engine, size/S

#643 Replace PyYaml with yaml utils
  requirements.txt
  test_requirements.txt
  tests/unittests/dag/test_repr.py
  tests/unittests/hub/test_operator_manager.py
  tests/unittests/pipelines/test_pipeline_template.py
  towhee/dag/base_repr.py
  towhee/hub/operator_manager.py
  towhee/pipelines/image_embedding_pipeline.py
Labels: lgtm, size/M

#660 Clarify README
  README.md
Labels: lgtm, approved, size/XS

#661 modify callback ut.
  tests/unittests/trainer/test_callback.py
  towhee/operator/base.py
Labels: lgtm, approved, size/M

#662 Add set_slice & show_freezed_layers to layer_freezer
  tests/unittests/trainer/test_freezer.py
  towhee/trainer/utils/layer_freezer.py
Labels: lgtm, approved, size/M, component/trainer

#666 add unittest and type annotation for callbacks.
  tests/unittests/trainer/test_callback.py
  towhee/trainer/callback.py
  towhee/trainer/trainer.py
Labels: lgtm, size/L, approved

#659 PoC of DataCollection API
  tests/unittests/functional/__init__.py
  tests/unittests/functional/test_data_collection.py
  towhee/engine/operator_registry.py
  towhee/engine/operator_runner/runner_base.py
  towhee/functional/__init__.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/data_source.py
  towhee/functional/mixins/dispatcher.py
  towhee/functional/option.py
Labels: lgtm, approved, size/XL

#678 Fix lr with resumed trainer
  towhee/trainer/callback.py
  towhee/trainer/optimization/optimization.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, size/L, approved, component/trainer

#680 support more types which can be transfered to gpus.
  towhee/trainer/trainer.py
  towhee/trainer/utils/trainer_utils.py
Labels: lgtm, approved, size/M

#681 Add option to completely freeze BatchNorm layers
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/S, component/trainer

#682 Add final save at the end of train
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/M, component/trainer

#676 support parallel execution in data collection
  tests/unittests/functional/test_data_collection.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/dispatcher.py
  towhee/functional/mixins/parallel.py
Labels: lgtm, size/L, approved

#684 Add numpy dep
  requirements.txt
Labels: lgtm, approved, size/XS

#685 modify compute loss and metric struct so that Trainer can be custom by users.
  tests/unittests/trainer/save_test.yaml
  towhee/trainer/metrics.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/M

#688 refactor lr scheduler configuration
  tests/unittests/trainer/config2.yaml
  tests/unittests/trainer/test_config_lr_shceduler.py
  towhee/trainer/trainer.py
Labels: lgtm, size/L, approved

#690 Fix typo in ModelCard
  towhee/trainer/modelcard.py
Labels: lgtm, approved, size/XS

#691 fix evalatue problems
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/S

#693 Fix option to freeze BN layers
  towhee/trainer/modelcard.py
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/S, component/trainer

#694 Optimizer model card
  towhee/operator/base.py
  towhee/trainer/modelcard.py
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/M

#695 add eval_epoch strategy in evaluate_step.
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/XS

#699 Optimize code to calculate lr
  tests/unittests/trainer/test_config_lr_scheduler.py
  towhee/trainer/optimization/optimization.py
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/S, component/trainer

#689 Add extra requirements for python<3.7
  requirements.txt
  setup.py
  towhee/hub/file_manager.py
Labels: lgtm, size/S

#701 remove redundant printing
  tests/unittests/trainer/test_config_lr_scheduler.py
Labels: lgtm, approved, size/XS

#705 support operator level parallel execution
  tests/unittests/functional/test_data_collection.py
  tests/unittests/functional/test_parallel.py
  towhee/__init__.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/parallel.py
Labels: lgtm, size/L, approved

#708 take apart the model from states when saving and loading and modify the dataset() position
  tests/unittests/trainer/test_weights.py
  towhee/__init__.py
  towhee/data/dataset/dataset.py
  towhee/trainer/__init__.py
  towhee/trainer/trainer.py
  towhee/trainer/utils/trainer_utils.py
Labels: lgtm, approved, size/M

#711 fix spell error in progressbar callback
  towhee/trainer/callback.py
Labels: lgtm, approved, size/XS

#714 refactor examples for scheduler
  towhee/trainer/scheduler.py
Labels: lgtm, size/L, approved

#709 Fix ruamel dependency issue in python 3.6 and coverage test
  requirements.txt
  setup.py
  test_requirements.txt
Labels: lgtm, size/S

#713 remove useless callbacks interface params and config params.
  towhee/trainer/callback.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/M

#716 make retinaface can be inferenced on gpu.
  towhee/models/retina_face/retinaface.py
Labels: lgtm, approved, size/S
