Repository towhee-io/towhee, pull requests merged in 2022-03, with the labels that each got.

#717 remove pytorch from dependency
  towhee/operator/base.py
Labels: lgtm, approved, size/XS

#720 Optimize and add docstring to layer_freezer
  tests/unittests/trainer/test_freezer.py
  towhee/trainer/utils/layer_freezer.py
Labels: lgtm, size/L, approved, component/trainer

#721 Add docstring to modelcard
  towhee/trainer/modelcard.py
  towhee/trainer/utils/layer_freezer.py
Labels: lgtm, approved, size/M, component/trainer

#722 refactor docstring for training_config.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/M

#724 fix type issue for docstring of training_config.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/M

#723 Update docstring
  towhee/trainer/modelcard.py
  towhee/trainer/utils/layer_freezer.py
Labels: lgtm, approved, size/S

#725 fix type issue for docstring of scheduler.py
  towhee/trainer/scheduler.py
Labels: lgtm, approved, size/M

#729 fix docstring in metrics.py
  towhee/trainer/metrics.py
Labels: lgtm, approved, size/XS

#730 fix return type absense in docstring of scheduler.py
  towhee/trainer/scheduler.py
Labels: lgtm, approved, size/S

#731 trainer docstring.
  tests/unittests/trainer/save_test.yaml
  tests/unittests/trainer/test_callback.py
  towhee/__init__.py
  towhee/trainer/callback.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, size/L, approved

#719 Fix typo in README
  README.md
Labels: lgtm, approved, size/XS

#727 Add data source in datacollection
  towhee/functional/data_collection.py
  towhee/functional/mixins/data_source.py
  towhee/utils/ndarray_utils.py
  towhee/utils/pil_utils.py
Labels: lgtm, approved, size/M

#737 add docstring for callback.
  towhee/trainer/callback.py
Labels: lgtm, size/L, approved

#739 optimize the train in base.py and add docstrings.
  tests/unittests/trainer/test_trainer.py
  towhee/__init__.py
  towhee/operator/base.py
  towhee/trainer/trainer.py
Labels: lgtm, size/L, approved

#736 add get started doc for dc
  docs/get-started/data-collection.md
Labels: lgtm, size/L, approved

#744 change default dataloader_num_workers to 0.
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/XS

#734 1.0 DOCS added gsoc page
  docs/get-started/Gsoc.MD
  docs/sidebars.js
Labels: lgtm, size/L, approved

#750 support video mixin; support multi-output
  towhee/functional/data_collection.py
  towhee/functional/mixins/computer_vision.py
  towhee/functional/mixins/data_source.py
  towhee/functional/mixins/parallel.py
Labels: lgtm, size/L, approved

#743 Op scheduler
  towhee/engine/engine.py
  towhee/engine/graph_context.py
  towhee/engine/operator_context.py
  towhee/engine/operator_io/writer.py
  towhee/engine/operator_runner/generator_runner.py
  towhee/engine/operator_runner/runner_base.py
  towhee/engine/task_scheduler.py
Labels: lgtm, approved, size/M

#752 Add sphinx to automatically create API-doc for trainer
  towhee/doc/Makefile
  towhee/doc/make.bat
  towhee/doc/source/_templates/autosummaryclass.rst
  towhee/doc/source/_templates/layout.html
  towhee/doc/source/conf.py
  towhee/doc/source/index.rst
  towhee/doc/source/trainer/modules.rst
  towhee/doc/source/trainer/trainer.optimization.rst
  towhee/doc/source/trainer/trainer.rst
  towhee/doc/source/trainer/trainer.utils.rst
  towhee/trainer/modelcard.py
Labels: type/doc, lgtm, size/L, approved, component/trainer

#749 Add warning in load_src
  towhee/utils/yaml_utils.py
Labels: lgtm, approved, size/XS

#755 Fix auto-generation of API-Doc for trainer
  towhee/doc/source/conf.py
Labels: lgtm, approved, component/trainer, size/XS, type/api-doc

#758 fix the docstring in callback and metrics.
  towhee/trainer/callback.py
  towhee/trainer/metrics.py
Labels: lgtm, approved, size/S

#757 Add plot for towhee and show with Datacollection
  towhee/__init__.py
  towhee/functional/data_collection.py
  towhee/utils/ndarray_utils.py
  towhee/utils/plot_utils.py
  towhee/utils/repo_normalize.py
Labels: lgtm, size/L, approved

#763 update doc for dc; move normalize to cv mixin
  docs/get-started/data-collection.md
  towhee/functional/data_collection.py
  towhee/functional/mixins/computer_vision.py
Labels: lgtm, approved, size/M

#764 Fix API-doc with dataclass in modules
  towhee/doc/source/trainer/trainer.rst
  towhee/trainer/modelcard.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/M, type/api-doc

#765 block multi gpu feature.
  tests/unittests/trainer/save_test.yaml
  towhee/trainer/modelcard.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/M

#766 Optimize examples in docstring
  towhee/trainer/modelcard.py
  towhee/trainer/utils/layer_freezer.py
Labels: lgtm, approved, size/M, type/api-doc

#767 Update release version
  setup.py
Labels: lgtm, approved, size/XS

#769 1.1 DOC added a dublicate music recognitioin tutorial
  docs/sidebars.js
  docs/tutorials/image-deduplication2.md
Labels: lgtm, approved, size/M

#759 Exclude tests when install towhee from setup.py
  setup.py
Labels: lgtm, size/XS

#760 Moving FileManager logic to init
  tests/unittests/__init__.py
  tests/unittests/engine/test_engine.py
  tests/unittests/engine/test_graph_context.py
  tests/unittests/engine/test_operator_context.py
  tests/unittests/engine/test_operator_pool.py
  tests/unittests/engine/test_pipeline.py
  tests/unittests/engine/test_thread_pool_task_executor.py
  tests/unittests/hub/test_download.py
Labels: lgtm, size/L, approved

#753 Delete outdated readme in hub/bin
  towhee/hub/bin/README.md
Labels: lgtm, size/L, approved

#770 Fix doc sidebars
  docs/developer-guides/framework/pipeline-overview.md
  docs/get-started/Gsoc.MD
  docs/get-started/troubleshooting.md
  docs/sidebars.js
Labels: lgtm, approved, size/M

#771 quick start training doc
  docs/training-guides/train-operators/1_quick_start_training.md
Labels: lgtm, approved, size/M

#773 Add ruamel into test_req
  test_requirements.txt
Labels: lgtm, approved, size/XS

#772 Update version and remove tests/docs/tutorials from source package
  MANIFEST.in
  setup.py
Labels: lgtm, approved, size/XS

#776 add sidebars.
  docs/fine-tuning/train-operators/1_quick_start_training.md
  docs/sidebars.js
Labels: lgtm, approved, size/S

#775 Fix docs filename
  docs/get-started/Gsoc-2022.md
Labels: lgtm, approved, size/XS

#779 Fix broken links
  docs/developer-guides/framework/architecture-overview.md
  docs/get-started/Gsoc-2022.md
Labels: lgtm, approved, size/XS

#780 add some training examples
  docs/fine-tuning/train-operators/2_train_on_mnist.md
  docs/fine-tuning/train-operators/2_train_on_mnist_files/2_train_on_mnist_6_0.png
  docs/fine-tuning/train-operators/3_read_configs_from_yaml.md
  docs/fine-tuning/train-operators/4_fine_tune_from_image_net.md
  docs/fine-tuning/train-operators/4_fine_tune_from_image_net_files/4_fine_tune_from_image_net_9_1.png
  docs/sidebars.js
Labels: lgtm, size/L, approved

#778 Remove create cache function in setup.py
  setup.py
Labels: lgtm, size/XS

#784 Optimize web-doc for trainer
  docs/fine-tune/train-operators/bird_image.png
  docs/fine-tune/train-operators/mnist_example.png
  docs/fine-tune/train-operators/quick_start_training.md
  docs/fine-tune/train-operators/train_on_imagenet.md
  docs/fine-tune/train-operators/train_on_mnist.md
  docs/fine-tune/train-operators/training_configs.md
  docs/fine-tuning/train-operators/3_read_configs_from_yaml.md
  docs/sidebars.js
Labels: type/doc, lgtm, size/L, approved

#785 Fix broken titles in docs
  docs/fine-tune/train-operators/train_on_imagenet.md
  docs/fine-tune/train-operators/train_on_mnist.md
Labels: lgtm, approved, size/XS

#786 Update docs of trainer steps
  docs/fine-tune/train-operators/quick_start_training.md
  docs/fine-tune/train-operators/train_on_imagenet.md
  docs/fine-tune/train-operators/train_on_mnist.md
  docs/fine-tune/train-operators/training_configs.md
Labels: type/doc, lgtm, approved, size/XS

#787 Fix mail link
  docs/get-started/Gsoc-2022.md
Labels: lgtm, approved, size/XS

#788 Remove duplicate tutorial
  docs/tutorials/image-deduplication2.md
Labels: lgtm, approved, size/M

#790 chage os.path to pathlib
  towhee/trainer/modelcard.py
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/S

#791 Fix duplicate sidebar link
  docs/sidebars.js
Labels: lgtm, approved, size/XS

#792 rm save_test.yaml after ut.
  tests/unittests/trainer/save_test.yaml
  tests/unittests/trainer/test_trainingargs_saving.py
Labels: lgtm, approved, size/M

#605 Dataframe Docs
  docs/developer-guides/framework/dataframe-details.md
  docs/overview.md
Labels: lgtm, approved, size/M

#795 Dfv2 documentation
  docs/sidebars.js
Labels: lgtm, approved, size/XS

#781 df ordering
  tests/unittests/dataframe/test_dataframe_v2.py
  towhee/dataframe/dataframe.py
  towhee/engine/operator_runner/flatmap_runner.py
  towhee/engine/operator_runner/generator_runner.py
  towhee/types/_frame.py
Labels: lgtm, size/L, approved

#798 fix multi gpu problem.
  towhee/data/dataset/dataset.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
  towhee/trainer/utils/trainer_utils.py
Labels: lgtm, approved, size/M

#800 fix bug in test_sam.py
  tests/unittests/models/layers/test_sam.py
Labels: lgtm, approved, size/XS

#811 Fix invalid quick start link
  docs/get-started/quick-start.mdx
Labels: lgtm, approved, size/XS

#812 Add square logo
  towhee_logo_square.png
Labels: lgtm, approved, size/XS

#799 Create Entity class
  tests/unittests/functional/test_entity.py
  towhee/functional/entity.py
Labels: lgtm, size/M

#809 add operator registation
  tests/unittests/engine/test_operator_register.py
  tests/unittests/functional/test_data_collection.py
  towhee/engine/operator_registry.py
Labels: lgtm, size/L, approved

#803 Add new Image type
  tests/unittests/_types/__init__.py
  tests/unittests/_types/test_image.py
  towhee/_types/__init__.py
  towhee/_types/image.py
Labels: lgtm, size/L, approved

#815 add 3d window MSA layer for video task
  tests/unittests/models/layers/test_window_attention3d.py
  towhee/models/layers/window_attention3d.py
Labels: lgtm, size/L, approved

#783 support index parameters in call holder
  towhee/__init__.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/dispatcher.py
  towhee/hparam/hyperparameter.py
Labels: lgtm, size/L, approved

#819 op lazy training.
  towhee/__init__.py
Labels: lgtm, size/XS

#817 add some vis utils.
  test_requirements.txt
  tests/unittests/trainer/test_visualization_util.py
  towhee/trainer/utils/visualization.py
Labels: lgtm, size/L, approved

#823 possible fix for #805
  tests/unittests/engine/test_engine.py
  towhee/dataframe/dataframe.py
  towhee/engine/graph_context.py
  towhee/pipeline_format.py
Labels: lgtm, approved, size/M

#824 use the correct method to get lr to avoid warning.
  towhee/trainer/trainer.py
Labels: lgtm, approved, size/XS

#822 update docstring for dc
  .readthedocs.yaml
  towhee/doc/requirements.txt
  towhee/doc/source/conf.py
  towhee/doc/source/data_collection/data_collection.rst
  towhee/doc/source/data_collection/option.rst
  towhee/functional/data_collection.py
  towhee/functional/mixins/__init__.py
  towhee/functional/option.py
Labels: lgtm, approved, size/XL

#828 add 3d swin transformer block for video task
  tests/unittests/models/layers/test_swin_transformer_block3d.py
  towhee/models/layers/swin_transformer_block3d.py
  towhee/models/utils/get_window_size.py
  towhee/models/utils/window_partition.py
  towhee/models/utils/window_reverse.py
Labels: lgtm, size/L, approved

#830 add show transform utils
  tests/unittests/trainer/test_visualization_util.py
  towhee/trainer/utils/visualization.py
Labels: lgtm, approved, size/M

#829 Add transforms for pretrained models in pytorchvideo
  test_requirements.txt
  tests/unittests/models/utils/test_video_transforms.py
  towhee/models/utils/video_transforms.py
Labels: lgtm, size/L, approved, component/models

#833 add video swin transformer block for video task
  tests/unittests/models/video_swin_transformer/test_video_swin_transformer_block.py
  towhee/models/video_swin_transformer/__init__.py
  towhee/models/video_swin_transformer/compute_mask.py
  towhee/models/video_swin_transformer/video_swin_transformer_block.py
Labels: lgtm, size/L, approved

#831 remove repeat training ut to speed up.
  tests/unittests/trainer/test_trainer.py
Labels: lgtm, approved, size/M

#836 repair sam unit test.
  tests/unittests/models/layers/test_sam.py
Labels: lgtm, approved, size/XS

#838 Upgrade deprecated packages (video transforms)
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/M, component/models

#840 Move mean & std to dict (video transforms by model name)
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/S, component/models

#835 Finish functional API ops draft
  tests/unittests/pipelines/test_pipeline_ops.py
  towhee/__init__.py
  towhee/functional/entity.py
  towhee/pipelines/alias_resolvers.py
Labels: lgtm, approved, size/M

#841 add plot lr utils.
  tests/unittests/trainer/test_visualization_util.py
  towhee/trainer/optimization/optimization.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
  towhee/trainer/utils/trainer_utils.py
  towhee/trainer/utils/visualization.py
Labels: lgtm, size/L, approved

#842 optimize plot utils ut.
  tests/unittests/trainer/test_visualization_util.py
  towhee/trainer/trainer.py
  towhee/trainer/utils/visualization.py
Labels: lgtm, approved, size/S

#848 add video swin transformer for video task
  tests/unittests/models/video_swin_transformer/test_video_swin_transformer.py
  towhee/models/video_swin_transformer/video_swin_transformer.py
Labels: lgtm, size/L, approved

#849 add reiase to owners
  OWNERS
Labels: lgtm, approved, size/XS

#844 Allow MIMO in ops
  tests/unittests/pipelines/test_pipeline_ops.py
  towhee/__init__.py
Labels: lgtm, size/M

#850 Mixin API for DC
  towhee/functional/mixins/dataset.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/feature_engine.py
  towhee/functional/mixins/metric.py
  towhee/functional/mixins/model_engine.py
Labels: lgtm, size/L, approved

#854 integrate captum .
  test_requirements.txt
  tests/unittests/trainer/test_visualization_util.py
  towhee/trainer/callback.py
  towhee/trainer/utils/file_utils.py
  towhee/trainer/utils/visualization.py
Labels: lgtm, size/L, approved

#855 Add default value for missing index in dc.iterable
  tests/unittests/functional/test_data_collection.py
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, approved, size/M

#864 Add type AudioFrame
  tests/unittests/types/test_audio_frame.py
  towhee/types/__init__.py
  towhee/types/audio_frame.py
Labels: lgtm, approved, size/M

#861 replace NNOperator.get_model() with self.model
  tests/unittests/trainer/test_trainer.py
  tests/unittests/trainer/test_weights.py
  towhee/operator/base.py
Labels: lgtm, approved, size/S

#868 support entity objects in chain methods of dc
  tests/unittests/functional/test_mixins.py
  towhee/__init__.py
  towhee/engine/factory.py
  towhee/functional/entity.py
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/dispatcher.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, size/L, approved

#874 Stream load json and csv
  tests/unittests/functional/test_data_collection.py
  tests/unittests/test_util/test_mixins/test.csv
  tests/unittests/test_util/test_mixins/test.json
  towhee/functional/mixins/data_source.py
Labels: lgtm, size/L, approved

#878 Add examples to towhee.types.arg.to_image_color
  towhee/types/arg.py
  towhee/types/image_utils.py
Labels: lgtm, approved, size/S

#884 optimize device to cpu in ut
  tests/unittests/operators/test_pytorch_object_detection_operator.py
Labels: lgtm, approved, size/XS

#837 Refactor parallel for DC
  towhee/functional/data_collection.py
  towhee/functional/mixins/parallel.py
  towhee/functional/option.py
Labels: lgtm, size/L, approved

#883 Add to_pil from_pil
  tests/unittests/types/test_mage_utils.py
  towhee/types/image_utils.py
Labels: lgtm, approved, size/M

#882 Multi-runners
  tests/unittests/engine/test_pipeline.py
  tests/unittests/test_util/test_multi_runner/test_multi_runner.yaml
  towhee/dag/operator_repr.py
  towhee/engine/operator_context.py
Labels: lgtm, size/L, approved

#887 Add replace function and modify fill_entity function in entity mixin
  tests/unittests/functional/test_data_collection.py
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, approved, size/M

#897 add operator flag to register decorator
  towhee/engine/operator_registry.py
  towhee/operator/base.py
Labels: lgtm, approved, size/M

#899 add config helper.
  tests/unittests/trainer/test_args.py
  towhee/trainer/training_config.py
  towhee/trainer/utils/visualization.py
Labels: lgtm, size/L, approved

#902 Add OperatorFlag to operator module
  towhee/operator/__init__.py
Labels: lgtm, approved, size/XS

#904 fix bugs in get started and API documents
  docs/get-started/data-collection.md
  towhee/functional/data_collection.py
  towhee/functional/mixins/data_source.py
  towhee/functional/mixins/dispatcher.py
  towhee/functional/mixins/entity_mixin.py
  towhee/functional/mixins/parallel.py
  towhee/hub/builtin/operators/computer_vision.py
Labels: lgtm, approved, size/M

#907 Add runas_op function to simplify user-defined operators
  tests/unittests/functional/test_data_collection.py
  towhee/engine/factory.py
  towhee/functional/data_collection.py
  towhee/hub/builtin/__init__.py
  towhee/hub/builtin/operators/__init__.py
  towhee/hub/builtin/operators/runas_op.py
  towhee/hub/preclude/__init__.py
Labels: lgtm, size/L, approved

#908 Allow import Entity from towhee and towhee.functional
  towhee/__init__.py
  towhee/functional/__init__.py
Labels: lgtm, approved, size/M

#909 add new python package for towhee.models
  setup.py
Labels: lgtm, approved, size/M

#917 support operator factory method
  towhee/engine/operator_loader.py
Labels: approved, size/S

#918 add dc.glob
  towhee/dc/__init__.py
Labels: lgtm, approved, size/M

#924 add `towhee.glob`
  towhee/__init__.py
  towhee/dc/__init__.py
  towhee/doc/source/towhee/towhee.rst
  towhee/hparam/hyperparameter.py
Labels: lgtm, approved, size/M

#928 fix operator always reload problem
  towhee/functional/mixins/data_source.py
  towhee/hub/file_manager.py
Labels: lgtm, approved, size/S

#926 Add head and tail function in display mixin and to_dict fucntion in entity mixin
  requirements.txt
  test_requirements.txt
  tests/unittests/functional/test_data_collection.py
  towhee/functional/entity.py
  towhee/functional/mixins/display.py
Labels: lgtm, size/L, approved

#920 refactor operator register
  towhee/doc/source/towhee/towhee.rst
  towhee/engine/operator_registry.py
  towhee/engine/uri.py
  towhee/utils/repo_normalize.py
Labels: lgtm, size/L, approved

#930 Add testcase of data collection
  tests/testcases/requirements.text
  tests/testcases/test_data_collection.py
Labels: lgtm, size/L, approved

#932 add feature engineer operators
  tests/unittests/functional/test_stateful_operator.py
  towhee/engine/factory.py
  towhee/hub/builtin/operators/feature_engineer.py
  towhee/hub/preclude/__init__.py
  towhee/operator/stateful_operator.py
Labels: lgtm, size/L, approved

#933 ray backend + bug and issue fixes
  towhee/functional/data_collection.py
  towhee/functional/mixins/parallel.py
Labels: lgtm, size/L, approved

#936 fix doc errors
  docs/get-started/data-collection.md
  towhee/engine/operator_loader.py
Labels: lgtm, approved, size/S

#931 update api doc
  tests/unittests/engine/test_op.py
  towhee/__init__.py
  towhee/dc/__init__.py
  towhee/doc/source/index.rst
  towhee/doc/source/towhee/towhee.rst
  towhee/doc/source/towhee/towhee_operator.rst
  towhee/engine/factory.py
Labels: lgtm, approved, size/M

#940 add and optimize some training and vis guide examples.
  docs/fine-tune/train-operators/1_quick_start.md
  docs/fine-tune/train-operators/2_Fine_Tune_with_MNIST.md
  docs/fine-tune/train-operators/2_Fine_Tune_with_MNIST_files/2_Fine_Tune_with_MNIST_12_0.png
  docs/fine-tune/train-operators/3_train_a_bird_classification_model.md
  docs/fine-tune/train-operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_11_1.png
  docs/fine-tune/train-operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_0.png
  docs/fine-tune/train-operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_1.png
  docs/fine-tune/train-operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_2.png
  docs/fine-tune/train-operators/4_training_configs.md
  docs/fine-tune/train-operators/bird_image.png
  docs/fine-tune/train-operators/mnist_example.png
  docs/fine-tune/train-operators/quick_start_training.md
  docs/fine-tune/train-operators/train_on_imagenet.md
  docs/fine-tune/train-operators/train_on_mnist.md
  docs/fine-tune/train-operators/training_configs.md
Labels: lgtm, approved, size/XXL

#938 Remove id and related attributes in Entity
  tests/unittests/functional/test_data_collection.py
  tests/unittests/functional/test_entity.py
  towhee/engine/factory.py
  towhee/functional/entity.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, approved, size/M

#943 Support onehotencoder in DC
  towhee/hub/builtin/operators/feature_engineer.py
Labels: lgtm, approved, size/M

#944 fix event loop leak
  towhee/functional/mixins/parallel.py
Labels: lgtm, approved, size/XS

#947 optimizing ray implementation and closing loop
  towhee/functional/mixins/parallel.py
Labels: lgtm, approved, size/S

#949 change sidebars and remove title
  docs/fine-tune/train-operators/1_quick_start.md
  docs/fine-tune/train-operators/2_fine_tune_with_MNIST.md
  docs/fine-tune/train-operators/3_train_a_bird_classification_model.md
  docs/fine-tune/train-operators/4_training_configs.md
  docs/sidebars.js
Labels: lgtm, approved, size/S

#951 repair id
  docs/developer-guides/framework/dataframe-details.md
  docs/fine-tune/train-operators/1_quick_start.md
  docs/fine-tune/train-operators/2_fine_tune_with_MNIST.md
  docs/fine-tune/train-operators/3_train_a_bird_classification_model.md
  docs/fine-tune/train-operators/4_training_configs.md
Labels: lgtm, approved, size/S

#955 change filename into dashes
  docs/fine-tune/train-operators/fine-tune-with-MNIST.md
  docs/fine-tune/train-operators/quick-start.md
  docs/fine-tune/train-operators/train-a-bird-classification-model.md
  docs/fine-tune/train-operators/training-configs.md
  docs/sidebars.js
Labels: lgtm, approved, size/S

#953 Added numpy dependency into requirements.txt
  requirements.txt
Labels: lgtm, approved, size/XS

#956 fix api doc
  towhee/doc/requirements.txt
Labels: lgtm, approved, size/XS

#959 Add split and mv data_source to dataset
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/data_source.py
  towhee/functional/mixins/dataset.py
  towhee/utils/sklearn_utils.py
Labels: lgtm, size/L, approved

#942 Add dropna function
  tests/unittests/functional/test_data_collection.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, approved, size/M

#961 Add show and head method to DataCollection
  test_requirements.txt
  tests/unittests/functional/test_data_collection.py
  tests/unittests/functional/test_mixins.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/display.py
Labels: lgtm, size/L, approved

#958 Add rename function in DC
  tests/unittests/functional/test_data_collection.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, approved, size/S

#937 drop image_embedding_pipeline
  tests/unittests/pipelines/test_image_embedding_pipeline.py
  tests/unittests/pipelines/test_pipeline_ops.py
  towhee/hub/builtin/pipelines/image_embedding_template_1.yaml
  towhee/hub/builtin/pipelines/image_embedding_template_2.yaml
  towhee/hub/builtin/pipelines/image_embedding_template_3.yaml
  towhee/pipelines/__init__.py
  towhee/pipelines/alias_resolvers.py
  towhee/pipelines/base.py
  towhee/pipelines/image_embedding_pipeline.py
Labels: lgtm, approved, size/XL

#966 fix stateful operator & fix from_df
  tests/unittests/functional/test_entity.py
  tests/unittests/pipelines/test_pipeline_ops.py
  towhee/engine/factory.py
  towhee/functional/entity.py
  towhee/functional/mixins/dataset.py
  towhee/functional/mixins/state.py
  towhee/hub/builtin/operators/feature_engineer.py
  towhee/operator/stateful_operator.py
Labels: lgtm, approved, size/M

#972 Allow no state arg pass to set_evaluating
  towhee/functional/mixins/state.py
Labels: lgtm, approved, size/XS

#970 Plot confusion matrix and metrics table
  towhee/functional/mixins/metric.py
  towhee/utils/sklearn_utils.py
Labels: lgtm, approved, size/M
