Repository towhee-io/towhee, pull requests merged in 2022-12, with the labels that each got.

#2310 Add model to triton with onnx
  test_requirements.txt
  tests/unittests/runtime/test_check_util.py
  tests/unittests/runtime/test_config.py
  tests/unittests/triton/test_model_to_triton.py
  towhee/runtime/check_utils.py
  towhee/runtime/node_config.py
  towhee/serve/triton/model_to_triton.py
  towhee/utils/onnx_utils.py
Labels: lgtm, size/L, approved

#2319 Add mock accelerator
  tests/unittests/runtime/test_accelerator.py
  towhee/dc2.py
  towhee/runtime/__init__.py
  towhee/runtime/node_config.py
  towhee/runtime/runtime_conf.py
Labels: lgtm, approved, size/M

#2321 Update towhee version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#2322 Update master towhee version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#2327 repair sam optimizer ut problem
  tests/unittests/models/layers/test_sam.py
Labels: lgtm, approved, size/XS

#2301 Create TritonModel class
  tests/unittests/models/layers/test_sam.py
  tests/unittests/runtime/test_accelerator.py
  tests/unittests/runtime/test_runtime_config.py
  tests/unittests/serve/test_triton_model.py
  towhee/runtime/node_config.py
  towhee/runtime/runtime_conf.py
  towhee/serve/triton/bls/mock/mock_pb_util.py
  towhee/serve/triton_client.py
Labels: lgtm, size/L, approved

#2329 profiler bug
  towhee/runtime/performance_profiler.py
Labels: lgtm, approved, size/XS

#2330 Reorganize triton directory
  tests/unittests/triton/test_triton_client.py
  towhee/runtime/runtime_conf.py
  towhee/serve/triton/triton_client.py
Labels: lgtm, approved, size/S

#2325 Add pipeline builder in triton
  setup.py
  tests/unittests/triton/test_model_to_triton.py
  tests/unittests/triton/test_pipeline_builder.py
  towhee/runtime/__init__.py
  towhee/runtime/node_config.py
  towhee/serve/triton/constant.py
  towhee/serve/triton/model_to_triton.py
  towhee/serve/triton/pipeline_builder.py
  towhee/serve/triton/triton_config_builder.py
Labels: lgtm, size/L, approved

#2332 Triton model support batching
  tests/unittests/runtime/test_user_pipeline.py
  tests/unittests/triton/bls/test_pipeline_model.py
  tests/unittests/triton/test_pipe_to_triton.py
  towhee/runtime/runtime_pipeline.py
  towhee/serve/triton/bls/pipeline_model.py
Labels: lgtm, size/L, approved

#2338 Modify isc to support onnx export
  towhee/models/isc/isc.py
Labels: lgtm, approved, size/XS, component/models

#2333 Add triton client
  tests/unittests/triton/test_pipeline_client.py
  towhee/__init__.py
  towhee/serve/__init__.py
  towhee/serve/triton/pipeline_client.py
Labels: lgtm, size/L, approved

#2339 remove redundant load and save method in NNOperator
  tests/unittests/trainer/test_weights.py
  towhee/operator/base.py
Labels: lgtm, approved, size/M

#2341 set nnop shareable
  towhee/operator/base.py
Labels: lgtm, approved, size/XS

#2344 update get class help function
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/S

#2342 Build triton inference image
  towhee/__init__.py
  towhee/dc2.py
  towhee/serve/__init__.py
  towhee/serve/triton/docker_image_builder_v2.py
  towhee/serve/triton/dockerfiles/DockerfileCuda113_v2
  towhee/serve/triton/dockerfiles/DockerfileCuda114_v2
  towhee/serve/triton/dockerfiles/DockerfileCuda116_v2
  towhee/serve/triton/dockerfiles/DockerfileCuda117
  towhee/serve/triton/dockerfiles/DockerfileCuda117dev
  towhee/serve/triton/dockerfiles/__init__.py
  towhee/utils/dependency_control.py
Labels: lgtm, size/L, approved

#2345 triton client support dict
  tests/unittests/triton/test_triton_client.py
  towhee/serve/triton/triton_client.py
Labels: lgtm, approved, size/S

#2348 Update notes of models, ops, notebooks in releases v0.8.1 & v0.9.0
  MODEL_CHANGELOG.md
  README.md
  README_CN.md
Labels: lgtm, size/L, approved, kind/documentation

#2350 optimize and repair lr config.
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, approved, size/XS

#2349 Remove param_scope from display mixin
  towhee/datacollection/mixins/display.py
Labels: lgtm, size/L, approved

#2352 Update config when build pipeline
  tests/unittests/triton/test_pipeline_builder.py
  towhee/serve/triton/pipeline_builder.py
Labels: lgtm, approved, size/S

#2353 Update tritonserver version
  towhee/serve/triton/dockerfiles/DockerfileCuda117
  towhee/serve/triton/dockerfiles/DockerfileCuda117dev
Labels: lgtm, approved, size/XS

#2351 Solve op_loader loading unexpected cognominal module issue
  tests/unittests/engine/test_operator_loader.py
  tests/unittests/mock_operators/cal_diff/__init__.py
  tests/unittests/mock_operators/cal_diff/cal.py
  tests/unittests/mock_operators/cal_sum/__init__.py
  tests/unittests/mock_operators/cal_sum/cal.py
  tests/unittests/runtime/test_operator_loader.py
  towhee/engine/factory.py
  towhee/engine/operator_loader.py
  towhee/runtime/operator_manager/operator_loader.py
Labels: lgtm, size/L, approved

#2354 Add progress bar for builder
  towhee/serve/triton/pipeline_builder.py
Labels: lgtm, approved, size/XS

#2358 Triton client use asyn infer
  tests/unittests/triton/test_pipeline_client.py
  towhee/serve/triton/pipeline_client.py
  towhee/utils/triton_httpclient.py
Labels: lgtm, size/L, approved

#2357 Add Serializer
  tests/unittests/triton/bls/test_pipeline_model.py
  tests/unittests/triton/test_pipe_to_triton.py
  tests/unittests/triton/test_pipeline_client.py
  tests/unittests/triton/test_serializer.py
  tests/unittests/utils/test_np_format.py
  towhee/serve/triton/bls/pipeline_model.py
  towhee/serve/triton/pipeline_client.py
  towhee/serve/triton/serializer.py
  towhee/utils/empty_format.py
  towhee/utils/np_format.py
Labels: lgtm, size/L, approved

#2360 Add AutoConfig for pipeline
  tests/unittests/runtime/test_auto_config.py
  tests/unittests/triton/test_pipeline_builder.py
  towhee/__init__.py
  towhee/dc2.py
  towhee/runtime/__init__.py
  towhee/runtime/dag_repr.py
  towhee/runtime/node_config.py
Labels: lgtm, size/L, approved
