Repository towhee-io/towhee, pull requests merged in 2022-04, with the labels that each got.

#976 Fix the checkout and setup-python version in workflow
  .github/workflows/codecov.yml
  .github/workflows/pylint.yml
Labels: lgtm, approved, size/XS

#975 Encapsulate sklearn models as builtin op
  towhee/hub/builtin/operators/sklearn.py
  towhee/hub/preclude/__init__.py
  towhee/utils/sklearn_utils.py
Labels: lgtm, size/L, approved

#977 Add timestamp to audio_frame
  tests/unittests/types/test_audio_frame.py
  towhee/types/audio_frame.py
Labels: lgtm, approved, size/S

#981 Add requirements for DC docs
  docs/get-started/data-collection.md
  docs/sidebars.js
Labels: lgtm, approved, size/XS

#979 Add feature summarize and update metric report
  towhee/functional/mixins/display.py
  towhee/functional/mixins/metric.py
  towhee/utils/ipython_utils.py
  towhee/utils/matplotlib_utils.py
  towhee/utils/pandas_utils.py
Labels: lgtm, size/L, approved

#984 Update requirements in doc
  towhee/doc/requirements.txt
Labels: size/S

#986 add self attention layer for perceiver
  tests/unittests/models/layers/test_selfattention.py
  towhee/models/perceiver/SelfAttention.py
Labels: lgtm, approved, size/M

#983 split operation
  towhee/functional/mixins/parallel.py
Labels: lgtm, approved, size/M

#987 Update mixins ut
  tests/unittests/functional/test_mixins.py
  towhee/functional/mixins/dispatcher.py
Labels: lgtm, approved, size/S

#988 add cross attention layer for perceiver
  tests/unittests/models/layers/test_crossattention.py
  towhee/models/perceiver/CrossAttention.py
Labels: lgtm, approved, size/M

#989 train_cub_200 example
  docs/fine-tune/train-operators/train-cub-200-2011.md
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_10_0.png
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_12_0.png
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_13_0.png
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_19_0.png
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_21_0.png
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_23_0.png
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_25_0.png
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_27_0.png
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_29_0.png
  docs/fine-tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_40_0.png
  docs/sidebars.js
Labels: lgtm, size/L, approved

#993 add mlp for perceiver
  tests/unittests/models/layers/test_perceiver_mlp.py
  towhee/models/perceiver/mlp.py
Labels: lgtm, approved, size/M

#994 fix doc workflow bug
  docs/get-started/data-collection.md
Labels: lgtm, approved, size/XS

#995 remove useless elements in docs
  docs/fine-tune/train-operators/train-cub-200-2011.md
Labels: lgtm, approved, size/M

#996 update as_entity and as_raw
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, approved, size/M

#997 update documents and rename dc.factory to dc._factory
  towhee/doc/source/builtin operators/feature engineer.rst
  towhee/doc/source/builtin operators/index.rst
  towhee/doc/source/builtin operators/runas op.rst
  towhee/doc/source/builtin operators/sklearn.rst
  towhee/doc/source/data_collection/mixins.rst
  towhee/functional/data_collection.py
  towhee/functional/mixins/dataset.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/entity_mixin.py
  towhee/functional/mixins/feature_engine.py
  towhee/functional/mixins/model_engine.py
  towhee/functional/mixins/parallel.py
  towhee/functional/mixins/state.py
  towhee/hub/builtin/operators/feature_engineer.py
  towhee/hub/builtin/operators/runas_op.py
  towhee/hub/builtin/operators/sklearn.py
Labels: lgtm, size/L, approved

#999 add residual for perceiver
  tests/unittests/models/layers/test_perceiver_residual.py
  towhee/models/perceiver/Residual.py
Labels: lgtm, approved, size/M

#998 Update select for entity
  towhee/functional/data_collection.py
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, approved, size/M

#1000 Update _factory in select
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, approved, size/XS

#980 Add ut for built-in sklearn operators
  test_requirements.txt
  tests/unittests/functional/test_data_collection.py
  tests/unittests/test_util/data.csv
Labels: lgtm, size/L, approved

#1004 Change the color of confusion matrix
  towhee/functional/mixins/metric.py
Labels: lgtm, approved, size/S

#1007 add ut for hparam
  tests/unittests/hparam/__init__.py
  tests/unittests/hparam/test_hparam.py
  towhee/hparam/hyperparameter.py
Labels: lgtm, size/L, approved

#1011 Update GSOC page
  docs/get-started/Gsoc-2022.md
Labels: lgtm, size/L, approved

#1010 add create cross attention function for perceiver
  tests/unittests/models/layers/test_create_cross_attention.py
  towhee/models/perceiver/Sequential.py
  towhee/models/perceiver/create_cross_attention.py
Labels: lgtm, approved, size/M

#1012 Bump Towhee version in quick start
  docs/get-started/gsoc-2022.md
  docs/get-started/quick-start.mdx
Labels: lgtm, approved, size/XS

#1019 add create self attention block function
  tests/unittests/models/layers/test_create_self_attention_block.py
  towhee/models/perceiver/create_self_attention_block.py
Labels: lgtm, approved, size/M

#1018 Add user option for towhee install cmdline
  tests/unittests/command/test_cmdline.py
  towhee/command/develop.py
Labels: lgtm, approved, size/S

#1009 add support for nested json
  docs/get-started/data-collection.md
  tests/unittests/functional/test_document.py
  towhee/__init__.py
  towhee/hparam/hyperparameter.py
Labels: lgtm, size/L, approved

#1020 Fix improper ... suffix on showing ndarray
  towhee/functional/mixins/display.py
Labels: lgtm, approved, size/XS

#1023 rm useless function
  towhee/functional/mixins/dataset.py
Labels: lgtm, approved, size/S

#1026 update show mixin and support specifilizing formatter for each column
  towhee/functional/mixins/display.py
Labels: lgtm, approved, size/S

#1025 Call `git lfs` to check
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/XS

#1027 drop module towhee.dc and add towhee.dc as a factory method
  tests/unittests/functional/test_data_collection.py
  tests/unittests/functional/test_entity.py
  tests/unittests/functional/test_parallel.py
  towhee/__init__.py
  towhee/dc/__init__.py
  towhee/functional/__init__.py
Labels: lgtm, size/L, approved

#1024 mmap -> multiple pmap
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/parallel.py
  towhee/functional/mixins/ray.py
Labels: lgtm, size/L, approved

#1029 support default namespace in operator loader
  towhee/engine/operator_loader.py
Labels: lgtm, approved, size/XS

#1030 Add configs for mvit models in pytorchvideo
  tests/unittests/models/utils/test_video_transforms.py
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/M, component/models

#1031 Rename some built-in operator
  tests/unittests/functional/test_data_collection.py
  towhee/hub/builtin/operators/feature_engineer.py
  towhee/hub/builtin/operators/tensor_like.py
Labels: lgtm, approved, size/M

#1034 fix unittest in codecov
  tests/unittests/engine/test_operator_register.py
  tests/unittests/functional/test_data_collection.py
  tests/unittests/functional/test_mixins.py
  tests/unittests/functional/test_parallel.py
  tests/unittests/functional/test_stateful_operator.py
  tests/unittests/hparam/test_hparam.py
  tests/unittests/hub/test_preclude.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/metric.py
  towhee/hparam/hyperparameter.py
  towhee/hub/builtin/operators/computer_vision.py
  towhee/hub/builtin/operators/tensor_like.py
Labels: lgtm, size/L, approved

#1035 Update select to support index[]
  towhee/functional/mixins/display.py
  towhee/functional/mixins/entity_mixin.py
  towhee/hub/builtin/operators/computer_vision.py
Labels: lgtm, approved, size/M

#1037 fix typo
  tests/testcases/test_data_collection.py
  tests/testcases/test_main.py
  towhee/functional/data_collection.py
Labels: lgtm, size/L, approved

#1038 Modify the testcase
  tests/testcases/requirements.text
  tests/testcases/test_data_collection.py
  tests/testcases/test_main.py
Labels: lgtm, size/L, approved

#1039 Update towhee.dc to support index[]
  towhee/functional/__init__.py
Labels: lgtm, approved, size/M

#1040 fix builtin operator doc
  towhee/doc/source/builtin operators/tensor like.rst
Labels: lgtm, approved, size/XS

#1045 Fix doctest typo in runas_op
  towhee/hub/builtin/operators/runas_op.py
Labels: lgtm, approved, size/XS

#1046 Support show AudioFrame
  tests/unittests/functional/test_mixins.py
  towhee/_types/image.py
  towhee/functional/mixins/display.py
  towhee/types/audio_frame.py
Labels: lgtm, size/L, approved

#1047 Add image animation tutorial
  demo/image_animation/README.md
  towhee/_types/image.py
  towhee/utils/plot_utils.py
  tutorials/anime_style_transformer.ipynb
Labels: lgtm, size/L, approved

#1049 another field selection syntax
  towhee/functional/mixins/entity_mixin.py
Labels: lgtm, approved, size/S

#1051 fix docstring for state mixin
  towhee/functional/mixins/state.py
Labels: lgtm, approved, size/XS

#1052 Download repo witout git-lfs
  towhee/hub/file_manager.py
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/M

#1053 Convert status callederror to filenotfounderror
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/XS

#1054 Update towhee version
  tests/testcases/requirements.text
  tests/testcases/test_main.py
Labels: lgtm, approved, size/XS

#1055 Update towhee version
  setup.py
Labels: lgtm, approved, size/XS

#1058 update installing towhee.models
  docs/get-started/quick-start.mdx
Labels: lgtm, approved, size/XS

#1057 Support AudioFrame in DataCollection.show()
  towhee/_types/image.py
  towhee/functional/mixins/display.py
  towhee/types/audio_frame.py
Labels: lgtm, approved, size/M

#1061 Update video transforms and add c2d & i3d
  tests/unittests/models/utils/test_video_transforms.py
  towhee/models/utils/video_transforms.py
Labels: lgtm, size/L, approved, component/models

#1032 Refactor towhee.ops to support pipeline
  tests/unittests/hub/test_repo_manager.py
  tests/unittests/pipelines/test_pipeline_ops.py
  tests/unittests/pipelines/test_pipeline_pipes.py
  towhee/__init__.py
  towhee/engine/factory.py
  towhee/hub/file_manager.py
  towhee/hub/repo_manager.py
Labels: lgtm, size/L, approved

#1062 update readme
  README.md
Labels: lgtm, approved, size/S

#1056 support ray dataset
  towhee/functional/data_collection.py
Labels: lgtm, approved, size/XS

#1063 doc about install towhee.models
  docs/get-started/quick-start.mdx
Labels: lgtm, approved, size/XS

#1064 Add csn and r2plus1d
  tests/unittests/models/utils/test_video_transforms.py
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/S, component/models

#1069 Float images in DataCollection.show()
  tests/unittests/functional/test_mixins.py
  towhee/functional/mixins/display.py
Labels: lgtm, approved, size/S

#1073 in DataCollection.show(), change multi-image layout in a single td
  tests/unittests/functional/test_mixins.py
  towhee/functional/mixins/display.py
  towhee/utils/matplotlib_utils.py
Labels: lgtm, approved, size/S

#1076 In DataCollection.show(), adjust td format
  README.md
  tests/unittests/functional/test_mixins.py
  towhee/functional/mixins/display.py
Labels: lgtm, size/L, approved

#1077 Restore README
  README.md
Labels: lgtm, size/L, approved

#1072 Add from_ops parameter in pipeline
  towhee/engine/factory.py
  towhee/hub/file_manager.py
Labels: lgtm, approved, size/S

#1068 runnings hub ops in ray
  towhee/_types/image.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/parallel.py
  towhee/functional/mixins/ray.py
Labels: lgtm, size/L, approved

#1086 Fix links in contributing.md
  CONTRIBUTING.md
Labels: type/doc, approved, size/XS

#1087 Minor change in bird classification document
  docs/fine-tune/train-operators/train-a-bird-classification-model.md
Labels: lgtm, approved, size/XS

#1084 support pandas backend
  test_requirements.txt
  tests/unittests/functional/test_pandas.py
  towhee/engine/factory.py
  towhee/functional/__init__.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/dataset.py
  towhee/functional/mixins/entity_mixin.py
  towhee/functional/mixins/state.py
Labels: lgtm, size/L, approved

#1088 Add docs contribution guide
  docs/developer-guides/contributing/adding-new-doc.md
  docs/developer-guides/contributing/contributing-guide.md
  docs/get-started/gsoc-2022.md
  docs/sidebars.js
Labels: lgtm, approved, size/M

#1091 attention interface.
  tests/unittests/trainer/test_visualization_util.py
  towhee/trainer/utils/visualization.py
Labels: lgtm, approved

#1078 DC and Ray Docs
  docs/sidebars.js
  docs/user-guides/data-collection/data-collection-with-ray.md
Labels: lgtm, approved, size/M

#1101 Disable tests
  tests/testcases/test_main.py
Labels: lgtm, approved, size/XS

#1094 demo of tsm
  tests/unittests/models/tsm/__init__.py
  tests/unittests/models/tsm/test_tsm.py
  towhee/models/tsm/basic_ops.py
  towhee/models/tsm/bn_inception.py
  towhee/models/tsm/mobilenet_v2.py
  towhee/models/tsm/non_local.py
  towhee/models/tsm/temporal_shift.py
  towhee/models/tsm/tsm.py
Labels: lgtm, approved, size/XXL, component/models

#1095 Optimize vit model and some layers
  tests/unittests/models/layers/test_patch_embed2d.py
  tests/unittests/models/vit/test_vit.py
  towhee/models/layers/multi_head_attention.py
  towhee/models/layers/patch_embed2d.py
  towhee/models/vit/__init__.py
  towhee/models/vit/vit.py
  towhee/models/vit/vit_block.py
  towhee/models/vit/vit_utils.py
Labels: lgtm, approved, component/models

#1096 Add milvus_search builtin operator
  towhee/doc/requirements.txt
  towhee/doc/source/builtin operators/index.rst
  towhee/doc/source/builtin operators/milvus search.rst
  towhee/hub/builtin/operators/milvus_search.py
  towhee/hub/preclude/__init__.py
Labels: lgtm, approved, size/M

#1092 add a serve api for data collection
  test_requirements.txt
  tests/unittests/functional/test_mixins.py
  towhee/__init__.py
  towhee/functional/__init__.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/serve.py
Labels: size/L, approved

#1103 Add default labels to different kinds of issues
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/design proposal.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: lgtm, approved, size/S

#1108 Fix path.unlink issue for pre python 3.8
  towhee/command/develop.py
  towhee/hub/file_manager.py
Labels: lgtm, approved, size/S

#1105 use pytest for unit test
  .coveragerc
  .github/workflows/codecov.yml
  pyproject.toml
  setup.cfg
  setup.py
  test_requirements.txt
  tests/unittests/command/test_cmdline.py
  tests/unittests/models/tsm/test_tsm.py
  tests/unittests/pipelines/test_pipeline_ops.py
  towhee/engine/factory.py
  towhee/functional/__init__.py
  towhee/functional/mixins/dispatcher.py
  towhee/functional/mixins/milvus_mixin.py
  towhee/functional/mixins/parallel.py
  towhee/functional/mixins/serve.py
Labels: lgtm, size/L, approved

#1114 Add TimeSformer model
  tests/unittests/models/timesformer/__init__.py
  tests/unittests/models/timesformer/test_timesformer.py
  towhee/models/timesformer/__init__.py
  towhee/models/timesformer/timesformer.py
  towhee/models/timesformer/timesformer_block.py
  towhee/models/timesformer/timesformer_utils.py
Labels: lgtm, size/L, approved, component/models

#1113 models and trainer pytest
  setup.cfg
  test_requirements.txt
  tests/unittests/models/layers/test_crossattention.py
  tests/unittests/models/layers/test_multimodalattention.py
  tests/unittests/models/layers/test_perceiver_residual.py
  tests/unittests/models/layers/test_selfattention.py
  tests/unittests/models/mvit/test_multiscale_vision_transformers.py
  tests/unittests/models/tsm/test_tsm.py
  towhee/models/layers/patch_merging3d.py
  towhee/models/multiscale_vision_transformers/__init__.py
  towhee/models/multiscale_vision_transformers/create_multiscale_vision_transformers.py
  towhee/models/perceiver/__init__.py
  towhee/models/perceiver/create_cross_attention.py
  towhee/models/perceiver/create_self_attention.py
  towhee/models/perceiver/create_self_attention_block.py
  towhee/models/perceiver/cross_attention.py
  towhee/models/perceiver/multi_head_attention.py
  towhee/models/perceiver/residual.py
  towhee/models/perceiver/self_attention.py
  towhee/models/perceiver/sequential.py
  towhee/models/tsm/basic_ops.py
  towhee/models/tsm/bn_inception.py
  towhee/models/tsm/mobilenet_v2.py
  towhee/models/tsm/non_local.py
  towhee/models/tsm/temporal_shift.py
  towhee/models/tsm/tsm.py
Labels: lgtm, approved, size/XXL

#1116 Update for refactoring operator with cmd
  towhee/command/execute.py
  towhee/hub/operator_manager.py
Labels: lgtm, approved, size/S

#1117 avoid use the private module from torchvision.
  towhee/models/retina_face/retinaface.py
  towhee/models/retina_face/utils.py
Labels: lgtm, approved, size/M

#1115 DOC 1.0 side bar automate
  docs/sidebars.js
Labels: lgtm, approved, size/M

#1119 Fix broken link in DC doc
  docs/user-guides/data-collection/data-collection-with-ray.md
Labels: lgtm, approved, size/XS

#1118 Modify status in gitutils to cope with non-english env
  tests/unittests/utils/test_git_utils.py
  towhee/hub/file_manager.py
  towhee/utils/git_utils.py
Labels: lgtm, approved, size/S

#1124 dont show plot
  tests/unittests/models/mvit/__init__.py
  tests/unittests/models/video_swin_transformer/__init__.py
  tests/unittests/trainer/test_visualization_util.py
Labels: lgtm, approved, size/XS

#1121 add model and trainer to coverage
  setup.cfg
Labels: lgtm, approved, size/XS

#1127 DEV-DOCS 1.1 Directory names and the doc unit test are in accordance to the new automated side bar
  docs/Developer guides/cmdline.md
  docs/Developer guides/contributing/adding-new-doc.md
  docs/Developer guides/contributing/contributing-guide.md
  docs/Developer guides/framework/DAG-details.md
  docs/Developer guides/framework/architecture-overview.md
  docs/Developer guides/framework/dag.png
  docs/Developer guides/framework/dataframe-details.md
  docs/Developer guides/framework/engine-details.md
  docs/Developer guides/framework/framework.png
  docs/Developer guides/framework/hub-integration-and-caching.md
  docs/Developer guides/framework/image-ensemble-training.md
  docs/Developer guides/framework/pipeline-overview.md
  docs/Developer guides/framework/roadmap.md
  docs/Developer guides/models/layers-overview.md
  docs/Developer guides/models/swin_arch.png
  docs/Fine tune/train-operators/2_Fine_Tune_with_MNIST_files/2_Fine_Tune_with_MNIST_12_0.png
  docs/Fine tune/train-operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_11_1.png
  docs/Fine tune/train-operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_0.png
  docs/Fine tune/train-operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_1.png
  docs/Fine tune/train-operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_2.png
  docs/Fine tune/train-operators/fine-tune-with-MNIST.md
  docs/Fine tune/train-operators/quick-start.md
  docs/Fine tune/train-operators/train-a-bird-classification-model.md
  docs/Fine tune/train-operators/train-cub-200-2011.md
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_10_0.png
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_12_0.png
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_13_0.png
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_19_0.png
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_21_0.png
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_23_0.png
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_25_0.png
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_27_0.png
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_29_0.png
  docs/Fine tune/train-operators/train_cub_200_2011_files/train_cub_200_2011_40_0.png
  docs/Fine tune/train-operators/training-configs.md
  docs/Getting Started/data-collection.md
  docs/Getting Started/gsoc-2022.md
  docs/Getting Started/install.md
  docs/Getting Started/pipeline-config.md
  docs/Getting Started/quick-start.mdx
  docs/Getting Started/towhee.jpeg
  docs/Getting Started/troubleshooting.md
  docs/Supported pipelines/audio-embedding.md
  docs/Supported pipelines/image-embedding.md
  docs/User guides/data-collection/data-collection-with-ray.md
  tests/unittests/documents/test_dc_get_started.py
Labels: lgtm, approved, size/XS

#1128 Allow timesformer to load pretrained models
  tests/unittests/models/timesformer/test_timesformer.py
  tests/unittests/models/vit/test_vit.py
  towhee/models/timesformer/__init__.py
  towhee/models/timesformer/timesformer.py
  towhee/models/timesformer/timesformer_utils.py
  towhee/models/vit/__init__.py
  towhee/models/vit/vit.py
  towhee/models/vit/vit_utils.py
Labels: lgtm, size/L, approved, component/models

#1129 DOC 1.3 updated broken links of markdown files
  docs/Developer guides/framework/architecture-overview.md
  docs/Getting Started/quick-start.mdx
  docs/Supported pipelines/audio-embedding.md
  docs/Supported pipelines/image-embedding.md
Labels: lgtm, approved, size/S

#1131 DOCS 1.3 broken links change
  docs/Developer guides/contributing/contributing-guide.md
  docs/Fine tune/Train operators/2_Fine_Tune_with_MNIST_files/2_Fine_Tune_with_MNIST_12_0.png
  docs/Fine tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_11_1.png
  docs/Fine tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_0.png
  docs/Fine tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_1.png
  docs/Fine tune/Train operators/3_train_a_bird_classification_model_files/3_train_a_bird_classification_model_13_2.png
  docs/Fine tune/Train operators/fine-tune-with-MNIST.md
  docs/Fine tune/Train operators/quick-start.md
  docs/Fine tune/Train operators/train-a-bird-classification-model.md
  docs/Fine tune/Train operators/train-cub-200-2011.md
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_10_0.png
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_12_0.png
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_13_0.png
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_19_0.png
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_21_0.png
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_23_0.png
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_25_0.png
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_27_0.png
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_29_0.png
  docs/Fine tune/Train operators/train_cub_200_2011_files/train_cub_200_2011_40_0.png
  docs/Fine tune/Train operators/training-configs.md
  docs/Supported pipelines/audio-embedding.md
  docs/Supported pipelines/image-embedding.md
  docs/User guides/Data collection/data-collection-with-ray.md
  docs/overview.md
Labels: lgtm, approved, size/S

#1132 DOCS 1.4 Directory name update
  docs/Tutorials/image-deduplication.md
  docs/Tutorials/image_dedup.png
  docs/Tutorials/music-recognition-system.md
  docs/Tutorials/music_embedding.png
  docs/Tutorials/music_recog_system.png
  docs/Tutorials/reverse-image-search.md
  docs/Tutorials/reverse_image_search_results1.png
  docs/Tutorials/reverse_image_search_results2.png
  docs/Tutorials/reverse_image_search_step1.png
  docs/Tutorials/reverse_image_search_step2.png
Labels: lgtm, approved, size/XS

#1133 Update new doc guide
  docs/Developer guides/contributing/adding-new-doc.md
Labels: lgtm, approved, size/M

#1126 Add hit_ratio and average_precision metrics
  tests/unittests/functional/test_mixins.py
  towhee/functional/mixins/metric.py
Labels: lgtm, approved, size/M

#1135 Update display with str data
  towhee/functional/mixins/display.py
Labels: lgtm, approved, size/XS

#1125 add document
  setup.cfg
  towhee/doc/requirements.txt
  towhee/doc/source/conf.py
  towhee/doc/source/data_collection/get_started.rst
  towhee/doc/source/index.rst
  towhee/doc/source/user_guide/10-minutes-to-data-collection.md
  towhee/doc/source/user_guide/index.rst
  towhee/functional/__init__.py
  towhee/functional/data_collection.py
Labels: lgtm, size/L, approved

#1136 Add defalut search parameter in milvus-search
  towhee/hub/builtin/operators/milvus_search.py
Labels: lgtm, approved, size/M

#1137 support entity in towhee.api
  towhee/functional/__init__.py
  towhee/functional/mixins/entity_mixin.py
  towhee/functional/mixins/serve.py
Labels: lgtm, size/L, approved

#1140 Optimize video_transforms
  tests/unittests/models/utils/test_video_transforms.py
  towhee/models/timesformer/timesformer.py
  towhee/models/utils/video_transforms.py
Labels: lgtm, size/L, approved, component/models

#1139 drop unused main
  setup.cfg
  towhee/functional/mixins/computer_vision.py
  towhee/functional/mixins/dataset.py
  towhee/functional/mixins/dispatcher.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/entity_mixin.py
  towhee/functional/mixins/metric.py
  towhee/functional/mixins/parallel.py
  towhee/functional/mixins/state.py
Labels: lgtm, approved, size/M

#1142 Add parameters for transform_video: start_sec & end_sec
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/XS, component/models

#1141 update read the docs
  .readthedocs.yaml
  towhee/doc/source/conf.py
Labels: lgtm, approved, size/XS

#1144 fix `as_function` for `towhee.api`
  towhee/doc/source/user_guide/10-minutes-to-data-collection.md
  towhee/functional/__init__.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/entity_mixin.py
  towhee/functional/mixins/serve.py
Labels: lgtm, size/L, approved

#1143 Add save-image builtin op
  towhee/functional/mixins/dataset.py
  towhee/hub/builtin/operators/computer_vision.py
Labels: lgtm, approved, size/M

#1145 Update image-load to towhee.Image
  towhee/hub/builtin/operators/computer_vision.py
Labels: lgtm, approved, size/XS

#1147 Allow video-transforms to skip UniformTemporalSubsample
  tests/unittests/models/utils/test_video_transforms.py
  towhee/models/utils/video_transforms.py
Labels: lgtm, approved, size/M, component/models

#1150 fix towhee.api request decode
  test_requirements.txt
  towhee/functional/mixins/serve.py
Labels: lgtm, approved, size/S

#1151 Add param when milvus no index and retrun dc
  towhee/functional/mixins/milvus_mixin.py
  towhee/hub/builtin/operators/milvus_search.py
Labels: lgtm, approved, size/S

#1152 Ray actor cleanup bug fix
  towhee/functional/mixins/ray.py
Labels: lgtm, approved, size/XS

#1153 add new call tracker
  towhee/doc/source/towhee/towhee.rst
  towhee/functional/__init__.py
  towhee/functional/mixins/entity_mixin.py
  towhee/hparam/__init__.py
  towhee/hparam/hyperparameter.py
Labels: lgtm, size/L, approved

#1155 Fix issue to unstream milvusmixin
  towhee/functional/mixins/milvus_mixin.py
Labels: lgtm, approved, size/XS

#1156 Feature/drop call holder
  towhee/engine/factory.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/dispatcher.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/metric.py
  towhee/functional/mixins/milvus_mixin.py
  towhee/hparam/hyperparameter.py
  towhee/hub/file_manager.py
Labels: lgtm, size/L, approved

#1157 add hparam to pytest
  setup.cfg
  towhee/functional/__init__.py
  towhee/functional/data_collection.py
  towhee/functional/mixins/computer_vision.py
  towhee/functional/mixins/dataset.py
  towhee/functional/mixins/display.py
  towhee/functional/mixins/milvus_mixin.py
  towhee/functional/mixins/ray.py
  towhee/functional/mixins/serve.py
  towhee/functional/option.py
  towhee/hparam/hyperparameter.py
Labels: lgtm, size/L, approved

#1160 Add CLIP model
  tests/unittests/models/clip/__init__.py
  tests/unittests/models/clip/test_clip.py
  towhee/models/clip/README.md
  towhee/models/clip/__init__.py
  towhee/models/clip/model.py
Labels: lgtm, approved, size/XL, component/models

#1163 Optimize APIs to call timesformer & vit from towhee.models
  tests/unittests/models/timesformer/test_timesformer.py
  tests/unittests/models/vit/test_vit.py
  towhee/models/timesformer/__init__.py
  towhee/models/timesformer/timesformer.py
  towhee/models/timesformer/timesformer_utils.py
  towhee/models/vit/__init__.py
  towhee/models/vit/vit.py
  towhee/trainer/utils/layer_freezer.py
Labels: lgtm, size/L, approved, component/models

#1148 add_tsm
  tests/unittests/models/tsm/test_tsm.py
  towhee/models/layers/non_local.py
  towhee/models/tsm/__init__.py
  towhee/models/tsm/bn_inception.py
  towhee/models/tsm/mobilenet_v2.py
  towhee/models/tsm/temporal_shift.py
  towhee/models/tsm/tsm.py
  towhee/models/utils/basic_ops.py
Labels: lgtm, approved, size/XXL, component/models

#1166 Fix broken docs links
  docs/01-Overview.md
  docs/02-Getting started/quick-start.mdx
  docs/04-Supported pipelines/audio-embedding.md
  docs/04-Supported pipelines/image-embedding.md
  docs/06-Developer guides/framework/architecture-overview.md
Labels: lgtm, approved, size/S

#1167 Add Visual Prompt for ActionClip
  tests/unittests/models/action_clip/__init__.py
  tests/unittests/models/action_clip/test_action_clip.py
  towhee/models/action_clip/__init__.py
  towhee/models/action_clip/visual_prompt.py
Labels: lgtm, size/L, approved, component/models

#1169 Update quick start for v0.6
  docs/01-Overview.md
  docs/02-Getting started/quick-start.mdx
Labels: lgtm, approved, size/M

#1170 Fix broken links in overview
  docs/01-Overview.md
Labels: lgtm, approved, size/S

#1172 Fix links from bad capitalization
  docs/01-Overview.md
Labels: lgtm, approved, size/XS
