Repository towhee-io/towhee, pull requests merged in 2023-01, with the labels that each got.

#2366 Update filter parameters in dag
  tests/unittests/functional/test_mixins.py
  tests/unittests/runtime/test_dag_repr.py
  towhee/runtime/dag_repr.py
  towhee/runtime/pipeline.py
Labels: lgtm, approved, size/M

#2367 Add built-in pipeline video copy detection
  tests/unittests/runtime/test_pipeline.py
  tests/unittests/runtime/test_window_all.py
  towhee/pipelines/video_copy.py
  towhee/runtime/schema_repr.py
Labels: lgtm, size/L, approved

#2371 fix example clip version
  README.md
Labels: lgtm, approved, size/XS

#2370 Add new pipelines
  .coveragerc
  tests/unittests/triton/test_pipeline_client.py
  towhee/pipelines/insert_milvus.py
  towhee/pipelines/search_milvus.py
  towhee/pipelines/sentence_embedding.py
  towhee/pipelines/sentence_similarity.py
  towhee/pipelines/text_image_embedding.py
  towhee/serve/triton/model_to_triton.py
  towhee/serve/triton/pipeline_client.py
Labels: lgtm, size/L, approved
