Repository towhee-io/towhee, pull requests merged in 2023-07, with the labels that each got.

#2602 Add serve docs
  tests/unittests/serve/grpc/test_server.py
  towhee/serve/api_service.py
  towhee/serve/grpc/server.py
  towhee/serve/http/server.py
  towhee/serve/io/bytes_io.py
  towhee/serve/io/json_io.py
  towhee/serve/io/ndarray_io.py
  towhee/serve/io/text_io.py
Labels: lgtm, size/L, approved

#2604 Limit pydantic version
  requirements.txt
  test_requirements.txt
Labels: lgtm, approved, size/XS

#2605 Limit pydantic version
  requirements.txt
  test_requirements.txt
Labels: lgtm, approved, size/XS

#2603 Support building service from repo
  tests/unittests/command/test_cmdline.py
  towhee/command/README.md
  towhee/command/service.py
Labels: lgtm, size/L, approved

#2607 Update release version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#2606 Update release version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#2608 Add serving docs
  tests/unittests/serve/http/test_http.py
  towhee/doc/source/index.rst
  towhee/doc/source/serving/api.rst
  towhee/doc/source/serving/index.rst
  towhee/doc/source/serving/usage.md
  towhee/serve/api_service.py
  towhee/serve/io/bytes_io.py
  towhee/serve/io/json_io.py
  towhee/serve/io/ndarray_io.py
  towhee/serve/io/text_io.py
  towhee/serve/server_builder.py
Labels: lgtm, size/L, approved

#2609 Limit pydantic<2
  towhee/doc/requirements.txt
Labels: lgtm, approved, size/XS

#2615 Add data_source docs
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/data_source.py
  towhee/runtime/hub_ops/image_decode.py
  towhee/runtime/hub_ops/operator_parser.py
Labels: lgtm, size/L, approved

#2616 Add ann insert docs
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/ann_insert.py
  towhee/runtime/hub_ops/data_source.py
  towhee/runtime/hub_ops/image_decode.py
  towhee/runtime/hub_ops/image_embedding.py
  towhee/runtime/hub_ops/operator_parser.py
  towhee/runtime/hub_ops/sentence_embedding.py
Labels: lgtm, size/L, approved

#2618 Add ann search
  .github/workflows/codecov.yml
  Dockerfile
  GPUDockerfile
  tests/unittests/command/test_cmdline.py
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/ann_insert.py
  towhee/runtime/hub_ops/ann_search.py
  towhee/runtime/hub_ops/operator_parser.py
Labels: lgtm, size/L, approved

#2619 More hub op test & image-text-embedding docs
  tests/unittests/command/test_cmdline.py
  tests/unittests/runtime/test_hub_ops.py
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/ann_search.py
  towhee/runtime/hub_ops/image_text_embedding.py
  towhee/runtime/hub_ops/operator_parser.py
Labels: lgtm, size/L, approved

#2622 Add decoder docs
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/audio_decode.py
  towhee/runtime/hub_ops/operator_parser.py
  towhee/runtime/hub_ops/video_decode.py
Labels: lgtm, size/L, approved

#2623 Add object detection docs
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/object_detection.py
  towhee/runtime/hub_ops/operator_parser.py
Labels: lgtm, size/L, approved

#2624 docs for towhee namespace
  tests/unittests/runtime/test_hub_ops.py
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/operator_parser.py
  towhee/runtime/hub_ops/rerank.py
  towhee/runtime/hub_ops/utils.py
Labels: lgtm, size/L, approved

#2625 Add LLM docs
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/llm.py
  towhee/runtime/hub_ops/operator_parser.py
Labels: lgtm, size/L, approved

#2627 Add prompt docs
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/operator_parser.py
  towhee/runtime/hub_ops/prompt.py
Labels: lgtm, size/L, approved

#2626 Add data_loader docs
  towhee/doc/source/operator/hub_ops.rst
  towhee/runtime/hub_ops/data_loader.py
  towhee/runtime/hub_ops/operator_parser.py
Labels: lgtm, size/L, approved

#2630 Add html loader doc
  towhee/runtime/hub_ops/data_loader.py
Labels: lgtm, approved, size/M

#2632 Add notebook loader doc
  towhee/runtime/hub_ops/data_loader.py
Labels: lgtm, approved, size/M

#2633 Add powerpoint loader doc
  towhee/runtime/hub_ops/data_loader.py
Labels: lgtm, approved, size/S

#2634 Support uppercase for pipeline schema
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/check_utils.py
Labels: lgtm, approved, size/XS

#2636 Update readme
  README.md
  README_CN.md
Labels: lgtm, approved, size/XS

#2640 Optimize Towhee logging module
  tests/unittests/utils/test_log.py
  towhee/config/__init__.py
  towhee/config/log_config.py
  towhee/utils/log.py
Labels: lgtm, size/L, approved

#2643 Change Issue rule
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
Labels: lgtm, approved, size/XS
