Repository towhee-io/towhee, pull requests merged in 2023-02, with the labels that each got.

#2375 Get _hf_models by op attribute
  towhee/pipelines/sentence_embedding.py
Labels: lgtm, approved, size/S

#2378 Enhance trainer compatibility
  towhee/operator/base.py
Labels: lgtm, approved, size/XS

#2379 fix clip4clip data device
  towhee/models/clip4clip/clip4clip.py
Labels: lgtm, approved, size/XS

#2377 fix dc.show bug, show the real channel order
  towhee/datacollection/mixins/display.py
  towhee/runtime/nodes/_output.py
Labels: lgtm, approved, size/M

#2381 fix drl data device
  towhee/models/drl/drl.py
Labels: lgtm, approved, size/XS

#2382 Support config triton parallelism
  tests/unittests/runtime/builtin_pipeline.py
  tests/unittests/triton/test_pipe_to_triton.py
  towhee/pipelines/_builtin_pipeline.py
  towhee/serve/server_builder.py
  towhee/serve/triton/constant.py
  towhee/serve/triton/pipe_to_triton.py
  towhee/serve/triton/pipeline_builder.py
Labels: lgtm, approved, size/M

#2385 Support cloud
  towhee/hub/file_manager.py
  towhee/pipelines/insert_milvus.py
  towhee/pipelines/search_milvus.py
Labels: lgtm, approved, size/M

#2388 Pipes optimize
  tests/unittests/runtime/test_data_queue.py
  tests/unittests/triton/test_model_to_triton.py
  towhee/pipelines/search_milvus.py
  towhee/pipelines/sentence_embedding.py
  towhee/pipelines/text_image_embedding.py
  towhee/runtime/data_queue.py
  towhee/serve/triton/model_to_triton.py
Labels: lgtm, size/L, approved

#2389 Replace with sentence_embedding.openai
  towhee/pipelines/sentence_embedding.py
Labels: lgtm, approved, size/XS

#2396 Set recurse to True for dump
  towhee/serve/triton/docker_image_builder_v2.py
Labels: lgtm, approved, size/XS

#2399 Code polish
  tests/unittests/functional/test_mixins.py
  tests/unittests/mock_operators/trion_nnop_oldversion/triton_nnop.py
  tests/unittests/mock_operators/triton_nnop/preprocess.py
  tests/unittests/mock_operators/triton_nnop/triton_nnop.py
  tests/unittests/mock_operators/triton_py/triton_py.py
  tests/unittests/triton/expected_files/clip_preprocess_model.py
  tests/unittests/triton/expected_files/preprocess/1/model.py
  tests/unittests/triton/expected_files/resnet50_model.py
  tests/unittests/triton/test_pipeline_builder.py
  tests/unittests/triton/test_pipeline_client.py
  tests/unittests/triton/test_python_model_builder.py
  tests/unittests/triton/test_triton_config_builder.py
  tests/unittests/types/test_image.py
  towhee/__init__.py
  towhee/_types/__init__.py
  towhee/_types/image.py
  towhee/functional/mixins/display.py
  towhee/serve/triton/docker_image_builder_v2.py
  towhee/serve/triton/pipe_to_triton.py
  towhee/serve/triton/pipeline_builder.py
  towhee/serve/triton/type_gen.py
  towhee/types/__init__.py
  towhee/utils/thirdparty/dill_util.py
Labels: lgtm, approved, size/M

#2406 Built-in pipeline use normalize op
  towhee/pipelines/sentence_embedding.py
  towhee/pipelines/text_image_embedding.py
Labels: lgtm, approved, size/S

#2409 fix err info
  towhee/pipelines/sentence_embedding.py
  towhee/pipelines/text_image_embedding.py
  towhee/runtime/auto_config.py
  towhee/runtime/auto_pipes.py
Labels: lgtm, approved, size/XS

#2410 change DDP to DP when parallel training
  towhee/trainer/metrics.py
  towhee/trainer/trainer.py
  towhee/trainer/training_config.py
Labels: lgtm, size/L, approved

#2372 Optimize and reorganize built-in Video Copy Pipeline
  tests/unittests/functional/test_mixins.py
  towhee/functional/mixins/__init__.py
  towhee/functional/mixins/kv_storage.py
  towhee/pipelines/video_copy.py
  towhee/pipelines/video_copy_detection.py
  towhee/pipelines/video_embedding.py
  towhee/serve/triton/dockerfiles/DockerfileCuda117dev
  towhee/utils/thirdparty/plyvel_utils.py
Labels: lgtm, approved, size/XL

#2414 Fix dag issue about concat node
  tests/unittests/runtime/test_dag_repr.py
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/dag_repr.py
  towhee/runtime/schema_repr.py
Labels: lgtm, size/L, approved

#2422 change np.long to np.int32
  towhee/models/clip4clip/utils.py
Labels: lgtm, approved, size/XS

#2426 assert torchmetrics version
  towhee/trainer/__init__.py
Labels: lgtm, approved, size/XS

#2427 Add output for insert_milvus pipeline
  towhee/pipelines/insert_milvus.py
Labels: lgtm, approved, size/XS

#2431 Update supported model
  towhee/pipelines/video_copy_detection.py
  towhee/pipelines/video_embedding.py
Labels: lgtm, approved, size/XS

#2433 Update video copy pipeline model
  towhee/pipelines/video_copy_detection.py
  towhee/pipelines/video_embedding.py
Labels: lgtm, approved, size/S

#2437 Remove id column from video embedding
  towhee/pipelines/video_embedding.py
Labels: lgtm, approved, size/S

#2442 Validate start time and end time for decoder
  towhee/pipelines/video_copy_detection.py
  towhee/pipelines/video_embedding.py
Labels: lgtm, approved, size/XS
