Repository towhee-io/towhee, pull requests merged in 2023-04, with the labels that each got.

#2501 Add tracer in debug
  tests/unittests/runtime/test_runtime_pipeline.py
  tests/unittests/tools/test_data_visualizer.py
  tests/unittests/tools/test_visualizer.py
  towhee/runtime/runtime_pipeline.py
  towhee/tools/data_visualizer.py
  towhee/tools/profilers.py
  towhee/tools/visualizer.py
Labels: lgtm, approved, size/XL

#2507 Fix codecov not found
  .github/workflows/codecov.yml
Labels: lgtm, approved, size/XS

#2506 Json serialize visualizer with tracer
  tests/unittests/tools/test_visualizer.py
  towhee/datacollection/data_collection.py
  towhee/tools/visualizer.py
Labels: lgtm, approved, size/M

#2512 Fix reset_size drops rows contain Empty() issue
  towhee/runtime/data_queue.py
Labels: lgtm, approved, size/XS
