Repository towhee-io/towhee, pull requests merged in 2023-03, with the labels that each got.

#2398 Modify weekly test script
  tests/testcases/hub/execute_hub_operators.py
  tests/testcases/test_data_collection.py
Labels: lgtm, approved, size/S

#2443 Update towhee and towhee.models version
  tests/testcases/requirements.text
Labels: lgtm, approved, size/XS

#2447 DataCollection handle empty DataQueue
  tests/unittests/datacollection/test_data_collection.py
  towhee/datacollection/mixins/display.py
Labels: lgtm, approved, size/M

#2448 DataCollection handle empty DataQueue
  tests/unittests/datacollection/test_data_collection.py
  towhee/datacollection/mixins/display.py
Labels: lgtm, approved, size/M

#2450 fix side by cols err
  tests/unittests/runtime/test_user_pipeline.py
  towhee/hub/cache_manager.py
  towhee/runtime/nodes/_filter.py
  towhee/runtime/nodes/_flat_map.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/nodes/_time_window.py
  towhee/runtime/nodes/_window.py
  towhee/runtime/nodes/_window_all.py
Labels: lgtm, size/L, approved

#2452 Fix side_by_col err
  tests/unittests/runtime/test_user_pipeline.py
  towhee/hub/cache_manager.py
  towhee/runtime/nodes/_filter.py
  towhee/runtime/nodes/_flat_map.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/nodes/_time_window.py
  towhee/runtime/nodes/_window.py
  towhee/runtime/nodes/_window_all.py
Labels: lgtm, size/L, approved

#2453 Update SchemaRepr in dag
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/dag_repr.py
Labels: lgtm, approved, size/S

#2454 Update SchemaRepr in dag
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/dag_repr.py
Labels: lgtm, approved, size/S

#2455 Redefine profiler API
  tests/unittests/runtime/test_performance_tracer.py
  towhee/pipelines/video_copy_detection.py
  towhee/pipelines/video_embedding.py
  towhee/runtime/constants.py
  towhee/runtime/pipeline.py
  towhee/runtime/runtime_pipeline.py
Labels: lgtm, size/L, approved

#2460 Fix used schema with outputs
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/dag_repr.py
Labels: lgtm, approved, size/S

#2461 Fix used schema with outputs
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/dag_repr.py
Labels: lgtm, approved, size/S

#2463 repair device in test_clip4clip
  tests/unittests/models/clip4clip/test_clip4clip.py
Labels: lgtm, approved, size/XS

#2464 repair device in test_clip4clip
  tests/unittests/models/clip4clip/test_clip4clip.py
Labels: lgtm, approved, size/XS

#2465 Fix device issue of ut for convnext, hornet, mcprop
  tests/unittests/models/convnext/test_utils.py
  tests/unittests/models/hornet/test_utils.py
  tests/unittests/models/mcprop/test_imageextractor.py
  tests/unittests/models/mcprop/test_matcher.py
Labels: lgtm, approved, size/S

#2466 Fix device issue for ut of convnext, hornet, mcprop
  tests/unittests/models/convnext/test_utils.py
  tests/unittests/models/hornet/test_utils.py
  tests/unittests/models/mcprop/test_imageextractor.py
  tests/unittests/models/mcprop/test_matcher.py
Labels: lgtm, approved, size/S

#2462 Rebuild dag with pipelines
  tests/unittests/runtime/test_dag_pipeline.py
  tests/unittests/runtime/test_dag_repr.py
  tests/unittests/runtime/test_nodes.py
  tests/unittests/runtime/test_pipeline.py
  tests/unittests/runtime/test_runtime_pipeline.py
  tests/unittests/runtime/test_user_pipeline.py
  tests/unittests/triton/test_pipeline_builder.py
  towhee/runtime/constants.py
  towhee/runtime/dag_repr.py
  towhee/runtime/node_repr.py
  towhee/runtime/nodes/node.py
  towhee/runtime/operator_manager/operator_action.py
  towhee/runtime/operator_manager/operator_loader.py
  towhee/runtime/pipeline.py
Labels: lgtm, approved, size/XL

#2468 Update triton_builder cmd
  setup.py
  towhee/serve/triton/dockerfiles/DockerfileCuda113
  towhee/serve/triton/dockerfiles/DockerfileCuda114
  towhee/serve/triton/dockerfiles/DockerfileCuda116
  towhee/serve/triton/dockerfiles/DockerfileCuda117dev
  towhee/serve/triton/model_to_triton.py
  towhee/serve/triton/pipe_to_triton.py
Labels: lgtm, approved, size/S

#2467 Delete dc2 in test cases
  tests/testcases/requirements.text
  tests/testcases/test_audio_embedding.py
  tests/testcases/test_data_collection.py
  tests/testcases/test_image_embedding.py
  tests/testcases/test_main.py
  tests/testcases/test_pipeline.py
Labels: lgtm, size/L, approved

#2472 Reformat display table
  towhee/datacollection/mixins/display.py
  towhee/tools/graph_visualizer.py
Labels: lgtm, approved, size/S

#2473 Json serialize dag repr
  tests/unittests/runtime/test_dag_repr.py
  towhee/runtime/dag_repr.py
Labels: lgtm, size/L, approved

#2475 Display dag nodes in topological order
  towhee/tools/graph_visualizer.py
Labels: lgtm, approved, size/XS

#2476 Rename the node with pipeline
  tests/unittests/runtime/test_dag_repr.py
  towhee/runtime/dag_repr.py
  towhee/runtime/operator_manager/operator_action.py
  towhee/tools/graph_visualizer.py
Labels: lgtm, approved, size/M

#2477 Update towhee version
  tests/testcases/requirements.text
Labels: lgtm, approved, size/XS

#2480 Add revision and get_latest for operator
  tests/unittests/hub/test_cache_manager.py
  tests/unittests/runtime/test_factory.py
  tests/unittests/runtime/test_operator_action.py
  tests/unittests/runtime/test_operator_pool.py
  tests/unittests/runtime/test_user_pipeline.py
  towhee/hub/__init__.py
  towhee/hub/cache_manager.py
  towhee/hub/downloader.py
  towhee/runtime/factory.py
  towhee/runtime/node_repr.py
  towhee/runtime/nodes/node.py
  towhee/runtime/operator_manager/operator_action.py
  towhee/runtime/operator_manager/operator_loader.py
  towhee/runtime/operator_manager/operator_pool.py
  towhee/runtime/pipeline.py
Labels: lgtm, size/L, approved

#2479 DataQueue support debug
  tests/unittests/runtime/test_data_queue.py
  towhee/runtime/data_queue.py
Labels: lgtm, size/L, approved

#2485 Fix download error in windows
  tests/unittests/hub/test_downloader.py
  towhee/hub/downloader.py
Labels: lgtm, approved, size/S

#2487 Update triton README
  towhee/serve/triton/README.md
Labels: lgtm, size/L, approved

#2488 Update triton README
  towhee/serve/triton/README.md
Labels: lgtm, size/L, approved

#2486 Update op modname with tag
  tests/unittests/runtime/test_operator_loader.py
  towhee/runtime/operator_manager/operator_loader.py
Labels: lgtm, approved, size/S

#2483 Support AutoPipes and AutoConfig from hub
  tests/unittests/__init__.py
  tests/unittests/hub/test_cache_manager.py
  tests/unittests/hub/test_downloader.py
  tests/unittests/mock_pipelines/ci_test2/ci_test2.py
  tests/unittests/runtime/test_autos.py
  towhee/hub/__init__.py
  towhee/hub/cache_manager.py
  towhee/hub/downloader.py
  towhee/runtime/pipeline_loader.py
Labels: lgtm, size/L, approved

#2489 Wrap debug return values
  tests/unittests/tools/test_data_visualizer.py
  tests/unittests/tools/test_performance_profiler.py
  tests/unittests/tools/test_visualizer.py
  towhee/runtime/nodes/_concat.py
  towhee/runtime/nodes/_filter.py
  towhee/runtime/nodes/_flat_map.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/nodes/_output.py
  towhee/runtime/nodes/_window.py
  towhee/runtime/nodes/_window_all.py
  towhee/runtime/nodes/node.py
  towhee/runtime/runtime_pipeline.py
  towhee/runtime/time_profiler.py
  towhee/tools/__init__.py
  towhee/tools/data_visualizer.py
  towhee/tools/profilers.py
  towhee/tools/visualizer.py
Labels: lgtm, size/L, approved

#2497 Add reduce node
  tests/unittests/mock_operators/reduce_op/__init__.py
  tests/unittests/mock_operators/reduce_op/sum_operator.py
  tests/unittests/runtime/test_dag_pipeline.py
  tests/unittests/runtime/test_reduce.py
  tests/unittests/runtime/test_user_pipeline.py
  towhee/runtime/constants.py
  towhee/runtime/dag_repr.py
  towhee/runtime/nodes/__init__.py
  towhee/runtime/nodes/_concat.py
  towhee/runtime/nodes/_filter.py
  towhee/runtime/nodes/_flat_map.py
  towhee/runtime/nodes/_map.py
  towhee/runtime/nodes/_output.py
  towhee/runtime/nodes/_reduce.py
  towhee/runtime/nodes/_single_input.py
  towhee/runtime/nodes/_window_all.py
  towhee/runtime/nodes/_window_base.py
  towhee/runtime/nodes/node.py
  towhee/runtime/pipeline.py
  towhee/runtime/runtime_pipeline.py
  towhee/runtime/schema_repr.py
Labels: lgtm, approved, size/XL
