Repository towhee-io/towhee, pull requests merged in 2023-05, with the labels that each got.

#2514 Update towhee version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#2517 Update towhee version
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#2516 Update readme example
  README.md
  README_CN.md
Labels: lgtm, size/L, approved

#2521 Add data loader
  tests/unittests/mock_operators/data_source_op/__init__.py
  tests/unittests/mock_operators/data_source_op/ds.py
  tests/unittests/models/violet/test_violet.py
  tests/unittests/test_data_loader.py
  towhee/__init__.py
  towhee/data_loader.py
  towhee/operator/base.py
  towhee/operator/concat_operator.py
Labels: lgtm, size/L, approved

#2523 Update readme
  README.md
  README_CN.md
Labels: lgtm, approved, size/XS

#2524 Add readem pic
  assets/dog1.png
  assets/dog2.png
  assets/dog3.png
Labels: lgtm, approved, size/XS

#2525 Update readme demo
  README.md
  README_CN.md
Labels: lgtm, approved, size/S

#2527 Update api docs
  towhee/doc/requirements.txt
  towhee/doc/source/GPU/GPU.md
  towhee/doc/source/GPU/index.rst
  towhee/doc/source/api.rst
  towhee/doc/source/benchmark/column-based-benchmark-report.md
  towhee/doc/source/builtin operators/computer vision.rst
  towhee/doc/source/builtin operators/feature engineer.rst
  towhee/doc/source/builtin operators/index.rst
  towhee/doc/source/builtin operators/milvus search.rst
  towhee/doc/source/builtin operators/runas op.rst
  towhee/doc/source/builtin operators/sklearn.rst
  towhee/doc/source/builtin operators/tensor like.rst
  towhee/doc/source/conf.py
  towhee/doc/source/data_collection/get_started.rst
  towhee/doc/source/data_collection/index.rst
  towhee/doc/source/data_collection/mixins.rst
  towhee/doc/source/data_collection/option.rst
  towhee/doc/source/index.rst
  towhee/doc/source/operator/api.rst
  towhee/doc/source/operator/index.rst
  towhee/doc/source/operator/operator_base.rst
  towhee/doc/source/operator/usage.md
  towhee/doc/source/pipeline/api.rst
  towhee/doc/source/pipeline/index.rst
  towhee/doc/source/pipeline/usage.md
  towhee/doc/source/towhee/towhee.rst
  towhee/doc/source/towhee/towhee_operator.rst
  towhee/doc/source/trainer/index.rst
  towhee/doc/source/triton/index.rst
  towhee/doc/source/triton/qps.png
  towhee/doc/source/triton/triton.md
  towhee/doc/source/user_guide/10-minutes-to-data-collection.md
  towhee/doc/source/user_guide/10-minutes-to-towhee.md
  towhee/doc/source/user_guide/concat_node.png
  towhee/doc/source/user_guide/filter_node.png
  towhee/doc/source/user_guide/flat_map_node.png
  towhee/doc/source/user_guide/index.rst
  towhee/doc/source/user_guide/map_node.png
  towhee/doc/source/user_guide/readme.md
  towhee/doc/source/user_guide/time_window_node.png
  towhee/doc/source/user_guide/window_all.png
  towhee/doc/source/user_guide/window_node.png
Labels: lgtm, approved, size/XXL

#2528 Add docs link in README
  README.md
  README_CN.md
Labels: lgtm, approved, size/S

#2520 Update towhee version
  tests/testcases/requirements.text
Labels: lgtm, approved, size/XS

#2529 Optimize visualizer in cmdline.
  tests/unittests/triton/bls/test_pipeline_model.py
  tests/unittests/triton/test_pipe_to_triton.py
  tests/unittests/utils/test_np_format.py
  tests/unittests/utils/test_serializer.py
  towhee/datacollection/mixins/display.py
  towhee/serve/triton/bls/pipeline_model.py
  towhee/serve/triton/pipeline_client.py
  towhee/tools/data_visualizer.py
  towhee/tools/visualizer.py
  towhee/utils/serializer.py
Labels: lgtm, size/L, approved

#2530 add trainer doc
  towhee/doc/source/trainer/class_operator.png
  towhee/doc/source/trainer/index.rst
  towhee/doc/source/trainer/tensorboard.png
  towhee/doc/source/trainer/towhee_trainer_framework.png
  towhee/doc/source/trainer/trainer.md
  towhee/doc/source/trainer/trainer.optimization.rst
  towhee/doc/source/trainer/trainer.rst
  towhee/doc/source/trainer/trainer.utils.rst
Labels: lgtm, approved, size/XL

#2531 Optimize html Display
  towhee/datacollection/mixins/display.py
  towhee/runtime/dag_repr.py
  towhee/tools/data_visualizer.py
  towhee/utils/console_table.py
  towhee/utils/empty_format.py
  towhee/utils/html_table.py
  towhee/utils/np_format.py
  towhee/utils/serializer.py
Labels: lgtm, approved, size/XL

#2532 Update api docs
  towhee/doc/requirements.txt
  towhee/doc/source/GPU/GPU.md
  towhee/doc/source/GPU/index.rst
  towhee/doc/source/api.rst
  towhee/doc/source/benchmark/column-based-benchmark-report.md
  towhee/doc/source/builtin operators/computer vision.rst
  towhee/doc/source/builtin operators/feature engineer.rst
  towhee/doc/source/builtin operators/index.rst
  towhee/doc/source/builtin operators/milvus search.rst
  towhee/doc/source/builtin operators/runas op.rst
  towhee/doc/source/builtin operators/sklearn.rst
  towhee/doc/source/builtin operators/tensor like.rst
  towhee/doc/source/conf.py
  towhee/doc/source/data_collection/get_started.rst
  towhee/doc/source/data_collection/index.rst
  towhee/doc/source/data_collection/mixins.rst
  towhee/doc/source/data_collection/option.rst
  towhee/doc/source/index.rst
  towhee/doc/source/operator/api.rst
  towhee/doc/source/operator/index.rst
  towhee/doc/source/operator/operator_base.rst
  towhee/doc/source/operator/usage.md
  towhee/doc/source/pipeline/api.rst
  towhee/doc/source/pipeline/index.rst
  towhee/doc/source/pipeline/usage.md
  towhee/doc/source/towhee/towhee.rst
  towhee/doc/source/towhee/towhee_operator.rst
  towhee/doc/source/trainer/index.rst
  towhee/doc/source/triton/index.rst
  towhee/doc/source/triton/qps.png
  towhee/doc/source/triton/triton.md
  towhee/doc/source/user_guide/10-minutes-to-data-collection.md
  towhee/doc/source/user_guide/10-minutes-to-towhee.md
  towhee/doc/source/user_guide/concat_node.png
  towhee/doc/source/user_guide/filter_node.png
  towhee/doc/source/user_guide/flat_map_node.png
  towhee/doc/source/user_guide/index.rst
  towhee/doc/source/user_guide/map_node.png
  towhee/doc/source/user_guide/readme.md
  towhee/doc/source/user_guide/time_window_node.png
  towhee/doc/source/user_guide/window_all.png
  towhee/doc/source/user_guide/window_node.png
Labels: lgtm, approved, size/XXL

#2533 Add trainer docs
  tests/unittests/models/violet/test_violet.py
  towhee/doc/source/trainer/class_operator.png
  towhee/doc/source/trainer/index.rst
  towhee/doc/source/trainer/tensorboard.png
  towhee/doc/source/trainer/towhee_trainer_framework.png
  towhee/doc/source/trainer/trainer.md
  towhee/doc/source/trainer/trainer.optimization.rst
  towhee/doc/source/trainer/trainer.rst
  towhee/doc/source/trainer/trainer.utils.rst
Labels: lgtm, approved, size/XL

#2535 add license
  towhee/data/dataset/dataset.py
  towhee/models/clip/auxilary.py
  towhee/models/clip4clip/utils.py
  towhee/models/drl/drl.py
  towhee/models/drl/module_cross.py
  towhee/models/layers/non_local.py
  towhee/models/layers/patch_embed3d.py
  towhee/models/layers/patch_merging3d.py
  towhee/models/layers/swin_transformer_block3d.py
  towhee/models/layers/window_attention3d.py
  towhee/models/utils/get_window_size.py
  towhee/models/utils/window_partition.py
  towhee/models/utils/window_partition3d.py
  towhee/models/utils/window_reverse.py
  towhee/models/utils/window_reverse3d.py
  towhee/trainer/utils/file_utils.py
  towhee/trainer/utils/layer_freezer.py
Labels: lgtm, size/L, approved

#2536 Fix several licenses for imported code.
  towhee/models/retina_face/configs.py
  towhee/models/retina_face/heads.py
  towhee/models/retina_face/mobilenet_v1.py
  towhee/models/retina_face/prior_box.py
  towhee/models/retina_face/retinaface.py
  towhee/models/retina_face/retinaface_fpn.py
  towhee/models/retina_face/ssh.py
  towhee/models/retina_face/utils.py
  towhee/models/swin_transformer/configs.py
  towhee/models/utils/pretrained_utils.py
Labels: lgtm, size/L, approved

#2537 Remove useless mock ops
  tests/unittests/mock_operators/trion_nnop_oldversion/__init__.py
  tests/unittests/mock_operators/trion_nnop_oldversion/triton_nnop.py
  tests/unittests/mock_operators/triton_nnop/__init__.py
  tests/unittests/mock_operators/triton_nnop/model.py
  tests/unittests/mock_operators/triton_nnop/postprocess.py
  tests/unittests/mock_operators/triton_nnop/preprocess.py
  tests/unittests/mock_operators/triton_nnop/triton_nnop.py
  tests/unittests/mock_operators/triton_py/__init__.py
  tests/unittests/mock_operators/triton_py/triton_py.py
  tests/unittests/mock_operators/zero_drop/zero_drop.py
  tests/unittests/mock_pipelines/ci_test2/ci_test2.py
  tests/unittests/mock_pipelines/resnet50_embedding/resnet50_embedding.yaml
Labels: lgtm, size/L, approved

#2540 Add License Information
  tests/testcases/test_audio_embedding.py
  tests/testcases/test_command.py
  tests/testcases/test_dag_info.py
  tests/testcases/test_data_collection.py
  tests/testcases/test_image_embedding.py
  tests/testcases/test_main.py
  tests/testcases/test_pipeline.py
Labels: lgtm, size/L, approved

#2539 Add retry when downloading ops
  requirements.txt
  test_requirements.txt
  towhee/hub/downloader.py
  towhee/runtime/operator_manager/operator_loader.py
Labels: lgtm, approved, size/S

#2541 Update README_CN.md
  README_CN.md
Labels: lgtm, approved, size/XS

#2543 Update 10-minutes-to-towhee.md
  towhee/doc/source/user_guide/10-minutes-to-towhee.md
Labels: lgtm, approved, size/XS

#2545 Polish DagRepr
  requirements.txt
  test_requirements.txt
  tests/unittests/runtime/test_concat.py
  tests/unittests/runtime/test_config.py
  tests/unittests/runtime/test_filter_node.py
  tests/unittests/runtime/test_flat_map_node.py
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_node_repr.py
  tests/unittests/runtime/test_reduce.py
  tests/unittests/runtime/test_runtime_config.py
  tests/unittests/runtime/test_time_window_node.py
  tests/unittests/runtime/test_window_all.py
  tests/unittests/runtime/test_window_node.py
  tests/unittests/triton/test_model_to_triton.py
  tests/unittests/triton/test_pipeline_builder.py
  towhee/runtime/auto_config.py
  towhee/runtime/dag_repr.py
  towhee/runtime/node_config.py
  towhee/runtime/node_repr.py
  towhee/runtime/runtime_conf.py
  towhee/runtime/schema_repr.py
  towhee/serve/triton/model_to_triton.py
  towhee/serve/triton/pipeline_builder.py
Labels: lgtm, approved, size/XL

#2547 Update with basemodel
  tests/unittests/runtime/test_check_util.py
  tests/unittests/runtime/test_dag_repr.py
  towhee/runtime/check_utils.py
  towhee/runtime/dag_repr.py
  towhee/runtime/pipeline.py
Labels: lgtm, size/L, approved

#2550 Update docs
  docs/01-Overview.md
  docs/02-Getting Started/01-quick-start.mdx
  docs/02-Getting Started/02-install.md
  docs/02-Getting Started/03-create-pipeline.md
  docs/02-Getting Started/04-troubleshooting.md
  docs/02-Getting Started/quick-start.ipynb
  docs/02-Getting Started/towhee.jpeg
  docs/03-User Guides/01-Pipeline Programing Guide/01-node-types.md
  docs/03-User Guides/01-Pipeline Programing Guide/02-map.md
  docs/03-User Guides/01-Pipeline Programing Guide/03-flat-map.md
  docs/03-User Guides/01-Pipeline Programing Guide/04-filter.md
  docs/03-User Guides/01-Pipeline Programing Guide/05-window.md
  docs/03-User Guides/01-Pipeline Programing Guide/06-time-window.md
  docs/03-User Guides/01-Pipeline Programing Guide/07-window-all.md
  docs/03-User Guides/01-Pipeline Programing Guide/08-concat.md
  docs/03-User Guides/01-command-line-tool.md
  docs/03-User Guides/02-DataCollection/01-data-collection.md
  docs/03-User Guides/02-DataCollection/02-data-collection-with-ray.md
  docs/03-User Guides/03-Built-in Pipelines/audio-embedding.md
  docs/03-User Guides/03-Built-in Pipelines/image-embedding.md
  docs/04-API Reference/01-Pipeline API/01-input.md
  docs/04-API Reference/01-Pipeline API/02-output.md
  docs/04-API Reference/01-Pipeline API/03-map.md
  docs/04-API Reference/01-Pipeline API/04-flat-map.md
  docs/04-API Reference/01-Pipeline API/05-filter.md
  docs/04-API Reference/01-Pipeline API/06-window.md
  docs/04-API Reference/01-Pipeline API/07-time-window.md
  docs/04-API Reference/01-Pipeline API/08-window-all.md
  docs/04-API Reference/01-Pipeline API/09-concat.md
  docs/04-API Reference/01-Pipeline API/10-batch.md
  docs/04-API Reference/02-AutoConfig API/01-LocalCPUConfig.md
  docs/04-API Reference/02-AutoConfig API/02-LocalGPUConfig.md
  docs/04-API Reference/02-AutoConfig API/03-TritonCPUConfig.md
  docs/04-API Reference/02-AutoConfig API/04-TritonGPUConfig.md
  docs/04-API Reference/02-AutoConfig API/05-load-config.md
  docs/04-Developer Guides/Google Summer of Code/gsoc-2022.md
  docs/04-Developer Guides/Model Building Blocks/swin_arch.png
  docs/05-Developer Guides/01-contributing-guide.md
  docs/05-Developer Guides/02-adding-new-doc.md
  docs/05-Developer Guides/Model Building Blocks/layers-overview.md
  docs/05-Release Notes/release-notes-040.md
  docs/05-Release Notes/release-notes-050.md
  docs/05-Release Notes/release-notes-060.md
  docs/06-Release Notes.md
Labels: lgtm, approved, size/XXL

#2551 Update docs action
  .github/workflows/check-docs-update.yml
Labels: lgtm, approved, size/XS

#2552 Update docs and ut
  docs/02-Getting Started/01-quick-start.mdx
  docs/02-Getting Started/03-create-pipeline.md
  docs/03-User Guides/01-Pipeline Programing Guide/01-node-types.md
  docs/03-User Guides/01-Pipeline Programing Guide/02-map.md
  docs/03-User Guides/01-Pipeline Programing Guide/03-flat-map.md
  docs/03-User Guides/01-Pipeline Programing Guide/04-filter.md
  docs/03-User Guides/01-Pipeline Programing Guide/05-window.md
  docs/03-User Guides/01-Pipeline Programing Guide/06-time-window.md
  docs/03-User Guides/01-Pipeline Programing Guide/07-window-all.md
  docs/03-User Guides/01-Pipeline Programing Guide/08-concat.md
  docs/06-Release Notes.md
  tests/unittests/documents/__init__.py
  tests/unittests/documents/test_dc_get_started.py
Labels: lgtm, approved, size/M

#2554 Fix typo in dockerfile
  towhee/serve/triton/dockerfiles/DockerfileCuda117
Labels: lgtm, approved, size/XS

#2549 Add docstring for triton functions and update docs
  towhee/__init__.py
  towhee/doc/source/triton/triton.md
  towhee/serve/server_builder.py
  towhee/serve/triton/README.md
Labels: lgtm, size/L, approved

#2557 Add triton docs and fix false link
  docs/01-Overview.md
  docs/03-User Guides/01-Pipeline Programing Guide/01-node-types.md
  docs/03-User Guides/01-Pipeline Programing Guide/02-map.md
  docs/03-User Guides/01-Pipeline Programing Guide/03-flat-map.md
  docs/03-User Guides/01-Pipeline Programing Guide/04-filter.md
  docs/03-User Guides/01-Pipeline Programing Guide/05-window.md
  docs/03-User Guides/01-Pipeline Programing Guide/06-time-window.md
  docs/03-User Guides/01-Pipeline Programing Guide/07-window-all.md
  docs/03-User Guides/01-Pipeline Programing Guide/08-concat.md
  docs/04-Triton Server/qps.png
  docs/04-Triton Server/triton.md
  docs/05-API Reference/01-Pipeline API/01-input.md
  docs/05-API Reference/01-Pipeline API/02-output.md
  docs/05-API Reference/01-Pipeline API/03-map.md
  docs/05-API Reference/01-Pipeline API/04-flat-map.md
  docs/05-API Reference/01-Pipeline API/05-filter.md
  docs/05-API Reference/01-Pipeline API/06-window.md
  docs/05-API Reference/01-Pipeline API/07-time-window.md
  docs/05-API Reference/01-Pipeline API/08-window-all.md
  docs/05-API Reference/01-Pipeline API/09-concat.md
  docs/05-API Reference/01-Pipeline API/10-batch.md
  docs/05-API Reference/02-AutoConfig API/01-LocalCPUConfig.md
  docs/05-API Reference/02-AutoConfig API/02-LocalGPUConfig.md
  docs/05-API Reference/02-AutoConfig API/03-TritonCPUConfig.md
  docs/05-API Reference/02-AutoConfig API/04-TritonGPUConfig.md
  docs/05-API Reference/02-AutoConfig API/05-load-config.md
  docs/06-Developer Guides/01-contributing-guide.md
  docs/06-Developer Guides/02-adding-new-doc.md
  docs/06-Developer Guides/Model Building Blocks/layers-overview.md
  docs/07-Release Notes.md
Labels: lgtm, size/L, approved

#2558 Fix docs
  towhee/doc/source/user_guide/10-minutes-to-towhee.md
  towhee/doc/source/user_guide/readme.md
Labels: lgtm, approved, size/S

#2559 Update towhee version for 1.0.0
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#2560 Update towhee version for 1.0.0
  setup.cfg
  setup.py
Labels: lgtm, approved, size/XS

#2556 Update docs for 1.0
  docs/02-Getting Started/01-quick-start.mdx
  docs/02-Getting Started/02-install.md
  docs/03-User Guides/01-Pipeline Programing Guide/02-map.md
  docs/04-Triton Server/01-triton.md
  docs/07-Release Notes.md
Labels: lgtm, approved, size/M

#2562 Update owner
  OWNERS
Labels: lgtm, approved, size/XS

#2563 Update triton server version
  .github/workflows/codecov.yml
  README.md
  README_CN.md
  docs/02-Getting Started/01-quick-start.mdx
  docs/04-Triton Server/01-triton.md
  tests/testcases/requirements.text
  towhee/doc/source/triton/triton.md
  towhee/serve/triton/README.md
Labels: lgtm, approved, size/M

#2564 Update docs to publish
  docs/04-Triton Server/01-triton.md
Labels: lgtm, approved, size/XS

#2565 Update docs to publish
  docs/04-Triton Server/01-triton.md
Labels: lgtm, approved, size/XS

#2566 Fix docs to publish
  docs/01-Overview.md
Labels: lgtm, approved, size/XS

#2567 Update README
  README.md
  README_CN.md
Labels: lgtm, size/L, approved

#2568 Update pipelines with pydantic
  towhee/pipelines/insert_milvus.py
  towhee/pipelines/search_milvus.py
  towhee/pipelines/sentence_embedding.py
  towhee/pipelines/text_image_embedding.py
  towhee/pipelines/video_copy_detection.py
  towhee/pipelines/video_embedding.py
Labels: lgtm, size/L, approved
