Repository towhee-io/towhee, pull requests merged in 2024-10, with the labels that each got.

#2708 Fix typo in cuda_version parameter
  docs/04-Triton Server/01-triton.md
Labels: lgtm, approved, size/XS

#2710 Fix doc misspelling
  tests/unittests/runtime/test_map_node.py
  tests/unittests/runtime/test_runtime_config.py
  tests/unittests/serve/grpc/test_server.py
  towhee/pipelines/video_copy_detection.py
  towhee/pipelines/video_embedding.py
  towhee/runtime/node_config.py
  towhee/runtime/nodes/node.py
  towhee/serve/grpc/server.py
Labels: size/S

#2713 Fix ci
  .github/workflows/codecov.yml
  tests/unittests/command/test_cmdline.py
Labels: approved, size/M
